### ISSUE TITLE
Package-lock.json merge conflict when having multiple PRs to approve

### ISSUE THREAD

**Issue by Todilo** [tinglesoftware/dependabot-azure-devops#1007]
After dependabot has found multiple npm packages that needs to be updated (I understand grouping is not yet supported) approving one of those PRs will work but that will invalidate all others due to conflict in package-lock.json.

Is there a way to alleviate this problem?

**Comment by mburumaxwell** [comment]
Automatic merge conflict resolution is a feature that would be available in the server component in the future.

With or without groups, the only way to resolve the merge conflicts is to rerun the pipeline/execution. The ruby script will check for PRs with merge conflicts and resolve them. Remember the merge status must be conflict. This can be triggered by attempting merge or restarting merge.
