### ISSUE TITLE
For the PRs created with dependabot, in the PR description have a bunch or weird characters like there's an encoding issue

### ISSUE THREAD

**Issue by bganguly14** [tinglesoftware/dependabot-azure-devops#1077]
**Describe the bug**
in the PR description have a bunch or weird characters like there's an encoding issue

**To Reproduce**
1. Dependabot raise a PR
2. Check the Description section of the PR

**Expected behavior**
There should not be any encoded values in the PR descriptions

**Screenshots**

**Extension (please complete the following information):**
 - Host: [e.g. Azure DevOps, Azure DevOps Server]
 - Version [e.g. 1.2.54]
Azure DevOps

**Additional context**
![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/134032822/e9c87039-b39d-48c0-9a79-635110feae58)

**Comment by mburumaxwell** [comment]
Kindly raise this in the core repository. It has to do with conversion from UTF8 to UTF16, truncating, then converting back to UTF8; which is specific to the Azure DevOps implementation.

**Comment by bganguly14** [comment]
> Kindly raise this in the core repository. It has to do with conversion from UTF8 to UTF16, truncating, then converting back to UTF8; which is specific to the Azure DevOps implementation.

Can you please share the core repository link?
