### ISSUE TITLE
update-script.rb:265:in `block in <main>': undefined method `call' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by chadcampling** [tinglesoftware/dependabot-azure-devops#109]
Hi and thanks for putting this project together.

We've been working on trying to get Dependabot running against one of our Azure DevOps repos to assist in automating the updating of some internal dependencies. After several issues getting our Azure Artifacts feed authenticated we are now encountering the below error.

The error doesn't appear isolated to our internal package feed as the example below is pulling from nuget public package repo.

I have been using the 'latest' docker tag which at this time refers to `tingle/dependabot-azure-devops:0.3.3-ci.7` however I also confirmed the issue against `tingle/dependabot-azure-devops:0.3.0`

I have no Ruby experience so have fumbled through to this point, any pointers on how I can troubleshoot this further?
```
Error updating Nerdbank.GitVersioning from 3.3.37 to 3.4.194 (continuing)
Traceback (most recent call last):
	2: from ./update-script.rb:222:in `<main>'
	1: from ./update-script.rb:222:in `each'
./update-script.rb:265:in `block in <main>': undefined method `call' for nil:NilClass (NoMethodError)
```
```
    docker run --rm -t \
    -e AZURE_ACCESS_TOKEN=$TOKEN \
    -e AZURE_ORGANIZATION=MyOrg \
    -e AZURE_PROJECT=$(System.TeamProject) \
    -e AZURE_REPOSITORY=MyRepo \
    -e DEPENDABOT_PACKAGE_MANAGER=nuget \
    -e DEPENDABOT_DIRECTORY=Utility/Feature/Gateway \
    -e DEPENDABOT_TARGET_BRANCH=master \
    -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=5 \
    -e DEPENDABOT_VERSIONING_STRATEGY=auto \
    -e DEPENDABOT_EXTRA_CREDENTIALS='[{"type":"nuget_feed","token":"BASE64-Encoded-Token=","url":"https://pkgs.dev.azure.com/MyOrg/MyOrg/_packaging/MyRepo_Packages/nuget/v3/index.json"}]' \
    -e AZURE_SET_AUTO_COMPLETE=false \
    -e DEPENDABOT_ALLOW='[{"name":"MyRepo*","type":"nuget"},{"name":"Nerdbank.*","type":"nuget"}]' \
    tingle/dependabot-azure-devops:latest
```

**Comment by mburumaxwell** [comment]
@chadcampling 

We had a similar issue and fixed it via #103.
Could you check if this persists in version `0.4.0` that has just been released?

**Comment by chadcampling** [comment]
Further investigation led to identifying that the DEPENDABOT_ALLOW option was the cause of this and digging deeper it was a typo in our config
`    -e DEPENDABOT_ALLOW='[{"name":"MyRepo*","type":"nuget"},{"name":"Nerdbank.*","type":"nuget"}]' \`
should be 
`    -e DEPENDABOT_ALLOW='[{"name":"MyRepo*","type":"all"},{"name":"Nerdbank.*","type":"all"}]' \`

Reference to Allow types in documentation was key https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates#allow

**Comment by mburumaxwell** [comment]
@chadcampling happy to hear
