### ISSUE TITLE
Issue with Dependabot and Maui Workloads

### ISSUE THREAD

**Issue by indyjason79** [tinglesoftware/dependabot-azure-devops#1140]
I'm trying to set up Dependabot for a Maui app and encountering issues. The extension specifies it "requires macOS or Ubuntu (Windows is not supported)," but the dependabot@1 task tries to build the solution, failing due to missing Maui workloads. When attempting to install them, I receive "Workload ID maui isn't supported on this platform." Why does the task need to build the project to identify package updates? Is there a workaround, or is Maui unsupported with this extension?

**Comment by mburumaxwell** [comment]
That particular logic exists in the core repository. A while back they made the decision to use the NuGet CLI to check for updates which broke a couple of scenarios and they are still fixing them. Two things you can do:
1. Install the necessary workload in a custom docker image which you can then use to run your updates.
2. Create an issue in the core repo to seek resolution. https://github.com/dependabot/dependabot-core

**Comment by mburumaxwell** [comment]
https://github.com/dependabot/dependabot-core/issues/10117
