### ISSUE TITLE
Dependabot fails to read nuget feed (microsoft resources) - no address for api.nuget.org

### ISSUE THREAD

**Issue by JimGeersinga** [tinglesoftware/dependabot-azure-devops#1160]
**Describe the bug**
Dependabot fails to read nuget feed (microsoft resources)
Error: no address for api.nuget.org

**To Reproduce**
1. Have a project reference `Azure.Identity 1.11.3`
2. Run the dependabot@1 task in devops

**Expected behavior**
Create pull requests based on needed dependency updates

**Screenshots**
![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/7780260/b5ffcaf5-3e8a-4ce4-811e-7701ea13ee77)

**Extension (please complete the following information):**
 - Host: Azure DevOps

**Server (please complete the following information):**
 - Region:  westeurope

**Additional context**
The dependabot task is running in a vm using wsl to run the docker image.

**Comment by JimGeersinga** [comment]
It looks like it's a bug in ruby. Changing the DNS server in the docker image could resolve it. Do you maybe have an insight in how to resolve this issue?

**Comment by mburumaxwell** [comment]
You can check changes in https://github.com/tinglesoftware/dependabot-azure-devops/pull/834
