### ISSUE TITLE
Pipeline fails with `fetch': key not found: "FilePath" (KeyError)

### ISSUE THREAD

**Issue by iconics-robertov** [tinglesoftware/dependabot-azure-devops#1190]
**Describe the bug**
After latest update to 1.29.4.751 all our DevOps pipelines are failing with the following error message:

/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.263.0/lib/dependabot/nuget/discovery/workspace_discovery.rb:16:in `fetch': key not found: "FilePath" (KeyError)

This is the full stack of the error: 

/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.263.0/lib/dependabot/nuget/discovery/workspace_discovery.rb:16:in `fetch': key not found: "FilePath" (KeyError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.263.0/lib/dependabot/nuget/discovery/workspace_discovery.rb:16:in `from_json'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.263.0/lib/dependabot/nuget/discovery/discovery_json_reader.rb:69:in `workspace_discovery'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.263.0/lib/dependabot/nuget/discovery/discovery_json_reader.rb:46:in `dependency_set'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.263.0/lib/dependabot/nuget/file_parser.rb:51:in `discovered_dependencies'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/dependabot-nuget-0.263.0/lib/dependabot/nuget/file_parser.rb:34:in `parse'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/call_validation.rb:270:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11463/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
	from bin/update_script.rb:531:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1

Everything was working fine with version 1.29.3.747

**To Reproduce**
We are just running the pipeline. I'm attaching the pipeline definition (azure-pipelines-dependabot.yml) and the dependabot configuration (dependabot.yml)

**Expected behavior**
Dependabot pipeline should not throw any errors

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version 1.29.4.751

**Server (please complete the following information):**
 - Region: Central US
 - Version: -unknnown

[dependabot-configuration.zip](https://github.com/user-attachments/files/16116830/dependabot-configuration.zip)

**Comment by rhyskoedijk** [comment]
I'm getting this error on a fresh build too, even on 1.29.3 and earlier versions of the updater.

It seems that https://github.com/dependabot/dependabot-core/pull/10025 changed the native NuGet helpers in dependabot core 0.264 and because of this all builds of this project now use the new tools due to the way the docker images are built.

https://github.com/tinglesoftware/dependabot-azure-devops/blob/4fc47639abc6509e749c1e4ddfca1cb6459ebf99/updater/Dockerfile#L1-L4

I think the eaiest fix is to update the Rubygems to 0.264 so they match again. The long term fix is to try find a solution to that TODO comment.

**Comment by iconics-robertov** [comment]
Thank you very much for looking into this and for the quick answer!

**Comment by philipp-naused** [comment]
We had the same problem, but it seems to be fixed now in `1.29.5`.
Thank you.
