### ISSUE TITLE
Nuget automatic update failure

### ISSUE THREAD

**Issue by prajwalkumar9** [tinglesoftware/dependabot-azure-devops#1201]
**Describe the bug**
When we run the dependabot on a project which downloads the packages from nuget, its getting failed. Although its working fine with NPM package.

**To Reproduce**
1. Try to run dependabot on any project which is downloading packages from nuget.

**Screenshots**
![Dependabot_Issue](https://github.com/tinglesoftware/dependabot-azure-devops/assets/106602044/39372b29-fdb7-43bd-9804-aa15cc6c378b)

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version : 1.29.5.760

**Comment by rhyskoedijk** [comment]
I had this issue too, it is caused by a bug in dependabot-core, see: https://github.com/dependabot/dependabot-core/pull/10156 and https://github.com/dependabot/dependabot-core/pull/10159

It was happening for me because I had a vulnerable package that could only become nonvulernable if it upgrade to the next major version. However, I had "ignore" restrictions in dependabot.yml prevented it from upgrading to major versions, so it ended up not being able to resolve "lowest_security_fix_version". I ended up manually updating the package to work around the bug. Your issue might be different though.

It looks like they [dependabot-core] have patched the problem in the base updater, but I am not sure if it is fully fixed in the NuGet updater or not.

**Comment by tyler-hagen** [comment]
I have this same issue even without any ignore restrictions in my dependabot.yml

**Comment by prajwalkumar9** [comment]
@tyler-hagen : Same here, still facing the issue.

**Comment by rhyskoedijk** [comment]
@prajwalkumar9 @tyler-hagen does it work on tag 1.29.6?
I just ran it and am no longer having the error; seems dependabot-core 0.265.0 fixed it for me.

**Comment by prajwalkumar9** [comment]
@rhyskoedijk : No it did not fix for me

**Comment by rhyskoedijk** [comment]
@prajwalkumar9 are you able to share your dependabot.yml config and the name of the package it is failing on, it should mention it above the error/stack trace.

**Comment by tyler-hagen** [comment]
@prajwalkumar9 @rhyskoedijk 

I solved my problem, it was actually solved by the workaround you (@rhyskoedijk) commented here: https://github.com/tinglesoftware/dependabot-azure-devops/issues/921#issuecomment-2162273558

@prajwalkumar9 Are you getting nuget errors when dependabot tries to build your projects? If so, try this out.

**Comment by prajwalkumar9** [comment]
With the latest build of dependabot and core i see this following issue. It says Authentication Failure. Attaching the log from the pipeline for reference,
![Dependabot_Error](https://github.com/user-attachments/assets/4186a75f-0f0d-48b7-94db-9f4f10ccfd02)

**Comment by rhyskoedijk** [comment]
@prajwalkumar9 are you using private Azure DevOps NuGet feeds in that project? If yes, have you tried the workaround in https://github.com/tinglesoftware/dependabot-azure-devops/issues/921#issuecomment-2162273558?

**Comment by prajwalkumar9** [comment]
@rhyskoedijk : Yes using the private azure devops nuget  feeds. is it about passing the extra environment variable to the dependabot tag?

**Comment by rhyskoedijk** [comment]
@prajwalkumar9 yes, until https://github.com/dependabot/dependabot-core/pull/8927 is resolved, you have to use the  `WORKAROUND_CMD` hack if your project uses Azure DevOps feeds.

```yml
- task: dependabot@1
    inputs:
      extraEnvironmentVariables: 'WORKAROUND_CMD=sh -c "$(curl -fsSL https://aka.ms/install-artifacts-credprovider.sh)";VSS_NUGET_EXTERNAL_FEED_ENDPOINTS={"endpointCredentials":[{"endpoint":"https://pkgs.dev.azure.com/...your_feed_slug.../nuget/v3/index.json","username":"unused","password":"$(System.AccessToken)"}]}'

```
