### ISSUE TITLE
Fix code scanning alert - Incomplete URL substring sanitization

### ISSUE THREAD

**Issue by mburumaxwell** [tinglesoftware/dependabot-azure-devops#1234]
Tracking issue for:
- [ ] https://github.com/tinglesoftware/dependabot-azure-devops/security/code-scanning/23

**Comment by mburumaxwell** [comment]
@rhyskoedijk

**Comment by rhyskoedijk** [comment]
Can you copy the info in to this issue? it gives me 404 error when clicking the link

**Comment by mburumaxwell** [comment]
Hadn't realized it is not public. Maybe we should have you as a maintainer....

<img width="1288" alt="Screenshot 2024-07-24 at 10 47 15 AM" src="https://github.com/user-attachments/assets/dfe8a37d-9dc2-4e8a-88d8-86511f16827f">

<img width="1288" alt="Screenshot 2024-07-24 at 10 51 54 AM" src="https://github.com/user-attachments/assets/f43aae96-3a04-4d84-bd52-0f2f9d72fb1a">

<img width="1512" alt="Screenshot 2024-07-24 at 10 52 24 AM" src="https://github.com/user-attachments/assets/e04b2f61-9c7f-402f-90cd-94f2d4b26b88">
