### ISSUE TITLE
Dependabot Issue

### ISSUE THREAD

**Issue by prajwalkumar9** [tinglesoftware/dependabot-azure-devops#1269]
With this below version of dependabot resulting in a issue. 
![image](https://github.com/user-attachments/assets/9d7c06d8-4b68-43d0-9e63-a710a3f2269a)

Error Described in the below screen shot

![image](https://github.com/user-attachments/assets/c6125631-f0fa-4041-811d-ed8b76f8aa88)

**Comment by rhyskoedijk** [comment]
This is likely a duplicate of #1257; stack trace matches
