### ISSUE TITLE
Question: Does this work with the hosted agents in Azure devops?

### ISSUE THREAD

**Issue by MikaelEliasson** [tinglesoftware/dependabot-azure-devops#137]
We tried running with the hosted agents but it fails like this. The message is not that helpful so I'm a bit unsure if it's the hosted agent or something else. It would be nice to confirm before we setup self hosted agents to try.

![image](https://user-images.githubusercontent.com/888296/120998119-106d2480-c788-11eb-96b7-4a65ca1987be.png)

**Comment by petejespersqbe** [comment]
@MikaelEliasson I'm successfully using the hosted `ubuntu-18.04` pool.

**Comment by MikaelEliasson** [comment]
@petejespersqbe Thank you! I got the same error with that pool so then I know I need to look at other reasons.
