### ISSUE TITLE
Error creating Pull request for Maven

### ISSUE THREAD

**Issue by olamy** [tinglesoftware/dependabot-azure-devops#1391]
**Describe the bug**
Error creating pull request for Maven dependencies 

**Categorization**
- [x] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**Repository**
private

**To Reproduce**
Having a Maven dependency to `org.junit:junit-bom-xxxx`
Enable dependabot task v2

**Expected behavior**

Having a pull request with the upgrade of `org.junit:junit-bom-xxxx`

**Logs and screenshots**
error logs
```

    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.35.955/node_modules/typed-rest-client/RestClient.js:7:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 400,
  result: {
    '$id': '1',
    innerException: null,
    message: "TF401021: 'refs/heads/dependabot/maven/master/org.junit:junit-bom-5.11.2' is not a valid name for a Git ref. Visit https://go.microsoft.com/fwlink/?LinkId=800646 for more information on Git ref naming.\r\n" +
      'Parameter name: newPush',
    typeName: 'Microsoft.TeamFoundation.SourceControl.WebServer.InvalidArgumentValueException, Microsoft.TeamFoundation.SourceControl.WebServer',
    typeKey: 'InvalidArgumentValueException',
    errorCode: 0,
    eventId: 0
  },


```

**Comment by rhyskoedijk** [comment]
@olamy thanks for the report, this will be fixed in https://github.com/tinglesoftware/dependabot-azure-devops/pull/1392

**Comment by olamy** [comment]
Thanks
