### ISSUE TITLE
Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-pip:1.34' locally

### ISSUE THREAD

**Issue by fensoft** [tinglesoftware/dependabot-azure-devops#1405]
**Describe the bug**
`Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-pip:1.34' locally` error when using `dependabot@1`

**To Reproduce**
Use this pipeline code:
```
steps:
  - task: dependabot@1
```

I don't want to use dependabot@2 as: "Work in progress; dependabot@V2 is still under development and this document may change without notice up until general availability (GA)."

**Comment by grixxie** [comment]
I am running into the same issue for ```ghcr.io/tinglesoftware/dependabot-updater-nuget:1.34```. Same repro steps.

I knew dependabot@2 was available but didn't expect dependabot@1 to be turned off!

**Comment by mburumaxwell** [comment]
Fixed in https://github.com/tinglesoftware/dependabot-azure-devops/pull/1406
Released in https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.36.1

**Comment by grixxie** [comment]
My ADO extension just updated and my pipeline works now - thanks!
