### ISSUE TITLE
Unable to create PR -  not a valid name for a Git ref error

### ISSUE THREAD

**Issue by Hoang-Minh** [tinglesoftware/dependabot-azure-devops#1409]
Even with the new update after #1391 is merged and fixed, I still have this error on azure pipelines. 
```
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code using [Dependabot CLI](https://github.com/dependabot/cli)
Version      : 2.36.1000
Author       : Tingle Software
Help         : https://github.com/tinglesoftware/dependabot-azure-devops/issues
```

Describe the bug
Error creating pull request for nuget dependencies

Categorization

 This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

Repository
private

To Reproduce:

Enable dependabot task v2

Expected behavior
Having a pull request created successfully.

Logs and screenshots
error logs

```
Creating pull request 'Bump FluentAssertions from 6.12.0 to 6.12.1'...
 - Pushing 1 file change(s) to branch 'dependabot/nuget/dev/FluentAssertions-6.12.1'...
🌎 🠊 [POST] https://xxx.visualstudio.com/TTC%20Property%20Tax%20Online%20Payment/_apis/git/repositories/TTCWebApi/pushes
🌎 🠈 [400] Bad Request
{"$id":"1","innerException":null,"message":"TF401021: 'refs/heads/dependabot/nuget/dev/FluentAssertions-6.12.1' is not a valid name for a Git ref. Visit https://go.microsoft.com/fwlink/?LinkId=800646 for more information on Git ref naming.","typeName":"Microsoft.TeamFoundation.Git.Server.InvalidGitRefNameException, Microsoft.TeamFoundation.Git.Server","typeKey":"InvalidGitRefNameException","errorCode":0,"eventId":3000}
##[error]Failed to create pull request: Error: Request to 'https://xxx.visualstudio.com/TTC%20Property%20Tax%20Online%20Payment/_apis/git/repositories/TTCWebApi/pushes' failed: 400 Bad Request
Error: Request to 'https://xxx.visualstudio.com/TTC%20Property%20Tax%20Online%20Payment/_apis/git/repositories/TTCWebApi/pushes' failed: 400 Bad Request
    at AzureDevOpsWebApiClient.restApiRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/azure-devops/AzureDevOpsWebApiClient.js:521:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AzureDevOpsWebApiClient.restApiPost (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/azure-devops/AzureDevOpsWebApiClient.js:498:16)
    at async AzureDevOpsWebApiClient.createPullRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/azure-devops/AzureDevOpsWebApiClient.js:156:26)
    at async DependabotOutputProcessor.process (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/dependabot-cli/DependabotOutputProcessor.js:67:42)
    at async DependabotCli.update (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/dependabot-cli/DependabotCli.js:113:51)
    at async run (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/index.js:75:57)
```

**Comment by sailro** [comment]
I'm hitting the exact same issue.

**Comment by sailro** [comment]
Okay I found the culprit.

To try the dependabot task, I created a `dependabot` branch. But it seems to conflict with the branch path used to create branches for PRs like 'dependabot/nuget/main/src/detection-6eed6abb33'

Dropping the branch then creating a new one named `deploy-dependabot` fixed the issue.

So I guess you are using a `dependabot` branch as well @Hoang-Minh :)

**Comment by Hoang-Minh** [comment]
@sailro : Yes, my branch is also named dependabot as well lolol

If this is the case, the readme document needs to be updated.

Thank you @sailro

**Comment by Hoang-Minh** [comment]
@sailro unfortunately it does not work for me :(

![image](https://github.com/user-attachments/assets/2e318925-c8e9-4178-b638-22e370ac93ae)

**Comment by sailro** [comment]
Make sure you deleted the remote branch as well (not only the local one).

`git push --delete origin dependabot`

**Comment by rhyskoedijk** [comment]
@sailro thanks for that, good find.
@mburumaxwell I can make a change for this, what is your preference? The issue looks like it applies to all task versions, not specifically V2. Ideas:

1. Add documentation to explain that the "/dependabot/..." branch prefix is reserved; don't create branches with that name.
2. Add a check to the task which throws an error if it detects the branch prefix is already in use by another branch.

**Comment by mburumaxwell** [comment]
@rhyskoedijk yes, those changes are welcome.
