### ISSUE TITLE
ADO API responds with GitObjectDoesNotExistException when pushing file changes to branch

### ISSUE THREAD

**Issue by grixxie** [tinglesoftware/dependabot-azure-devops#1413]
Hi,

I am facing the following problem with my dependabot (v2) pipeline. My pipeline looks like so:
```
stages:
- stage: dependabot
  jobs:
  - job: dependabot
    pool:
      name: my-selfhosted-pool
    steps:
    - task: dependabot@2
      displayName: 'Run Dependabot'
      inputs:
        setAutoComplete: true
        abandonUnwantedPullRequests: false
        azureDevOpsAccessToken: $(System.AccessToken)
        gitHubAccessToken: $(GHTOKEN)
```

My dependabot.yml config looks like so:
```
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: 'dependabot/releases/release-15'
    schedule:
      interval: "daily"
```

My pipeline is erroring with the following error snippet, when it tries to call the /pushes endpoint of my repo via the ADO API to push the file changed. It is complaining that an object does not exist; I am not sure what this object is refering to. My ```release-15``` branch mentioned in my dependabot.yml definitely exists and is a different ID to the one mentioned in the error...
The error:
```
Creating pull request 'Bump Microsoft.AspNetCore.SpaServices.Extensions from 8.0.8 to 8.0.10'...
 - Pushing 1 file change(s) to branch 'dependabot/nuget/dependabot/releases/release-15/Microsoft.AspNetCore.SpaServices.Extensions-8.0.10'...
🌎 🠊 [POST] https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/pushes
🌎 🠈 [500] Internal Server Error
{"$id":"1","innerException":null,"message":"TF401035: The object '5eae8e97b8105c3b55acb7ed3d41233062e2bcf7' does not exist.","typeName":"Microsoft.TeamFoundation.Git.Server.GitObjectDoesNotExistException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitObjectDoesNotExistException","errorCode":0,"eventId":3000}
##[error]Failed to create pull request: Error: Request to 'https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/pushes' failed: 500 Internal Server Error
Error: Request to 'https://dev.azure.com/ORG/PROJECT/_apis/git/repositories/REPO/pushes' failed: 500 Internal Server Error
    at AzureDevOpsWebApiClient.restApiRequest (/agent/_work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/azure-devops/AzureDevOpsWebApiClient.js:521:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AzureDevOpsWebApiClient.restApiPost (/agent/_work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/azure-devops/AzureDevOpsWebApiClient.js:498:16)
    at async AzureDevOpsWebApiClient.createPullRequest (/agent/_work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/azure-devops/AzureDevOpsWebApiClient.js:156:26)
    at async DependabotOutputProcessor.process (/agent/_work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/dependabot-cli/DependabotOutputProcessor.js:67:42)
    at async DependabotCli.update (/agent/_work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/utils/dependabot-cli/DependabotCli.js:113:51)
    at async run (/agent/_work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1000/index.js:75:57)
```

Please advise if I am doing something wrong. If you need any more information then please let me know and I will provide. Thank you.
If anyone else is also experiencing this issue please respond!

**Comment by rhyskoedijk** [comment]
@grixxie thanks for the report;
do you have an existing branch named `dependabot/releases/release-15`? If so, I would guess that this is causing problems as Dependabot is wanting to use the `dependabot/` prefix for the pull requests it is trying to create. If not, do you know what branch the commit `5eae8e97b8105c3b55acb7ed3d41233062e2bcf7` belongs to? Is it your target branch or another branch?

If you haven't already tried and it is possible to do so, I'd recommend renaming any branches starting with `dependabot/`; I'll look at adding a config option to change this prefix as it sounds like there are a few people who are already using this prefix.

**Comment by rhyskoedijk** [comment]
just a follow up to this; I've tried to reproduce your issue by doing the following:

- Run update targeting default branch and `dependabot/releases/release-15` already exists
- Run update targeting `dependabot/releases/release-15` and `dependabot/releases/release-15` already exists
- Run update targeting `dependabot/releases/release-15` and `dependabot/releases/release-15` does not exist

I was not able to reproduce the issue.
Are you able to provide any more information that would help reproduce your issue? Can you identify what branch git commit `5eae8e97b8105c3b55acb7ed3d41233062e2bcf7` belongs to?

**Comment by grixxie** [comment]
Hi - thanks for the response.

I also tested rerunning v2 with changes to the target branch name and ran into my same issue.

To answer your question, I have no idea where that commit is coming from, I could not find it when I was doing my testing yesterday. I will be doing some more testing later today though so will let you know the outcome of that.

You not being able to reproduce this issue definitely makes it seem like I'm doing something not quite right though...

**Comment by DaleMckeown** [comment]
I have also just tried to use v2 for the first time and and running into this issue.

```
Creating pull request 'Bump the npm group in /{folderName} with 17 updates'...
 - Pushing 1 file change(s) to branch 'dependabot/npm_and_yarn/dependabot/dependabot_grouping_v2/{folderName}/npm-d631ece976'...
🌎 🠊 [POST] https://dev.azure.com/{orgName}/{projectName}/_apis/git/repositories/{repoName}/pushes
🌎 🠈 [500] Internal Server Error
{"$id":"1","innerException":null,"message":"TF401035: The object 'abdceb5590885eeb4810012ade73d8125ae03864' does not exist.","typeName":"Microsoft.TeamFoundation.Git.Server.GitObjectDoesNotExistException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitObjectDoesNotExistException","errorCode":0,"eventId":3000}
##[error]Failed to create pull request: Error: Request to 'https://dev.azure.com/{orggName}/{projectName}/_apis/git/repositories/{projectName}/pushes' failed: 500 Internal Server Error
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;]Failed to create pull request: Error: Request to 'https://dev.azure.com/{orggName}/{projectName}/_apis/git/repositories/{repoName}/pushes' failed: 500 Internal Server Error
Error: Request to 'https://dev.azure.com/{orgName}/{projectName}/_apis/git/repositories/{repoName}/pushes' failed: 500 Internal Server Error
    at AzureDevOpsWebApiClient.restApiRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/azure-devops/AzureDevOpsWebApiClient.js:521:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AzureDevOpsWebApiClient.restApiPost (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/azure-devops/AzureDevOpsWebApiClient.js:498:16)
    at async AzureDevOpsWebApiClient.createPullRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/azure-devops/AzureDevOpsWebApiClient.js:156:26)
    at async DependabotOutputProcessor.process (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/dependabot-cli/DependabotOutputProcessor.js:67:42)
    at async DependabotCli.update (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/dependable-cli/DependabotCli.js:113:51)
    at async run (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/index.js:75:57)
```

I also cannot find that commit ID at all, it must be one being created locally by Dependabot?  I've ran the job multiple times and each time the `objectId` is different.

The branch `dependabot/dependabot_grouping_v2` definitely exists.

When running this, I have two package ecosystems. NuGet, which runs successfully, and then NPM, which fails.

**Comment by grixxie** [comment]
@rhyskoedijk I have found the same as @DaleMckeown post above; running the command ```git branch -a --contains <SHA>``` returns no results. I also think that this commit is one being created locally by Dependabot, but has failed to push to remote. This would explain why ADO API returns 500 when trying to create the PR.

**Comment by DaleMckeown** [comment]
If I flip the order of my package ecosystems to run NPM first and then NuGet, NPM runs successfully and NuGet errors instead. So it seems to be an issue related to processing multiple package ecosystems in the same Dependabot run.

**Comment by rhyskoedijk** [comment]
> If I flip the order of my package ecosystems to run NPM first and then NuGet, NPM runs successfully and NuGet errors instead. So it seems to be an issue related to processing multiple package ecosystems in the same Dependabot run.

Thanks @DaleMckeown, that is a good lead and something that I have not tested yet; I will investigate.

**Comment by grixxie** [comment]
> > If I flip the order of my package ecosystems to run NPM first and then NuGet, NPM runs successfully and NuGet errors instead. So it seems to be an issue related to processing multiple package ecosystems in the same Dependabot run.
> 
> Thanks @DaleMckeown, that is a good lead and something that I have not tested yet; I will investigate.

This may be a good lead to find the root of the problem. However, just to point out my dependabot.yml config in the description of this issue, I'm only using a single package ecosystem (NuGet) and still running into this issue!

**Comment by rhyskoedijk** [comment]
> This may be a good lead to find the root of the problem. However, just to point out my dependabot.yml config in the description of this issue, I'm only using a single package ecosystem (NuGet) and still running into this issue!

Understood; At this point I'm just looking for a way to reproduce the error, even if it isn't your original scenario.
I have just tried using a run with multiple package ecosystems (NPM and NuGet), but unfortunately this didn't fail for me either.

![image](https://github.com/user-attachments/assets/cf7521a4-4c69-4149-8ee5-5f95bfbbb30c)

I am out of ideas for now; If anybody is able to produce a minimal reproduction of their dependabot.yml and *.csproj that causes the error, I will revisit this.

**Comment by beytun** [comment]
I am facing the exact issue. My pipeline was successful on 14th October. The next execution on 21st October failed with this issue. I see a new version of this task has been released meanwhile.

**Comment by rhyskoedijk** [comment]
@grixxie, @DaleMckeown, @beytun are git submodules used in your repositories facing this issue? 

I was able to reproduce the same error message if my repo had a submodule and Dependabot had updated one of the files within the submodule. I will continue to investigate, but curious if this is the same scenario or just a different way of getting the same error.

**Comment by DaleMckeown** [comment]
There are no git submodules in the project I have been working on that is experiencing this issue.

I still need to try and do a minimal report to reproduce this issue. I'll try and get it done this week.

**Comment by Patrick-3000** [comment]
Same issue here: 

We were using Dependabot for MS Azure Devops V1 but as this version got deprecated, we switched to V2.

However, Dependabot is not able to create Pull Requests as it fails with

```
Creating pull request '[npm-Updates]: Bump lru-cache from 11.0.0 to 11.0.1'...
 - Pushing 1 file change(s) to branch 'dependabot/npm_and_yarn/main/lru-cache-11.0.1'...
🌎 🠊 [POST] [https://***/***/***/_apis/git/repositories/***/pushes?api-version=5.0](https://%2A%2A%2A/***/***/_apis/git/repositories/***/pushes?api-version=5.0)
🌎 🠈 [500] Internal Server Error
{"$id":"1","innerException":null,"message":"TF401035: The object '450425a1a469b12373a3e49b8bd23bfca51a11e3' does not exist.","typeName":"Microsoft.TeamFoundation.Git.Server.GitObjectDoesNotExistException, Microsoft.TeamFoundation.Git.Server","typeKey":"GitObjectDoesNotExistException","errorCode":0,"eventId":3000}
##[error]Failed to create pull request: Error: Request to '[https://***/***/***/_apis/git/repositories/***/pushes?api-version=5.0'](https://%2A%2A%2A/***/***/_apis/git/repositories/***/pushes?api-version=5.0%27) failed: 500 Internal Server Error
Error: Request to '[https://***/***/***/_apis/git/repositories/***/pushes?api-version=5.0'](https://%2A%2A%2A/***/***/_apis/git/repositories/***/pushes?api-version=5.0%27) failed: 500 Internal Server Error
    at AzureDevOpsWebApiClient.restApiRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.37.1025/utils/azure-devops/AzureDevOpsWebApiClient.js:551:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AzureDevOpsWebApiClient.restApiPost (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.37.1025/utils/azure-devops/AzureDevOpsWebApiClient.js:528:16)
    at async AzureDevOpsWebApiClient.createPullRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.37.1025/utils/azure-devops/AzureDevOpsWebApiClient.js:177:26)
    at async DependabotOutputProcessor.process (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.37.1025/utils/dependabot-cli/DependabotOutputProcessor.js:81:42)
    at async DependabotCli.update (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.37.1025/utils/dependabot-cli/DependabotCli.js:116:55)
    at async run (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.37.1025/index.js:82:57)
```

For me this looks like a bug (especially considering that with V1 we could create PRs), but maybe anybody has a suggestion of what I could try as I am out of ideas...

**Comment by bhiggins14** [comment]
> I am facing the exact issue. My pipeline was successful on 14th October. The next execution on 21st October failed with this issue. I see a new version of this task has been released meanwhile.
> 
> Successful pipeline
> 
> > Task         : Dependabot
> > Description  : Automatically update dependencies and vulnerabilities in your code using [Dependabot CLI](https://github.com/dependabot/cli)
> > Version      : 2.35.955
> > Author       : Tingle Software
> > Help         : https://github.com/tinglesoftware/dependabot-azure-devops/issues
> 
> Failed pipeline
> 
> > Task         : Dependabot
> > Description  : Automatically update dependencies and vulnerabilities in your code using [Dependabot CLI](https://github.com/dependabot/cli)
> > Version      : 2.36.1003
> > Author       : Tingle Software
> > Help         : https://github.com/tinglesoftware/dependabot-azure-devops/issues
> 
> Update: I just tried pinning the version 2.35.955 in my pipeline and it worked fine. This can be used a workaround till the issue is found out and fixed.

hey thanks for the post. Can you explain how you did this? Not seeing anything concrete on how to select an extension version for azure devops

**Comment by rhyskoedijk** [comment]
I have not been able to reproduce this issue outside of using a git submodule to trick the updater in to updating files that don't actually exist, which doesn't seem to be the problem reported here.

I have submitted a change in https://github.com/tinglesoftware/dependabot-azure-devops/pull/1452 that will add more debug info to failed DevOps API calls; Once released, it will hopefully provide more info in to the cause of this issue.

**Comment by Patrick-3000** [comment]
> Update: I just tried pinning the version 2.35.955 in my pipeline and it worked fine. This can be used a workaround till the issue is found out and fixed.

@bhiggins14: Could you please explain how you managed to pin the Dependabot version? I do not see an option for this here: https://marketplace.visualstudio.com/items?itemName=tingle-software.dependabot

**Comment by beytun** [comment]
@Patrick-3000 
``` yaml
- task: dependabot@2.35.955
```

**Comment by Patrick-3000** [comment]
@beytun: thank you very very much, this actually helps us a lot!

**Comment by rhyskoedijk** [comment]
Could somebody still facing this issue do an update using v1.38.1 with "Enable system diagnostics" selected on the pipeline run? This version should dump more info about the failed push that will hopefully provide some clues as to what is going on.

My assumption is that the error is caused by pushing a file that shouldn't be committed, but there could be more to it than just that.

**Comment by DaleMckeown** [comment]
@rhyskoedijk  I've got a log for you. Is there any specific bit you're interested in?

**Comment by rhyskoedijk** [comment]
@DaleMckeown thanks, that log is very helpful. It looks like on the 2nd update, the local git repo is not being reset correctly. It is likely that this issue was introduced by https://github.com/tinglesoftware/dependabot-azure-devops/pull/1382, which would match with the comments above suggesting this issue started from v2.35.955.

If you add `targetRepositoryName: '$(Build.Repository.Name)'` to your task inputs, does the issue still happen?

**Comment by DaleMckeown** [comment]
@rhyskoedijk  Do I Add that to the Dependabot task? i.e.:

```
      - task: dependabot@2
        displayName: Run Dependabot
        inputs:
          mergeStrategy: squash
          setAutoComplete: true
          targetRepositoryName: '$(Build.Repository.Name)'
```

**Comment by rhyskoedijk** [comment]
Yes

**Comment by DaleMckeown** [comment]
@rhyskoedijk 

With that it fails to find my config file:

```
##[debug]Evaluating condition for step: 'Run Dependabot'
##[debug]Evaluating: SucceededNode()
##[debug]Evaluating SucceededNode:
##[debug]=> True
##[debug]Result: True
Starting: Run Dependabot
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code using [Dependabot CLI](https://github.com/dependabot/cli)
Version      : 2.38.1062
Author       : Tingle Software
Help         : https://github.com/tinglesoftware/dependabot-azure-devops/issues
==============================================================================
##[debug]Using node path: /home/vsts/agents/3.246.0/externals/node20_1/bin/node
##[debug]system.debug=True
##[debug]DistributedTask.Tasks.Node.SkipDebugLogsWhenDebugModeOff=True
##[debug]agent.TempDirectory=/home/vsts/work/_temp
##[debug]loading inputs and endpoints
##[debug]loading INPUT_SKIPPULLREQUESTS
##[debug]loading INPUT_ABANDONUNWANTEDPULLREQUESTS
##[debug]loading INPUT_COMMENTPULLREQUESTS
##[debug]loading INPUT_SETAUTOCOMPLETE
##[debug]loading INPUT_MERGESTRATEGY
##[debug]loading INPUT_AUTOAPPROVE
##[debug]loading INPUT_STOREDEPENDENCYLIST
##[debug]loading INPUT_TARGETREPOSITORYNAME
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
##[debug]loaded 12
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]Checking for `docker` install...
##[debug]which 'docker'
##[debug]found: '/usr/bin/docker'
##[debug]Checking for `go` install...
##[debug]which 'go'
##[debug]found: '/usr/bin/go'
##[debug]System.TeamFoundationCollectionUri=https://dev.azure.com/{redacted}/
##[debug]No virtual directory detected; Running for Azure DevOps Services.
##[debug]System.TeamProjectId=bc32d8ef-8cfc-42cc-a120-d205f5436004
##[debug]System.TeamProject=UniLincoln
##[debug]targetRepositoryName=UniLincoln
##[debug]Custom repository provided; Running update for remote repository.
##[debug]gitHubAccessToken=undefined
##[debug]gitHubConnection=undefined
##[debug]azureDevOpsUser=undefined
##[debug]azureDevOpsAccessToken=undefined
##[debug]azureDevOpsServiceConnection=undefined
##[debug]No custom token provided. The SystemVssConnection's AccessToken shall be used.
##[debug]SystemVssConnection auth param AccessToken = ***
##[debug]authorEmail=undefined
##[debug]authorName=undefined
##[debug]setAutoComplete=true
##[debug]mergeStrategy=squash
##[debug]autoCompleteIgnoreConfigIds=undefined
```

**Comment by rhyskoedijk** [comment]
Ah sorry, you'll need the DevOps access token input set too, e.g:

```yaml
      - task: dependabot@2
        inputs:
          targetRepositoryName: '$(Build.Repository.Name)'
          azureDevOpsAccessToken: '$(System.AccessToken)' # or whatever access token you normally use for running Dependabot as
```

**Comment by DaleMckeown** [comment]
> Ah sorry, you'll need the DevOps access token input set too, e.g:
> 
> ```yaml
>       - task: dependabot@2
>         inputs:
>           targetRepositoryName: '$(Build.Repository.Name)'
>           azureDevOpsAccessToken: '$(System.AccessToken)' # or whatever access token you normally use for running Dependabot as
> ```

Apologies, got distracted with other work stuff. I'll give this a go tomorrow.

**Comment by bhiggins14** [comment]
hey I'm someone who has been following the thread with the same issue. 

Trying to do the fix and I'm having issues passing my pat to the dependabot.yaml config from azure pipeline

Here's my pipeline

``` parameters:
 - name: ADO_PAT
   displayName: ADO_PAT
   default: ""
   type: string

pool:
  vmImage: 'ubuntu-latest'

variables:
  System.Debug: false

jobs:
- job: Build
  variables:
     ADO_PAT: ${{ parameters.ADO_PAT }}
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: dependabot@2
    displayName: DependaBot
    env:
      ADO_PAT: ${{ variables.ADO_PAT }}
    inputs:
      targetRepositoryName: '$(Build.Repository.Name)'
      skipPullRequests: false
      azureDevOpsAccessToken: '$(System.AccessToken)' 
```

Here's my dependabot.yaml

```
version: 2
registries:
  private:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/***/***/_packaging/***/nuget/v3/index.json
    token: PAT:${{  variables.ADO_PAT  }}
    key: contract-feed
updates:
- package-ecosystem: nuget
  directory: "/"
  registries:
    - private
  schedule:
    interval: daily
  open-pull-requests-limit: 25
```
Getting 401s when trying to access my feed

updater | +---------------------------------------+
updater | |                Errors                 |
updater | +---------------------------------------+
updater | | private_source_authentication_failure |
updater | +---------------------------------------+

**Comment by rhyskoedijk** [comment]
@bhiggins14 you probably need to replace `token: PAT:${{  variables.ADO_PAT  }}` with `token: PAT:${{ADO_PAT}}`; You can only reference environment variables. See the purple tips in [configuring private feeds and registries](https://github.com/tinglesoftware/dependabot-azure-devops?tab=readme-ov-file#configuring-private-feeds-and-registries).

**Comment by DaleMckeown** [comment]
> Ah sorry, you'll need the DevOps access token input set too, e.g:
> 
> ```yaml
>       - task: dependabot@2
>         inputs:
>           targetRepositoryName: '$(Build.Repository.Name)'
>           azureDevOpsAccessToken: '$(System.AccessToken)' # or whatever access token you normally use for running Dependabot as
> ```

Sorry, I got distracted with other stuff. I'll give this a go tomorrow.

**Comment by DaleMckeown** [comment]
@rhyskoedijk 

I've tried this a few times, I can't get it working. It keeps telling me that I don't have an access token, despite the debug output above stating that I do:

```
##[debug]azureDevOpsAccessToken provided, using for authenticating
##[debug]authorEmail=undefined
##[debug]authorName=undefined
##[debug]setAutoComplete=true
##[debug]mergeStrategy=squash
##[debug]autoCompleteIgnoreConfigIds=undefined
##[debug]storeDependencyList=false
##[debug]autoApprove=false
##[debug]autoApproveUserToken=undefined
##[debug]experiments=undefined
##[debug]System.Debug=True
##[debug]targetUpdateIds=undefined
##[debug]securityAdvisoriesFile=undefined
##[debug]skipPullRequests=false
##[debug]commentPullRequests=false
##[debug]abandonUnwantedPullRequests=false
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Processed: ##vso[task.setsecret]***
##[debug]Attempting to fetch configuration file via REST API ...
##[debug]GET [https://***/***/***/_apis/git/repositories/***/items?path=/.azuredevops/dependabot.yml](https://%2A%2A%2A/***/***/_apis/git/repositories/***/items?path=/.azuredevops/dependabot.yml)
##[debug]task result: Failed
##[error]No access token has been provided to access '[https://***/***/***/_apis/git/repositories/***/items?path=/.azuredevops/dependabot.yml'](https://%2A%2A%2A/***/***/_apis/git/repositories/***/items?path=/.azuredevops/dependabot.yml%27)
```

**Comment by rhyskoedijk** [comment]
@DaleMckeown no worries, I did some very rough testing the other day and I am fairly confident that reverting https://github.com/tinglesoftware/dependabot-azure-devops/pull/1382 would fix the issue. I hope to have a PR for it this weekend.

**Comment by bhiggins14** [comment]
hey @rhyskoedijk  the settings you gave me worked worked and I was able to generate PRs successfully with 
```
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code using [Dependabot CLI](https://github.com/dependabot/cli)
Version      : 2.38.1062
```

**Comment by rhyskoedijk** [comment]
This _should_ be fixed by https://github.com/tinglesoftware/dependabot-azure-devops/pull/1478.

**Comment by rhyskoedijk** [comment]
Could everyone impacted by this please test again using [1.38.2](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.38.2)? I know at least one instance of this error is fixed, but if there are still scenarios which aren't fixed, it would be good to get a copy of your logs so I can investigate further. Thanks.

**Comment by DaleMckeown** [comment]
@rhyskoedijk FYI It fixed my case.
