### ISSUE TITLE
Adding npm registry credentials through pipeline variables causes `concat': no implicit conversion of String into Array (TypeError)

### ISSUE THREAD

**Issue by MassivDash** [tinglesoftware/dependabot-azure-devops#142]
I have a issue configuring the npm credentials though Azure Step Extension in the variables section of the pipeline. 
Adding DEPENDABOT_EXTRA_CREDENTIALS with the example from the docs (a single array with one object)  causes 

```
./update-script.rb:114:in `concat': no implicit conversion of String into Array (TypeError)
	from ./update-script.rb:114:in `<main>'

```

**Comment by mburumaxwell** [comment]
Hi @MassivDash please share what inputs you are providing to better understand why this may be the case.
