### ISSUE TITLE
Running Dependabot@2 causing 500 internal sql exception via pipeline in ADO

### ISSUE THREAD

**Issue by mouaxiong1980** [tinglesoftware/dependabot-azure-devops#1438]
**Describe the bug**
I've added the dependabot extension to our ADO.  When I try to go and run the pipeline to run dependabot, it gives me the following error:

🌎 🠊 [POST] https://dev.azure.com/EnvisionTechnologyPartners/WebIZ/_apis/git/repositories/WebIZ.Graph/pullrequests
🌎 🠈 [500] Internal Server Error
{"$id":"1","innerException":null,"message":"TF400898: An Internal Error Occurred. Activity Id: b7ecf655-43d8-42bc-bf5b-e093cf56dce6.","typeName":"Microsoft.Data.SqlClient.SqlException, Microsoft.Data.SqlClient","typeKey":"SqlException","errorCode":0,"eventId":0}
##[error]Failed to create pull request: Error: Request to 'https://dev.azure.com/EnvisionTechnologyPartners/WebIZ/_apis/git/repositories/WebIZ.Graph/pullrequests' failed: 500 Internal Server Error
Error: Request to 'https://dev.azure.com/EnvisionTechnologyPartners/WebIZ/_apis/git/repositories/WebIZ.Graph/pullrequests' failed: 500 Internal Server Error
    at AzureDevOpsWebApiClient.restApiRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/azure-devops/AzureDevOpsWebApiClient.js:521:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async AzureDevOpsWebApiClient.restApiPost (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/azure-devops/AzureDevOpsWebApiClient.js:498:16)
    at async AzureDevOpsWebApiClient.createPullRequest (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/azure-devops/AzureDevOpsWebApiClient.js:188:33)
    at async DependabotOutputProcessor.process (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/dependabot-cli/DependabotOutputProcessor.js:67:42)
    at async DependabotCli.update (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/utils/dependabot-cli/DependabotCli.js:113:51)
    at async run (/home/vsts/work/_tasks/dependabot_d98b873d-cf18-41eb-8ff5-234f14697896/2.36.1003/index.js:75:57)

I am able to see that the branches get created successfully however the PRs fail to get created.  I've reached out to MSFT and they've asked me to contact Tingle instead since they believe the error is happening when the request is coming from Dependabot.

**Categorization**
- [ ] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**Repository**
[URL: e.g. https://dev.azure.com/tingle/dependabot/_git/repro-684](https://dev.azure.com/EnvisionTechnologyPartners/WebIZ/_git/WebIZ.Graph?path=%2F&version=GBfeatures%2Fmxiong%2F111908_dependabot&_a=contents)

I'm more than happy to do a screen share upon request.

**To Reproduce**
1.  Run the pipeline

**Expected behavior**
I expect dependabot to successfully run and create the PRs for review.  At the moment, it is only creating the branches and then failing on a 500 error as described above.

**Logs and screenshots**
[If applicable, include relevant logs or screenshots to help explain your problem.
See [extension troubleshooting](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/extension.md#troubleshooting-issues) for more on how to collect additional diagnostic logs.
]
https://app.screencast.com/H9yNtrJEknYSh
https://app.screencast.com/acJoiTt6DtxRi

**Extension (please complete the following information):**
- Dependabot@2

**Server (please complete the following information):**
N/A

**Additional context**

**Comment by mouaxiong1980** [comment]
Hi,

Is there any updates on this?


Moua Xiong
________________________________

**Comment by rhyskoedijk** [comment]
> Is there any updates on this?

I haven't had a chance to look in to it further yet, but hope to sometime over this weekend.

I do see that you are using assignees/reviewers. If you haven't already, it might be worth like commenting out these in your `dependabot.yml` file and seeing if that allows the PR to be created; If so, that would certainly narrow down the problem area.

**Comment by rhyskoedijk** [comment]
@mouaxiong1980 my best guess is that there is a duplicated identity in your assignee/reviewers list. I can for example see that "Team 3" is listed as both an assignee and reviewer, this might also be true for the masked email address.

I have submitted a change in https://github.com/tinglesoftware/dependabot-azure-devops/pull/1457 that will filter out duplicated identities. Until this is merged, you can probably work around this issue by manually removing duplicates in your `dependabot.yml` config.

**Comment by mouaxiong1980** [comment]
Thanks for the update.  Simply commenting out the assignee and reviewee seemed to have fixed the issue for now.  From your comment, are you also saying that we shouldn't have the same entity/person assigned as a reviewee and assignee?  I just want to understand this setting.  Thanks.

Moua Xiong
________________________________
