### ISSUE TITLE
Receiving message "update_note_possible" on certain dependencies which breaks the pipeline while running dependabot in ADO

### ISSUE THREAD

**Issue by mouaxiong1980** [tinglesoftware/dependabot-azure-devops#1491]
**Describe the bug**
When running dependabot against our repo in ADO, dependabot is able to create PRs.  However, on certain packages, it is coming back with the error message:

##[Error]Update job error:  update_not_possible {"dependencies":["Microsoft.Extensions.Logging"]}

I've attached a screenshot.

**Categorization**
- [ ] This is not a permissions issue (Seek help at https://github.com/tinglesoftware/dependabot-azure-devops/discussions/1245)

**Repository**
URL: e.g. https://dev.azure.com/tingle/dependabot/_git/repro-684
[<!-- If credentials are required, send them to support@tingle.software --https://dev.azure.com/EnvisionTechnologyPartners/WebIZ/_git/WebIZ.Common

**To Reproduce**
1. Simply running the pipeline causes the error when dependabot is running

**Expected behavior**
PRs are created for each group specified and as necessary.

**Logs and screenshots**
If applicable, include relevant logs or screenshots to help explain your problem.
[See [extension troubleshooting](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/extension.md#troubleshooting-issues) for more on how to collect additional diagnostic logs.]

https://app.screencast.com/TlNIh6DMI6tzT

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version 

**Server (please complete the following information):**
 - Region:  Not sure
 - Version 

**Additional context**

**Comment by rhyskoedijk** [comment]
@mouaxiong1980 this is a known issue in dependabot-core for the NuGet ecosystem. Unfortunately, there is nothing that can be done in the scope of this project to fix it. 

See: https://github.com/dependabot/dependabot-core/issues/10834

Feel free to upvote and comment on the above issue to give it more attention and visibility with the dependabot-core team.
