### ISSUE TITLE
Error: Can't submit to open pull requests

### ISSUE THREAD

**Issue by sucodlaranja** [tinglesoftware/dependabot-azure-devops#1512]
**Describe the bug**
The dependabot can actually find the packages and see the new versions but when trying to submit, it returns an object with information about the commit but does not actually create the pull requests. Ive added the permissions to create pull requests but even with the permissions, the same thing happens.
It does not return an error or the pull request limit gets reached, it just keeps on running and doing the same things

**Dependabot config**
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
```

**Pipeline dependabot**

trigger: none 

schedules:
  - cron: "0 2 * * *"
    always: true
    branches:
      include:
        - main
    batch: true
    displayName: Daily

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: dependabot@2
    inputs:
      azureDevOpsServiceConnection: "Dependabot_Azure"
      gitHubConnection: "github.com_sucodlaranja"

**Logs and screenshots**
Updating @angular/core from 17.3.12 to 18.2.13
updater | 2024/12/10 17:35:44 INFO <job_update_0_npm_and_yarn_all> Submitting @angular/core pull request for creation
`
{"data":{"base-commit-sha":"2a07a31a79e707f194255abd079724aacc476d98","dependencies":[{"name":"@angular/core","previous-requirements":[{"file":"package.json","groups":["dependencies"],"requirement":"^17.1.0","source":{"type":"registry","url":"[https://registry.npmjs.org"}}],"previous-version":"17.3.12","requirements":[{"file":"package.json","groups":["dependencies"],"requirement":"^18.2.13","source":{"type":"registry","url":"https://registry.npmjs.org"}}],"version":"18.2.13","directory":"/"}],"updated-dependency-files":[{"content":"{\n](https://registry.npmjs.org"}}],"previous-version":"17.3.12","requirements":[{"file":"package.json","groups":["dependencies"],"requirement":"%5E18.2.13","source":{"type":"registry","url":"https//registry.npmjs.org%22%7D%7D],%22version%22:%2218.2.13%22,%22directory%22:%22/%22%7D],%22updated-dependency-files%22:[%7B%22content%22:%22%7B/n)  \"name\": \"picdental\",\n  \"version\": \"0.0.0\",\n  \"scripts\": {\n    \"ng\": \"ng\",\n    \"start\": \"ng serve\",\n    \"build\": \"ng build\",\n    \"watch\": \"ng build --watch --configuration development\",\n    \"test\": \"ng test\",\n    \"lint\": \"ng lint\"\n  },\n  \"private\": true,\n  \"dependencies\": {\n    \"@angular/animations\": \"^17.1.0\",\n    \"@angular/common\": \"^17.1.0\",\n    \"@angular/compiler\": \"^17.1.0\",\n    \"@angular/core\": \"^18.2.13\"...
n-utils\": \"^7.25.9\"\n      },\n      \"engines\": {\n        \"node\": \"\u003e=6.9.0\"\n      },\n      \"peerDependencies\": {\n        \"@babel/core\": \"^7.0.0\"\n      }\n    },\n    \"node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining\": {\n      \"version\": \"7.25.9\",\n      \"resolved\": \"[https://registry.npmjs.org/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining/-/plugin-bugfix-v8-spread-parameters-in-optional-chaining-7.25.9.tgz\",\n](https://registry.npmjs.org/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining/-/plugin-bugfix-v8-spread-parameters-in-optional-chaining-7.25.9.tgz/%22,/n)      \"integrity\": \"sha512-6xWgLZTJXwilVjlnV7ospI3xi+sl8lN8rXXbBD6vYn3UYDlGsag8wrZkKcSI8G6KgqKP7vNFaDgeDnfAABq61g==\",\n      \"dev\": true,\n      \"dependencies\": {\n        \"@babel/helper-plugin-utils\": \"^7.25.9\",\n        \"@babel/helper-skip-transparent-expression-wrappers\": \"^7.25.9\",\n        \"@babel/plugin-transform-optional-chaining\": \"^7.25.9\"\n      },\n      \"engines\": {\n        \"node\": \"\u003e=6.9.0\"\n      },\n      \"peerDependencies\": {\n        \"@babel/core\": \"^7.13.0\"\n      }\n    ...
],\n      \"engines\": {\n        \"node\": \"\u003e=12\"\n      }\n    },\n    \"node_modules/@esbuild/linux-ppc64\": {\n      \"version\": \"0.20.1\",\n      \"resolved\": \"[https://registry.npmjs.org/@esbuild/linux-ppc64/-/linux-ppc64-0.20.1.tgz\",\n](https://registry.npmjs.org/@esbuild/linux-ppc64/-/linux-ppc64-0.20.1.tgz/%22,/n)      \"integrity\": \"sha512-b+yuD1IUeL+Y93PmFZDZFIElwbmFfIKLKlYI8M6tRyzE6u7oEP7onGk0vZRh8wfVGC2dZoy0EqX1V8qok4qHaw==\",\n      \"cpu\": [\n        \"ppc64\"\n      ],\n      \"dev\": true,\n      \"optional\": true,\n      \"os\": [\n        \"linux\"\n      ],\n      \"engines\": {\n        \"node\": \"\u003e=12\"\n      }\n    },\n    \"node_modules/@esbuild/linux-riscv64\": {\n      \"version\": \"0.20.1\",\n      \"resolved\": \"[https://registry.npmjs.org/@esbuild/linux-riscv64/-/linux-riscv64-0.20.1.tgz\",\n](https://registry.npmjs.org/@esbuild/linux-riscv64/-/linux-riscv64-0.20.1.tgz/%22,/n)      \"integrity\": \"sha512-wpDlpE0oRKZwX+GfomcALcouqjjV8MIX8DyTrxfyCfXxoKQSDm45CZr9fanJ4F6ckD4yDEPT98SrjvLwIqUCgg==\",\n      \"cpu\": [\n        \"riscv64\"\n      ],\n      \"dev\": true,\n      \"optional\": true,\n      \"os\": [\n        \"lin...
t/visitor-keys\": \"8.17.0\",\n        \"graphemer\": \"^1.4.0\",\n        \"ignore\": \"^5.3.1\",\n        \"natural-compare\": \"^1.4.0\",\n        \"ts-api-utils\": \"^1.3.0\"\n      },\n      \"engines\": {\n        \"node\": \"^18.18.0 || ^20.9.0 || \u003e=21.1.0\"\n      },\n      \"funding\": {\n        \"type\": \"opencollective\",\n        \"url\": \"[https://opencollective.com/typescript-eslint\"\n](https://opencollective.com/typescript-eslint/%22/n)      },\n      \"peerDependencies\": {\n        \"@typescript-eslint/parser\": \"^8.0.0 || ^8.0.0-alpha.0\",\n        \"eslint\": \"^8.57.0 || ^9.0.0\"\n      },\n      \"peerDependenciesMeta\": {\n        \"typescript\": {\n          \"optional\": true\n        }\n      }\n    },\n    \"node_modules/@typescript-eslint/parser\": {\n      \"version\": \"8.17.0\",\n      \"resolved\": \"[https://registry.npmjs.org/@typescript-eslint/parser/-/parser-8.17.0.tgz\",\n](https://registry.npmjs.org/@typescript-eslint/parser/-/parser-8.17.0.tgz/%22,/n)      \"integrity\": \"sha512-Drp39TXuUlD49F7ilHHCG7TTg8IkA+hxCuULdmzWYICxGXvDXmDmWEjJYZQYgf6l/TFfYNE167m7isnc3xlIEg==\",\n      \"dev\": true,\n   ...
"dependencies\": {\n        \"ajv\": \"^8.0.0\"\n      },\n      \"peerDependencies\": {\n        \"ajv\": \"^8.0.0\"\n      },\n      \"peerDependenciesMeta\": {\n        \"ajv\": {\n          \"optional\": true\n        }\n      }\n    },\n    \"node_modules/ajv-keywords\": {\n      \"version\": \"5.1.0\",\n      \"resolved\": \"[https://registry.npmjs.org/ajv-keywords/-/ajv-keywords-5.1.0.tgz\",\n](https://registry.npmjs.org/ajv-keywords/-/ajv-keywords-5.1.0.tgz/%22,/n)      \"integrity\": \"sha512-YCS/JNFAUyr5vAuhk1DWm1CBxRHW9LbJ2ozWeemrIqpbsqKjHVxYPyi5GC0rjZIT5JxJ3virVTS8wk4i/Z+krw==\",\n      \"dev\": true,\n      \"dependencies\": {\n        \"fast-deep-equal\": \"^3.1.3\"\n      },\n      \"peerDependencies\": {\n        \"ajv\": \"^8.8.2\"\n      }\n    },\n    \"node_modules/angular-eslint\": {\n      \"version\": \"19.0.1\",\n      \"resolved\": \"[https://registry.npmjs.org/angular-eslint/-/angular-eslint-19.0.1.tgz\",\n](https://registry.npmjs.org/angular-eslint/-/angular-eslint-19.0.1.tgz/%22,/n)      \"integrity\": \"sha512-sBup7/9I8+/xboKJYR2LZ3TU4qFgeYDkPM5cmLSxk/5tjvihG63684sktys2Uofq3+WmBjHFsc9WAd3VSApZ+Q==\",\n      \"dev\": true,\n      \"d...
: \"[https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz\",\n](https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz/%22,/n)      \"integrity\": \"sha512-WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==\",\n      \"dev\": true\n    },\n    \"node_modules/electron-to-chromium\": {\n      \"version\": \"1.5.47\",\n      \"resolved\": \"[https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.5.47.tgz\",\n](https://registry.npmjs.org/electron-to-chromium/-/electron-to-chromium-1.5.47.tgz/%22,/n)      \"integrity\": \"sha512-zS5Yer0MOYw4rtK2iq43cJagHZ8sXN0jDHDKzB+86gSBSAI4v07S97mcq+Gs2vclAxSh1j7vOAHxSVgduiiuVQ==\",\n      \"dev\": true\n    },\n    \"node_modules/emoji-regex\": {\n      \"version\": \"8.0.0\",\n      \"resolved\": \"[https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz\",\n](https://registry.npmjs.org/emoji-regex/-/emoji-regex-8.0.0.tgz/%22,/n)      \"integrity\": \"sha512-MSjYzcWNOA0ewAHpz0MxpYFvwg6yjy1NG3xteoqz644VCo/RPgnr1/GGt+ic3iJTzQ8Eu3TdM14SawnVUmGE6A==\",\n      \"dev\": true\n    },\n    \"node_modules/emojis-list\": {\n      \"version\": \"3.0.0\",\n      \"resolved\": \"[https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz\",\n](https://registry.npmjs.org/emojis-list/-/emojis-list-3.0.0.tgz/%22,/n)   ...
pansion-2.0.1.tgz\",\n      \"integrity\": \"sha512-XnAIvQ8eM+kC6aULx6wuQiwVsnzsi9d3WxzV3FpWTGA19F621kwdbsAcFKXgKUHZWsy+mY6iL1sHTxWEFCytDA==\",\n      \"dev\": true,\n      \"dependencies\": {\n        \"balanced-match\": \"^1.0.0\"\n      }\n    },\n    \"node_modules/ignore-walk/node_modules/minimatch\": {\n      \"version\": \"9.0.5\",\n      \"resolved\": \"[https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz\",\n](https://registry.npmjs.org/minimatch/-/minimatch-9.0.5.tgz/%22,/n)      \"integrity\": \"sha512-G6T0ZX48xgozx7587koeX9Ys2NYy6Gmv//P89sEte9V9whIapMNF4idKxnW2QtCcLiTWlb/wfCabAtAFWhhBow==\",\n      \"dev\": true,\n      \"dependencies\": {\n        \"brace-expansion\": \"^2.0.1\"\n      },\n      \"engines\": {\n        \"node\": \"\u003e=16 || 14 \u003e=14.17\"\n      },\n      \"funding\": {\n        \"url\": \"[https://github.com/sponsors/isaacs\"\n](https://github.com/sponsors/isaacs/%22/n)      }\n    },\n    \"node_modules/image-size\": {\n      \"version\": \"0.5.5\",\n      \"resolved\": \"[https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz\",\n](https://registry.npmjs.org/image-size/-/image-size-0.5.5.tgz/%22,/n)      \"integrity\": \"sha512-6TDAlDPZxU...
sion\": \"17.0.1\",\n      \"resolved\": \"[https://registry.npmjs.org/ngx-cookie-service/-/ngx-cookie-service-17.0.1.tgz\",\n](https://registry.npmjs.org/ngx-cookie-service/-/ngx-cookie-service-17.0.1.tgz/%22,/n)      \"integrity\": \"sha512-3/5GqMz83VH4VJWgxxv/rGjjIZRZqlp7kNrzisgkxccHsgBe3DMOr/zQyeKZPu7vEqwqyR58hKzegPwAm1Pr3Q==\",\n      \"dependencies\": {\n        \"tslib\": \"^2.6.2\"\n      },\n      \"peerDependencies\": {\n        \"@angular/common\": \"^17.0.0\",\n        \"@angular/core\": \"^17.0.0\"\n      }\n    },\n    \"node_modules/ngx-toastr\": {\n      \"version\": \"19.0.0\",\n      \"resolved\": \"[https://registry.npmjs.org/ngx-toastr/-/ngx-toastr-19.0.0.tgz\",\n](https://registry.npmjs.org/ngx-toastr/-/ngx-toastr-19.0.0.tgz/%22,/n)      \"integrity\": \"sha512-6pTnktwwWD+kx342wuMOWB4+bkyX9221pAgGz3SHOJH0/MI9erLucS8PeeJDFwbUYyh75nQ6AzVtolgHxi52dQ==\",\n      \"dependencies\": {\n        \"tslib\": \"^2.3.0\"\n      },\n      \"peerDependencies\": {\n        \"@angular/common\": \"\u003e=16.0.0-0\",\n        \"@angular/core\": \"\u003e=16.0.0-0\",\n        \"@angular/platform-browser\": \"\u003e=16.0.0-0\"\n      }\n    },\n    \"node_modules/nic...
\"integrity\": \"sha512-q1b3N5QkRUWUl7iyylaaj3kOpIT0N2i9MqIEQXP73GVsN9cw3fdx8X63cEmWhJGi2PPCF23Ijp7ktmd39rawIA==\",\n      \"dev\": true\n    },\n    \"node_modules/rimraf\": {\n      \"version\": \"3.0.2\",\n      \"resolved\": \"[https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz\",\n](https://registry.npmjs.org/rimraf/-/rimraf-3.0.2.tgz/%22,/n)      \"integrity\": \"sha512-JZkJMZkAGFFPP2YqXZXPbMlMBgsxzE8ILs4lMIX/2o0L9UBw9O/Y3o6wFw/i9YLapcUJWwqbi3kdxIPdC62TIA==\",\n      \"deprecated\": \"Rimraf versions prior to v4 are no longer supported\",\n      \"dev\": true,\n      \"dependencies\": {\n        \"glob\": \"^7.1.3\"\n      },\n      \"bin\": {\n        \"rimraf\": \"bin.js\"\n      },\n      \"funding\": {\n        \"url\": \"[https://github.com/sponsors/isaacs\"\n](https://github.com/sponsors/isaacs/%22/n)      }\n    },\n    \"node_modules/rollup\": {\n      \"version\": \"4.24.2\",\n      \"resolved\": \"[https://registry.npmjs.org/rollup/-/rollup-4.24.2.tgz\",\n](https://registry.npmjs.org/rollup/-/rollup-4.24.2.tgz/%22,/n)      \"integrity\": \"sha512-do/DFGq5g6rdDhdpPq5qb2ecoczeK6y+2UAjdJ5trjQJj5f1AiVdLRWRc9A9/fFukfvJRgM0UXzxBIYMovm5ww==\",\n      \"dev\": true,\
}\n    },\n    \"node_modules/vite\": {\n      \"version\": \"5.1.8\",\n      \"resolved\": \"[https://registry.npmjs.org/vite/-/vite-5.1.8.tgz\",\n](https://registry.npmjs.org/vite/-/vite-5.1.8.tgz/%22,/n)      \"integrity\": \"sha512-mB8ToUuSmzODSpENgvpFk2fTiU/YQ1tmcVJJ4WZbq4fPdGJkFNVcmVL5k7iDug6xzWjjuGDKAuSievIsD6H7Xw==\",\n      \"dev\": true,\n      \"dependencies\": {\n        \"esbuild\": \"^0.19.3\",\n        \"postcss\": \"^8.4.35\",\n        \"rollup\": \"^4.2.0\"\n      },\n      \"bin\": {\n        \"vite\": \"bin/vite.js\"\n      },\n      \"engines\": {\n        \"node\": \"^18.0.0 || \u003e=20.0.0\"\n      },\n      \"funding\": {\n        \"url\": \"[https://github.com/vitejs/vite?sponsor=1\"\n](https://github.com/vitejs/vite?sponsor=1\%22\n)      },\n      \"optionalDependencies\": {\n        \"fsevents\": \"~2.3.3\"\n      },\n      \"peerDependencies\": {\n        \"@types/node\": \"^18.0.0 || \u003e=20.0.0\",\n        \"less\": \"*\",\n        \"lightningcss\": \"^1.21.0\",\n        \"sass\": \"*\",\n        \"stylus\": \"*\",\n        \"sugarss\": \"*\",\n        \"terser\": \"^5.4.0\"\n      },
`

**Comment by rhyskoedijk** [comment]
@sucodlaranja thanks for the report. Looks like you might have solved the issue already? If so, are you able to comment on how you fixed it for future users that might find the same problem. If there is something that can be done to reduce the likelihood of it happening again, that is also good to know. Thanks
