### ISSUE TITLE
targetBranch does not work

### ISSUE THREAD

**Issue by dehlers-cts** [tinglesoftware/dependabot-azure-devops#1513]
**Describe the bug**
The targetBranch does not work. See example below

  - task: dependabot@2
            inputs:
              targetBranch: "dev"
              openPullRequestsLimit: 10
            displayName: 'Run Dependabot'

**Categorization**
- Branching issue

**To Reproduce**
1. Run the pipeline
2. No errors are reported and the target branch goes to main.

**Expected behavior**
I expect the targetBranch to create a PR that will be ready to merge to the dev branch. It is always created with the target branch to main.

**Logs and screenshots**
No errors are reported. It should work but ignores the option.

**Extension (please complete the following information):**
 - Host: [Azure DevOps]
 - Version [1.39.0.1099]

**Comment by rhyskoedijk** [comment]
@dehlers-cts the target branch and pull request limits should be specified in your [dependabot,yml configuration file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file), not the pipeline. The below config should do what you are asking.

In your pipeline
```yaml
- task: dependabot@2
  displayName: 'Run Dependabot'
```

In your `.azuredevops\dependabot.yml`
```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    target-branch: "dev"
    open-pull-requests-limit: 10
```

**Comment by dehlers-cts** [comment]
It is working now. I appreciate your help!!!
