### ISSUE TITLE
Dependabot is not pulling the prerelease version from Azure artifacts

### ISSUE THREAD

**Issue by gunjangmail** [tinglesoftware/dependabot-azure-devops#152]
We wanted to include the pre release versions as well while checking the increase version while comparing the nugget packages, but it seems it's skipping the latest pre release version which has *-dev as suffix. Here is an example:
Checking if somename.Runtime.Core 0.20.5.10957-dev needs updating
Requirements to unlock own
Updating somename.Runtime.Core from 0.20.5.10957-dev to 21.2.0.335
Submitting somename.Runtime.Core pull request for creation. Done (PR #2501).
It's taking by default 21.2.0.335, where as in my Azure Artifacts, I have the latest version as somename.Runtime.Core 21.3.11811-dev
Is there any way so that dependabot can look and create PRs for prerelease versions as well?
FYI, I am using dependency-type = all.

**Comment by mburumaxwell** [comment]
Hi @gunjangmail ,

dependabot can only update from a pre-release version to a release version. For NuGet, Semanic Versioning is used to determine the changes.
https://docs.microsoft.com/en-us/nuget/concepts/package-versioning
