### ISSUE TITLE
Azure DevOps extension - unsupported package manager npm

### ISSUE THREAD

**Issue by dome4** [tinglesoftware/dependabot-azure-devops#17]
I receive the following error code when trying to execute the Dependabot task in an Azure DevOps build pipeline. The pipeline uses ubuntu-18.04 as a client and Azure DevOps Personal Access Token should be set correctly. 

![image](https://user-images.githubusercontent.com/23152669/102120368-baf03480-3e42-11eb-8991-fdd8fc8035ca.png)

I'm not really into azure pipeline tasks and it would be therefore nice if you could have a look on it :)

**Comment by mburumaxwell** [comment]
@dome4 this is fixed in https://github.com/tinglesoftware/dependabot-azure-devops/commit/447f95a073a0a2ca7419fe0491955c1dead408ab, 3 days ago. A new version of the docker image and Azure DevOps extension should be available soon. I'll update you once it is ready.

**Comment by mburumaxwell** [comment]
@dome4 this has been released kindly trigger your pipeline
