### ISSUE TITLE
Authenticate on private composer registry

### ISSUE THREAD

**Issue by pimjansen** [tinglesoftware/dependabot-azure-devops#174]
Hey,

Im trying to run Dependabot which has a reference to our private registry. I the docs i see that there is an env available but this is not used for auth here `DEPENDABOT_EXTRA_CREDENTIALS`.

The private registry however authenticates via SSH so is there a way to set the SSH key inside the container while running Dependabot?

**Comment by mburumaxwell** [comment]
@pimjansen this an advanced scenario which requires passing the SSH key(s) to the docker container. After some random search, I found [an idea on SO](https://stackoverflow.com/a/18138352).

This seems like a command that can be run in ruby based on the availability of the SSH file contents in an ENV variable which would unfortunately only work for a single SSH file.

Without much composer knowledge, I cannot help test this functionality end to end. I suggest using the password authentication approach.

**Comment by pimjansen** [comment]
@mburumaxwell well i guess it would be good that the base image of the integration has an option to pass a ssh key maybe? If you could set it as env var it is actually done.

I now indeed need to provide a custom docker container the is actually just a wrapper that does this

**Comment by mburumaxwell** [comment]
@pimjansen if you already have something working, why not submit a PR then we can work from there?

**Comment by pimjansen** [comment]
> @pimjansen if you already have something working, why not submit a PR then we can work from there?

Havent got it working yet but will let you guys know once i have.

Was also curious if im missing somewhere here so

**Comment by mburumaxwell** [comment]
I can't see anything you're missing yet, @pimjansen

**Comment by pimjansen** [comment]
@mburumaxwell i managed to solve the issue by running the command with below extra arguments:

```
    -e SSH_AUTH_SOCK=/ssh-agent \
    --volume $SSH_AUTH_SOCK:/ssh-agent \
```

However, there is currrently no way to provide it in the azure task is it? I can add some extra env vars but not for a volume. I can run the container directly in an script task though but that does not hold my preference tbh.

**Comment by mburumaxwell** [comment]
@pimjansen 
This can be solved by adding a Boolean input to the Azure DevOps task which when true, the two arguments are added to the tool arguments.

**Comment by pimjansen** [comment]
Agree however im not that good at ruby and such. I believe by doing so everyone has full control over both the ssh implementation as the actual dependabot implementation(by loading the direct yml)
