### ISSUE TITLE
Question: Security, access to repository, only x branch?

### ISSUE THREAD

**Issue by XzaR90** [tinglesoftware/dependabot-azure-devops#175]
Is it possible to only give access to a certain branch instead of the whole repository?
I think that is good for the security as anything could happen if given access to the full source code.

Is that possible by creating a new account with a PAS token that only have access to one branch?

**Comment by mburumaxwell** [comment]
Hi @XzaR90 ,

Dependabot works by creating a PR in your repository. Usually, this is against the default branch (main/master). If you wish to restrict access to that branch, you can have it create pull requests against another branch by specifying the [`target-branch`](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#target-branch) option in the config file. However, dependabot still needs permissions to manage pull requests in the repository.
