### ISSUE TITLE
Whitespaces in organization, project & repo names not allowed

### ISSUE THREAD

**Issue by dome4** [tinglesoftware/dependabot-azure-devops#18]
We have a whitespace in our project name: `Test App`. Thus the uri resolves to `https://dev.azure.com/test-org/Test App/_apis/git/repositories/Test App/stats/branches?name=dev` which is considered as invalid uri by the ruby RFC3986_Parser. Our uri doesn't match the used regex: [see code](https://github.com/ruby/ruby/blob/5d8f227d0edd3c542fcac465eb82005a5f852d34/lib/uri/rfc3986_parser.rb#L6).

![image](https://user-images.githubusercontent.com/23152669/102325230-30fbb500-3f83-11eb-9055-4ec0f05aec2d.png)

For now it's sufficient to not use whitespaces in project and organization names but it would be nice if dependapot could escape whitespaces before passing the uri to the ruby parser. Moreover a comment in the docu would be helpful.

My ruby skills are limited but I think it already works if `repo_name` ([code](https://github.com/tinglesoftware/dependabot-azure-devops/blob/bcc530a03bb3754e8a121236237295623bb787a7/src/script/update-script.rb#L12)) is encoded e.g. with `repo_name= URI.encode("#{organization}/#{project}/_git/#{repository}")`.

**Comment by mburumaxwell** [comment]
Resolved in https://github.com/tinglesoftware/dependabot-azure-devops/commit/9dec0f90d9b2a7f1c00aa09f5fb1b0c12e973f85

**Comment by mburumaxwell** [comment]
Released (https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.1.4)
