### ISSUE TITLE
Need for Github PAT Token

### ISSUE THREAD

**Issue by vs4vijay** [tinglesoftware/dependabot-azure-devops#192]
Hi,

I wanted to understand whats the need of specifying github personal access token while setting up pipeline in Azure? As per my understanding, based on package manager as input, dependabot should try to get latest info. from package manager's artifact repository. e.g. In package manager is maven, then it should look for latest versions in Maven Centrals; if package manager is npm, then it should fetch info. from npmjs.org?   Isn't it so?

If dependabot always gets the latest version info. from github, then it might be possible that some of the package might not be hosted on github, they can be part of gitlab, bitbucket. Then why we're asking for Github PAT token only?

**Comment by mburumaxwell** [comment]
@vs4vijay the answer given by @MO2k4 is absolutely correct. However, that parameter is optional if you make very few requests from your IP or your IP has been allowed by GitHub for unlimited API requests.

I will now close this.
