### ISSUE TITLE
Trouble using Bitbucket repo from azure pipeline

### ISSUE THREAD

**Issue by MidasLamb** [tinglesoftware/dependabot-azure-devops#222]
Our version control (currently) is in BitBucket, currently I've been unsuccesful in getting this to work.
Almost all attempts end in: `/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/file_fetchers/base.rb:471:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)`

Is it just not possible to use this with bitbucket repo's? 
If it is, could you please help me out a bit, or help me find out which parameters are important?
It it is not, and you're open to extending this project with support for it, would you be interested in providing a small amount of guidance such that I'd be able to open a PR for this?

**Comment by mburumaxwell** [comment]
Hi @MidasLamb at this time, this only supports repositories in hosted on Azure DevOps otherwise referred to as Azure Repos.
