### ISSUE TITLE
Support Basic Auth

### ISSUE THREAD

**Issue by WebsiteDeveloper** [tinglesoftware/dependabot-azure-devops#234]
We are currently using an On Premise solution with due to some issues can only use basic auth.
Could this be supported?

**Comment by MathieuDR** [comment]
I would also enjoy having an basic authentication option as the following isn't working

`DEPENDABOT_EXTRA_CREDENTIALS: '[{"type":"nuget","password":"$(JFROG-PASS)","username":"$(JFROG-USER)","registry":"$(JFROG-URL)"}]'`

**Comment by mburumaxwell** [comment]
Have a look at this https://github.com/tinglesoftware/dependabot-azure-devops/issues/50#issuecomment-825780044
Is it a solution that would work
