### ISSUE TITLE
BUG: open-pull-requests-limit: 0 fails

### ISSUE THREAD

**Issue by vebjornmalmin** [tinglesoftware/dependabot-azure-devops#242]
Hey ! 

When limiting numbers of PR to `0`, it jumps to back `5`.   This happens  both for dependabot.yaml  or task-inputs. 

Could this  be due to `0` evaluating  to `false` ?

**Comment by mburumaxwell** [comment]
@vebjornmalmin yes you are correct. This is done this way because there was not particular reason to not create PRs. Could you explain why you need to have the limit set to `0`?
