### ISSUE TITLE
Is there a way to raise pull request for any high vulnerabilities ? otherwise there are so many pull requests in code base

### ISSUE THREAD

**Issue by ashu16815** [tinglesoftware/dependabot-azure-devops#249]
we have a legacy code base and we want to priorities the clean up of high vulnerabilities one by one but with dependabot its just raising pull request for all the outdated version . Is there a way to identify if we can use dependabot to raise pull request for  dependencies having high vulnerabilities only or other way to tag those pull request with high vulnerabilities

**Comment by mburumaxwell** [comment]
This is not yet supported in the extension.

Related to #161
