### ISSUE TITLE
[Help needed] Multiple repos for 'targetRepositoryName' parameter?

### ISSUE THREAD

**Issue by JoeriKlomp** [tinglesoftware/dependabot-azure-devops#266]
Hello, I was wondering if it's possible to target multiple repos with one pipeline and how that's achieved with the 'targetRepositoryName' parameter. The documentation says the following: "Supplying this value allows creation of a single pipeline that runs Dependablot against multiple repositories." But it doesn't say how that's done exactly.

**Comment by jackmtrayport** [comment]
I haven't; deploying a bunch of infrastructure like that is not something to be done lightly when it requires signoff from infosec people etc. It also seems like quite a bit of overkill to do what is effectively `docker run` in a loop (which tbh is what we might end up doing instead).

**Comment by mburumaxwell** [comment]
Actually, you can create a powershell/bash script that pulls the repositories in the project, checks for the configuration file then runs docker. You can even do it a dotnet console application which might be more readable.

You have lots of options at your disposal I think.

**Comment by mburumaxwell** [comment]
Also, just a heads up. Most of the new features coming soon will require the server component because they need storage of state. While the extension will continue to work for most situations, you may want to look at what the implications are for deploying the server component and plan ahead.
