### ISSUE TITLE
Need help with configuration

### ISSUE THREAD

**Issue by PCarlsson** [tinglesoftware/dependabot-azure-devops#267]
Hello,
I have a couple of questions regarding the configuration of Dependabot in Azure DevOps since it seems like I have missed something.

```...
Digest: sha256:a6517bb26d0342ccbce7a2ea0121ba7e8c2fc74c23667c1ebc1033936ed55868
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.5
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:239:in 'get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:95:in 'fetch_repo_contents_treeroot'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/clients/azure.rb:71:in 'fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:309:in '_azure_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:208:in '_fetch_repo_contents_fully_specified'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:179:in '_fetch_repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:163:in 'repo_contents'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.180.1/lib/dependabot/nuget/file_fetcher.rb:184:in 'csproj_file'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.180.1/lib/dependabot/nuget/file_fetcher.rb:55:in 'project_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.180.1/lib/dependabot/nuget/file_fetcher.rb:28:in 'fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.180.1/lib/dependabot/file_fetchers/base.rb:65:in 'files'
	from ./update-script.rb:245:in '<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
...
```

- Do we have to add/install some other tasks to the pipeline except the Dependabot task?
- We have a C# solution with several projects and one packages.config for each project. Is it enough to specify the top level folder or do we have to specify each folder/file?
- If we want to check both NuGet and npm do we have to have two different tasks targetting NuGet and npm separately?
- Is it possible to activate a debug mode for Dependabot with more verbose log?

Let me know if I need to provide additional information.

/Peter

**Comment by mburumaxwell** [comment]
> * Do we have to add/install some other tasks to the pipeline except the Dependabot task?

No you do not.


> * We have a C# solution with several projects and one packages.config for each project. Is it enough to specify the top level folder or do we have to specify each folder/file?

I have not used packages.config in years. When working with the newer csproj format (is it still new?), dependabot will update all projects in the repository if you specify `directory: '/'`.


> * If we want to check both NuGet and npm do we have to have two different tasks targetting NuGet and npm separately?

Yes. Each ecosystem gets is own task in the pipeline if you are not using the config file. If you are using the config file, you need one task with `useConfigFile: true` input and multiple updates in the config file. For more on the config file see [this description](https://github.com/tinglesoftware/dependabot-azure-devops#using-a-configuration-file)


> * Is it possible to activate a debug mode for Dependabot with more verbose log?

Yes. You can do this by adding `EXCON_DEBUG=1` to the env variables. Add the `extraEnvironmentVariables` inut e.g. `extraEnvironmentVariables: 'EXCON_DEBUG=1'`

**Comment by mburumaxwell** [comment]
To get the `Dependabot::Clients::Azure::NotFound` exception, there should be at least one HTTP call made to Azure. This should be visible with the input `extraEnvironmentVariables: 'EXCON_DEBUG=1'`. This is useful to determine the request, its path, the response code and error information, using which we can tell what the actual issue is. It is possible that it is an authentication issue or dependency directory issue.

Also, you can try a number of combinations of the directory locally on your machine using docker. See how to use docker [here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/src/script/README.md#:~:text=An%20example%2C%20for%20Azure%20DevOps%20Services,mnop%20%5C%0A%20%20%20%20%20%20%20%20%20%20%20tingle/dependabot%2Dazure%2Ddevops%3A0.4.0)

**Comment by PCarlsson** [comment]
Thanks for the response!

Could you please give me more details on how to add ```EXCON_DEBUG=1``` to the Azure DevOps build pipeline?
I added it under pipeline variable, but should it be added somewhere in the Dependabot task?

With values from the pipeline I managed to run Docker locally and get some output. For me it is still not obvious what setting is wrong. But it feels like the path to the source code is wrong.

What should DEPENDABOT_DIRECTORY look like in Azure DevOps and locally (if the git repository is located in C:\Workspace\Git\transpa)?

```
docker run --rm -i -e EXCON_DEBUG=1 -e DEPENDABOT_PACKAGE_MANAGER=nuget -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ORGANIZATION=transpa -e AZURE_PROJECT=transPA -e AZURE_REPOSITORY=transpa -e AZURE_ACCESS_TOKEN=<deleted> -e AZURE_SET_AUTO_COMPLETE=false -e AZURE_MERGE_STRATEGY=2 -e DEPENDABOT_DIRECTORY=/home/vsts/work/1/s -e DEPENDABOT_TARGET_BRANCH=development -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=1 -e AZURE_AUTO_APPROVE_PR=false tingle/dependabot-azure-devops:0.5
```

**Comment by mburumaxwell** [comment]
To set the variable in the pipeline,

```yaml
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    directory: '/'
    extraEnvironmentVariables: 'EXCON_DEBUG=1'
```

The task input named `directory` maps to the env named `DEPENDABOT_DIRECTORY`. The value to set here should be relative to the repository. To get access to the root of your repository use `/` as the value. This **should** work for NuGet. However, you may need to specify a different value depending on the structure; e.g. `/src` if all NuGet related items are under the _src_ folder

When working in Docker you need to specify more items. Here's an example:

```bash
docker run --rm -i -e AZURE_ORGANIZATION=transpa -e AZURE_PROJECT=transPA -e AZURE_REPOSITORY=transpa -e AZURE_ACCESS_TOKEN=<deleted> -e AZURE_SET_AUTO_COMPLETE=false -e DEPENDABOT_PACKAGE_MANAGER=nuget -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_TARGET_BRANCH=development -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=1 -e EXCON_DEBUG=1 tingle/dependabot-azure-devops:0.6
```

For readability:

```bash
docker run --rm -i \
    -e AZURE_ORGANIZATION=transpa \
    -e AZURE_PROJECT=transPA \
    -e AZURE_REPOSITORY=transpa \
    -e AZURE_ACCESS_TOKEN=<deleted> \
    -e AZURE_SET_AUTO_COMPLETE=false \

    -e DEPENDABOT_PACKAGE_MANAGER=nuget \
    -e DEPENDABOT_DIRECTORY=/ \
    -e DEPENDABOT_TARGET_BRANCH=development \
    -e DEPENDABOT_VERSIONING_STRATEGY=auto \
    -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=1 \

    -e EXCON_DEBUG=1 \
    tingle/dependabot-azure-devops:0.6
```

I have omitted some env settings because they have [defaults in he ruby script](https://github.com/tinglesoftware/dependabot-azure-devops/blob/3935425761ecc8b1ba694766198f775f1234948b/src/script/update-script.rb#L21-L57)

**Comment by PCarlsson** [comment]
Could you please provide an example of a complete dependabot.yml file?

**Comment by PCarlsson** [comment]
Here is some more details from the debug log. Hope I did not left out too much. Don't know how it resolved 'C:/Program%20Files/Git' as the path to the repository because that's not correct either locally (C:/Workspace/Git/transpa) or in Azure DevOps (/home/vsts/work/1/s).

```
excon.request
  :host                => "dev.azure.com"
  :method              => :get
  :path                => "/transpa/transPA/_apis/git/repositories/transpa/stats/branches"
  :query               => "name=development"
excon.response
  :status        => 200

excon.request
  :host                => "dev.azure.com"
  :method              => :get
  :path                => "/transpa/transPA/_apis/git/repositories/transpa/items"
  :query               => "path=C:/Program%20Files/Git&versionDescriptor.versionType=commit&versionDescriptor.version=a4db6de08f5f41a28aa562cf9fff3fc5760d8440"
excon.response
  :body          => "{\"$id\":\"1\",\"innerException\":null,\"message\":\"TF401174: The item 'C:/Program Files/Git' could not be found in the repository 'transpa' at the version specified by '<Commit: a4db6de08f5f41a28aa562cf9fff3fc5760d8440 >' (resolved to commit 'a4db6de08f5f41a28aa562cf9fff3fc5760d8440')\",\"typeName\":\"Microsoft.TeamFoundation.Git.Server.GitItemNotFoundException, Microsoft.TeamFoundation.Git.Server\",\"typeKey\":\"GitItemNotFoundException\",\"errorCode\":0,\"eventId\":3000}"
  :status        => 404

/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/clients/azure.rb:239:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/clients/azure.rb:95:in `fetch_repo_contents_treeroot'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/clients/azure.rb:71:in `fetch_repo_contents'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:309:in `_azure_repo_contents'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:208:in `_fetch_repo_contents_fully_specified'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:179:in `_fetch_repo_contents'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:65:in `files'
        from ./update-script.rb:245:in `<main>'
```

**Comment by mburumaxwell** [comment]
@PCarlsson 
Using a `dependabot.yml` file is optional. This repository only supports using it via the extension. It should be located at the root of the repository in a folder named `.azuredevops`.

The file looks the same as the [official one](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file), excluding sections for private registries.

Below is an example of one I use:

```yaml
version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "02:00"
    open-pull-requests-limit: 10
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/website" # Location of package manifests
    schedule:
      interval: "daily"
      time: "10:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "react"
```

**Comment by mburumaxwell** [comment]
> Here is some more details from the debug log. Hope I did not left out too much. Don't know how it resolved 'C:/Program%20Files/Git' as the path to the repository because that's not correct either locally (C:/Workspace/Git/transpa) or in Azure DevOps (/home/vsts/work/1/s).

Could you just leave the path as `/` ?

**Comment by PCarlsson** [comment]
The odd thing is that I already had it set to / with ```DEPENDABOT_DIRECTORY=/```. But perhaps that's not the right settings?
Now I added ```AZURE_VIRTUAL_DIRECTORY=/``` and got the following error. Not a request error this time.

```warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://dev.azure.com:443/C:/Program Files/Git//transpa/transPA/_apis/git/repositories/transpa/stats/branches?name=development" (URI::InvalidURIError)
        from /usr/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
        from /usr/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/excon-0.92.2/lib/excon.rb:121:in `new'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/excon-0.92.2/lib/excon.rb:250:in `get'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/clients/azure.rb:222:in `block in get'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/clients/azure.rb:286:in `retry_connection_failures'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/clients/azure.rb:221:in `get'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/clients/azure.rb:52:in `fetch_commit'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:73:in `commit'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:386:in `_full_specification_for'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:176:in `_fetch_repo_contents'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:163:in `repo_contents'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
        from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:65:in `files'
        from ./update-script.rb:245:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using 'https://dev.azure.com:443/C:/Program Files/Git//' as API endpoint
Fetching nuget dependency files for transpa/transPA/_git/transpa
Targeting 'development' branch under 'C:/Program Files/Git/' directory
Using 'auto' requirements update strategy
```

**Comment by mburumaxwell** [comment]
As per your log, the URI is wrong. The directory needs to be relative to the root of the repository and is not OS specific.

I suggest you try to get the extension working with simpler repositories where you can use the default settings.

**Comment by PCarlsson** [comment]
Thank you for your patience!

It feels like I misunderstand something in the settings.

I get **Targeting 'development' branch under '/' directory**:
```Digest: sha256:f775b523539fe3d438aa020e7be4fa6dd1845bcbe25a4796895cdeb8117b49af
Status: Downloaded newer image for tingle/dependabot-azure-devops:0.5
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.182.0/lib/dependabot/nuget/file_fetcher.rb:42:in `fetch_files': Dependabot::DependencyFileNotFound (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.182.0/lib/dependabot/file_fetchers/base.rb:65:in `files'
	from ./update-script.rb:245:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Fetching nuget dependency files for transpa/transPA/_git/transpa
Targeting 'development' branch under '/' directory
Using 'auto' requirements update strategy
```

I have also tested with **/home/vsts/work/1/s** where I can see the git repository is downloaded.

I thought that the setting **Directory (Set the directory from where Dependabot should check for updates. Examples: / for root, /src for src folder.)** should point to the directory where the git repository was downloaded by the Azure DevOps build pipeline. Or if set to / (root) it would search recursively for the correct folder. But maybe this should point on something else?

And I have not changed anything under the other settings (Auto Approval and Auto Completion of PR's, GitHub authentication, Advanced, Control Options or Output Variables)

**Comment by mburumaxwell** [comment]
@PCarlsson Could you share a sample repository preferably as a public project on Azure DevOps? You can remove anything sensitive.

This might be the only way to know the extract layout we're dealing with hence eventually help you out.

**Comment by PCarlsson** [comment]
I will see what I can set up.
