### ISSUE TITLE
DEPENDABOT_EXTRA_CREDENTIALS for Private Terraform Registries

### ISSUE THREAD

**Issue by apaarshrm39** [tinglesoftware/dependabot-azure-devops#268]
Is there any available documentation for the simple auth JSON syntax to pass private terraform registry creds as 'DEPENDABOT_EXTRA_CREDENTIALS' to the task, or any other way to authenticate against private terraform registries hosted at Terraform cloud.

**Comment by mburumaxwell** [comment]
Same question asked in https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#terraform-registry

I haven't used terraform, but according to the [official docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#terraform-registry), the json would likely be:

```
"[{\"type\": "terraform-registry", \"url\": "you know what goes here\", \"token\": "planet of apes\"}]"
```

Of course remember to change the actual values.

**Comment by apaarshrm39** [comment]
hey @mburumaxwell , I did try that but that doesn't seem to work, also I don't think there's a one to one matching with dependabot-core registry configuration and the EXTRA_CREDENTIALS as , for npm the dependabot doc says: `registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.MY_GITHUB_PERSONAL_TOKEN}}`
But the json is, `{
        "type": "npm_registry",
        "registry": "pkgs.dev.azure.com/<organization>/_packaging/<feed>/npm/registry/",
        "token": "<feed>:<raw-pat-value>"
    }`

**Comment by mburumaxwell** [comment]
@apaarshrm39 
According to the official [code](https://github.com/dependabot/dependabot-core/blob/e8a6a4b7edc31abeae1919e7a51beb9f7655a6d7/terraform/spec/dependabot/terraform/registry_client_spec.rb#L93) I would use:
```
"[{\"type\": \"terraform_registry\", \"host\": \"registry.example.org\", \"token\": \"planet of apes\"}]"
```
