### ISSUE TITLE
Add option to choose docker registry mirror

### ISSUE THREAD

**Issue by PatrickBig** [tinglesoftware/dependabot-azure-devops#276]
Some corporate environments do not allow direct access to docker hub and use their own registry that mirrors docker hub.

Please add the ability to select a Docker Registry service connector as the source to pull the image tingle/dependabot-azure-devops

**Comment by mburumaxwell** [comment]
This is definitely a good idea. Could you put in a PR?

**Comment by PatrickBig** [comment]
Yup.
