### ISSUE TITLE
Not updating to resolve existing PR's conflicts

### ISSUE THREAD

**Issue by davesmits** [tinglesoftware/dependabot-azure-devops#281]
first of all. great work to have dependabot in azure devops.

I have one pipeline with mulitple stages (for each repository a stage) to run dependabot. It works great only when for example Angular updates multiple PRs are created. After completing one the process very often halts because there getting conflicts in package.json (same for nuget). 

I thought dependabot was able to resolve those by just running again?

Conflicts i end up with:

![image](https://user-images.githubusercontent.com/3148438/168577720-9defed2f-71be-42d8-835d-2b9b616764b1.png)

and from the log it seems touching this dependencyl just not updating the existing PR

Updating @angular/core from  to 13.3.8
Submitting @angular/core pull request for creation. Seems PR is already present.

**Comment by mburumaxwell** [comment]
@davesmits the extension/script updates PRs that have `mergeStatus=conflict`. Pull requests in Azure DevOps don't update merge status automatically like on GitHub unless you have auto complete on the PR and all other checks have passed. Hence why this extension has it enabled by default. This can also be triggered manually by using the "restart merge" button/option for the PR.

Please try these options and report back.

**Comment by davesmits** [comment]
@mburumaxwell thanks. I noticed that Azure Devops is mostly requiring user interaction to detect the merge conflict status so was already playing with it a bit. 

The PR was already in 'conflict' status.

**Comment by davesmits** [comment]
@mburumaxwell it just happend me again. Had two pr's and after accepting the first the second became in conflict.

So I did try "restart merge" in the PR to ensure the conflict status is update and then ran my pipeline. See screenshot for output. But the PR didnt got updated

![image](https://user-images.githubusercontent.com/3148438/169979176-ebb58b5f-de0c-4e5e-aa4a-55a99e174e48.png)

**Comment by mburumaxwell** [comment]
@davesmits I see the logs clearly now though I realize there's a log output about the number of commits that is missing that should be added  in a future release for better debugging.

Before we get into that could you confirm the number of commits on the branch for the PR? In short have you added any more cookies besides the one created by dependabot?

**Comment by davesmits** [comment]
@mburumaxwell Not sure what you exactly mean (sorry not native english).

but for the master branch i did merge a PR of myself in between; but triggered the 'restart merge' after merging 11479
![image](https://user-images.githubusercontent.com/3148438/170026012-6ca49f7f-c6cd-462d-b2af-7d1b4864bba4.png)

If you mean committing the to branch dependabot craeted; no i didnt touch those.
This are the updates for the PR mentioned here above

![image](https://user-images.githubusercontent.com/3148438/170026202-ff959089-a2be-41bd-aba1-581bda56459e.png)

**Comment by davesmits** [comment]
I stand corrected. For nuget it works. only npm is not updated

**Comment by mburumaxwell** [comment]
@davesmits do you mean the behavior is erratic?

**Comment by davesmits** [comment]
Yes i think so. For nuget it's resolving conflicts in outstanding pull requests. I would expect same behavior in NPM but prs keep in conflicting state and need to be resolved manually

**Comment by mburumaxwell** [comment]
I am unable to repro this. We are having no issue with NPM and we have quite a number of them. Could you provide a repro for this in a public Azure DevOps project?

**Comment by djmVHB** [comment]
@davesmits were you ever able to find a fix for this? I am facing the same issue. Thanks.
