### ISSUE TITLE
Pull requests not auto-completing in ADO 2019

### ISSUE THREAD

**Issue by PatrickBig** [tinglesoftware/dependabot-azure-devops#288]
The pull request auto-complete feature currently does not work with the dependabot script if using ADO 2019.

**Comment by mburumaxwell** [comment]
@PatrickBig have you done any further investigation? Is there any more information that you can provide?

**Comment by PatrickBig** [comment]
> @PatrickBig have you done any further investigation? Is there any more information that you can provide?

Yes, I have. I actually have a fix ready.

It looks like it's because the current version of this task is using the ADO API v6 wherever it can. ADO 2019 only supports <= v5

https://docs.microsoft.com/en-us/azure/devops/integrate/concepts/rest-api-versioning?view=azure-devops


 Submitting a PR to resolve the issue
