### ISSUE TITLE
Can't Auth with private feed in azure devops

### ISSUE THREAD

**Issue by AlvaroCognodata** [tinglesoftware/dependabot-azure-devops#302]
Hi, last week I managed to get this working even I have a telerik dependency. But since last version was updated it keeps failing no matter what I'm doing. I have tested to ignore the private feed and tried to pass the login and both failed.

For passing extra credentials: 
##[debug]extraEnvironmentVariables=DEPENDABOT_EXTRA_CREDENTIALS=[{"type":"nuget_feed","username":"*****","password":"*****","url":"[https://nuget.telerik.com/nuget"}]

And the result was:
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.192.1/lib/dependabot/nuget/update_checker/repository_finder.rb:119:in `check_repo_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): https://nuget.telerik.com/nuget (Dependabot::PrivateSourceAuthenticationFailure)

And ignoring the dependency:

##[debug]/usr/bin/docker arg: ["-e","DEPENDABOT_IGNORE_CONDITIONS=[{\"dependency-name\":\"Telerik*\"}]"]

the result was the same.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.192.1/lib/dependabot/nuget/update_checker/repository_finder.rb:119:in `check_repo_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): https://nuget.telerik.com/nuget (Dependabot::PrivateSourceAuthenticationFailure)

Whatever I do the result is the following:

Targeting 'default' branch under '/' directory
Using 'auto' requirements update strategy
Parsing dependencies information
Checking if ElmahCore 2.1.1 needs updating
##[debug]Exit code 1 received from tool '/usr/bin/docker'
##[debug]STDIO streams have closed for tool '/usr/bin/docker'
##[debug]task result: Failed

The pipeline is configured as:

```
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    versioningStrategy: 'auto'
  displayName: 'Run Dependabot'
```

What else I could try?

Thanks.

**Comment by mburumaxwell** [comment]
Hi @AlvaroCognodata, could you provide a repro for this in a public Azure DevOps project?

**Comment by AlvaroCognodata** [comment]
Finally I solved this using another plugin.
