### ISSUE TITLE
.NET Framework references not updating correctly

### ISSUE THREAD

**Issue by MEmanuelsson** [tinglesoftware/dependabot-azure-devops#312]
We have a solution with a combination of .NET Framework and .NET 6 projects against which we run a dependabot job once every night in Azure Devops. Everything works fine for the .NET 6 projects (`<PackageReference>` being correctly updated in the .csproj-file) but for our .NET Framework projects it's not working as great. 

The problem being that it's only the reference in `packages.config` that's being updated, not assembly bindings in web.config or references in the .csproj file for instance. So when we get a PR created for our .NET Framework projects we have to manually update these Nuget-references to get the reference updated correctly, also if one Nuget-package is being used by both .NET Framework and .NET 6 we have to do this manual update. 

Just wondering if this is a known limitation with dependabot or something that we're doing wrong on our side?

**Comment by deenairn** [comment]
I'm not the maintainer, but I know when working with dependabot using GitHub, this also happens. So I would suspect it's a limitation with dependabot. You can only really use it as a notification that you need to update your dependencies using the proposed PR as a baseline, rather than just accept it and merge as with PackageReference format.

**Comment by MEmanuelsson** [comment]
Sorry about late reply to this one, just back from vacation :-) 
Seems like this is an issue that also has been discussed here for instance: https://github.com/dependabot/dependabot-core/issues/2218. 
So if it's not possible to get this working for .NET Framework projects, is there a way to tell dependabot to exclude this project from being analyzed and having PRs created? Haven't seen a way to do this but maybe I've missed something?

**Comment by jeffwidman** [comment]
See my latest comment here: https://github.com/dependabot/dependabot-core/issues/2218#issuecomment-1250140828

We don't have a ton of `.net` experience on the core team right now, so if one of you wants to take a crack at fixing it, we're happy to point you in the right direction in the Ruby code and then review the PR.

**Comment by mburumaxwell** [comment]
@MEmanuelsson if this is still an issue, could you offer a public repro?

**Comment by rhyskoedijk** [comment]
I ran in to this issue too, it seems to be an issue in dependabot-core.
I submitted https://github.com/dependabot/dependabot-core/pull/10110 which fixes this issue in my [legacy] .NET Framework projects.
