### ISSUE TITLE
openPullRequestsLimit: 0 - Does it work to get security updates only?

### ISSUE THREAD

**Issue by piejanssens** [tinglesoftware/dependabot-azure-devops#325]
[Should this work for the taks parameter openPullRequestLimit too?
](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates)

**Comment by mburumaxwell** [comment]
@piejanssens security only updates are currently not supported by this extension. Contributions are welcome.
Closing as duplicate of #161
