### ISSUE TITLE
Does it work with the Github repository?

### ISSUE THREAD

**Issue by t0p4** [tinglesoftware/dependabot-azure-devops#326]
I don't know if it can be paired with Azure Devops as a CI and Github as a source repository.

**Comment by mburumaxwell** [comment]
@t0p4 The extension is meant to update Azure DevOps repositories (a.k.a. Azure Repos). If you are using GitHub as your repository, the GitHub hosted version of dependabot will work just fine then you can setup CI/CD pipelines in Azure DevOps Pipelines (a.k.a. Azure Pipelines).

To configure Dependabot on GitHub [read here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates)
To setup CI in Azure Pipelines for your GitHub repository, see [this guide/lab](https://www.azuredevopslabs.com/labs/azuredevops/github-integration/)

Closing this; reopen if need be.
