### ISSUE TITLE
Directory.Packages.props file can't be found

### ISSUE THREAD

**Issue by dgcaron** [tinglesoftware/dependabot-azure-devops#333]
Hi,

we are using the extension in devops and the nuget CentralPackageVersionManagement feature. support for this has been added a while ago by dependabot but the extension is not finding a suitable file to update. it doesn't locate the Directory.Packages.props file in the specified directory, but it definitely is there.    anyone else have this working?

**Comment by dgcaron** [comment]
it doesn't look like it's related to the plugin but more to dependabot. Moving the file into the root of repo fixed the problem.

**Comment by mburumaxwell** [comment]
Acknowledged.
