### ISSUE TITLE
How to get multiple PR's for the same update simultaneously

### ISSUE THREAD

**Issue by KnicKnic** [tinglesoftware/dependabot-azure-devops#334]
The problem that we have is that there are multiple projects/directories (owned by different people) that have the same set of dependencies in the same repository.

1. Dependabot will open up a PR to update the dependency for directory /A
2. Dependabot will continue on to directory /B
    1. It will attempt to create a PR, but will do so under the same name as the one that it did for /A, it will then see the PR already exists and not do anything

I was wondering is it possible to distinguish the PR's per dependabot directory. We are having problems where one owner will let their PR backlog build up and block another directory from getting PR's (who's project may be more sensitive to getting behind).

**Comment by KnicKnic** [comment]
Looking into this, it appears that the easiest way to do this is to alter the branch name that dependabot creates. I created this in dependabot core https://github.com/dependabot/dependabot-core/issues/5571

**Comment by mburumaxwell** [comment]
@KnicKnic you are indeed correct. This is the default behaviour of dependabot and can only be rectified in the core repository. 

One way to solve this is to have a separate update for each directory, dependabot will then create branches with the directory name in them.

```yaml
version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/DirectoryA"
  - package-ecosystem: "nuget"
    directory: "/DirectoryB"
```

Dependabot will create branches with the format `dependabot/{ecosystem}/{directory}/{package-name}-{version}` for example:
- `dependabot/nuget/DirectoryA/Microsoft.Extensions.Caching.StackExchangeRedis-6.0.9`
- `dependabot/nuget/DirectoryB/Microsoft.Extensions.Caching.StackExchangeRedis-6.0.9`

I hope this helps and you can report back if that is the case.

**Comment by mburumaxwell** [comment]
Closing, reopen if need be
