### ISSUE TITLE
Add support for Kubernetes yaml files

### ISSUE THREAD

**Issue by nilekhc** [tinglesoftware/dependabot-azure-devops#346]
Ref: https://github.com/dependabot/dependabot-core/pull/5348

The dependabot core now supports k8s yaml files using `OPTIONS: { "kubernetes_updates": true }` env var with `docker` package manager type.

It would be great to have this support here.

**Comment by nilekhc** [comment]
Is there any luck on this? Is this already implemented? If not are you accepting PRs?

**Comment by mburumaxwell** [comment]
@nilekhc I hadn't gotten around to this one yet. Yes, we are accepting PRs.

**Comment by mburumaxwell** [comment]
@nilekhc , this is rather a simple fix. Doing a PR

**Comment by nilekhc** [comment]
Thanks @mburumaxwell Just looked at the PR. Looks like it'll be enabled by default and the user doesn't have to explicitly provide it, do they?

**Comment by nilekhc** [comment]
default makes sense. I was just confirming... :-)

**Comment by nilekhc** [comment]
Btw, @mburumaxwell is this released? Can I start using it right away?

**Comment by mburumaxwell** [comment]
@nilekhc I should do a release within 24 hours.

In the meantime, the latest bits are on docker hub. If you're using the docker container image in a workflow you can use the `latest` tag. If you're using the task extension you can pass `latest` to the `dockerImageTag` task input.
