### ISSUE TITLE
No files changed! (RuntimeError)

### ISSUE THREAD

**Issue by sabareeshkkanan** [tinglesoftware/dependabot-azure-devops#358]
We are getting following error but i did made sure permissions are all set right. 

Version      : 1.8.225

warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-gradle-0.196.0/lib/dependabot/gradle/file_updater.rb:35:in `updated_dependency_files': No files changed! (RuntimeError)
	from ./update-script.rb:348:in `block in <main>'
	from ./update-script.rb:286:in `each'
	from ./update-script.rb:286:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Pull Requests shall be linked to work item dependabot
Fetching gradle dependency files for guidedchoice/microservice/_git/accounts
Targeting 'dev' branch under '/' directory
Using 'auto' requirements update strategy
Parsing dependencies information
Checking if org.jfrog.buildinfo:build-info-extractor-gradle 4+ needs updating
Requirements to unlock own
Updating org.jfrog.buildinfo:build-info-extractor-gradle from 4+ to 4.29.0
##[error]The process '/bin/docker' failed with exit code 1

**Comment by SabareeshGC** [comment]
Figured out the issue you may get this if you are not using absolute version 
Updating org.jfrog.buildinfo:build-info-extractor-gradle from 4+ to 4.29.0
You can simple disable the fail on error flag and continue or use absolute versioning

**Comment by mburumaxwell** [comment]
Thanks for reporting back. Closing
