### ISSUE TITLE
How do I switch from calling the github API for dependencies to chekcing it on a private artifactory?

### ISSUE THREAD

**Issue by Wincioor11** [tinglesoftware/dependabot-azure-devops#362]
How do I switch from calling the github API for dependencies to checking it on a private artifactory?

I tried adding a Private gradle / maven repo by using DEPENDABOT_EXTRA_CREDENTIALS, but the dependabot is still calling the github and get a ratelimit error.

**Comment by mburumaxwell** [comment]
To solve rate limiting, supply a GitHub access token using `gitHubConnection` or `gitHubAccessToken` input as described [here](https://github.com/tinglesoftware/dependabot-azure-devops/tree/main/src/extension).

Depedabot always checks for release notes (or change logs) from GitHub/GitLab. I don't think a private maven repository supports release notes. If it does, the support would need to be added in the [core repository](https://github.com/dependabot/dependabot-core).
