### ISSUE TITLE
Auto approve by Project Collection Build Service

### ISSUE THREAD

**Issue by molszews** [tinglesoftware/dependabot-azure-devops#377]
Seems like `autoApprove` does not support _Project Collection Build Service_ type of accounts as it tries to find the user id using email address via `/userentitlements` REST endpoint.

It is possible to use `System.AccessToken` and _Project Collection Build Service (projectName)_ identity to auto approve, one just need to fetch the user id via `curl -u :$(PAT) https://dev.azure.com/orgName/_apis/connectionData | jq -r '.authenticatedUser.id'`

Would it be possible to pass the user id directly to the task or fallback to the default user id (build service id) if none is provided?

**Comment by mburumaxwell** [comment]
@molszews anything is possible under the sun especially with contributions...
I am not as experienced with the specific details of authentication in Azure DevOps, it is always confusing for me. However, from the much I can gather, in your issue, this would need to be solved in the `pull_request_approve(...)` function/method:
1. Find a way to detect if the token is the same as `System.AccessToken` when the options are being formed [here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/f3e7ebe6118e7959a6a73c400546dd65106d5d7d/script/update-script.rb#L61). You could add a new option named `auto_approve_user_token_is_default`
2. Pass the new variable to the `pull_request_approve(...)` invocation [here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/f3e7ebe6118e7959a6a73c400546dd65106d5d7d/script/update-script.rb#L497-L501).
3. Update the `pull_request_approve(...)` function/method [here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/f3e7ebe6118e7959a6a73c400546dd65106d5d7d/script/azure_helpers.rb#L80-L84) to account for the new variable.

**Comment by mburumaxwell** [comment]
For auto-approval, it is recommended to use a dedicated PAT for a user on Azure DevOps which is not the same as auto-completion.

**Comment by mburumaxwell** [comment]
Likely fixed in #441
