### ISSUE TITLE
Auto merge PR with limited merging strategy (e.g. Rebase)

### ISSUE THREAD

**Issue by molszews** [tinglesoftware/dependabot-azure-devops#378]
If there are defined branch policies that limits the way PR can be merged one needs to first set `completionOptions` of the pull request object, otherwise it would look like all checks/policies are green but PR is still not merged and requires manual intervention. To fix that I had to use following curl:
```
PR_PATCH_URL="$SYSTEM_TEAMFOUNDATIONCOLLECTIONURI$SYSTEM_TEAMPROJECTID/_apis/git/repositories/PROJECT/pullrequests/$p?api-version=7.0"
curl -XPATCH -u :$(PAT) -H "Content-Type: application/json" -d "{ autoCompleteSetBy: \"$IDENTITY_ID\", completionOptions: { mergeStrategy: \"rebase\"} }" $PR_PATCH_URL
```
I think having optional task parameter for that purpose could be useful

**Comment by mburumaxwell** [comment]
@molszews , contributions are welcome
