### ISSUE TITLE
Private source authentication (was working last week)

### ISSUE THREAD

**Issue by Doddy-codes** [tinglesoftware/dependabot-azure-devops#379]
This job was working fine last week and no changes were made, however it is now failing with:

To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:319:in `check_npm_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): https://pkgs.dev.azure.com/BC-SDPR-Research/_packaging/Research/npm/registry/ (Dependabot::PrivateSourceAuthenticationFailure)
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:276:in `npm_details'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:108:in `valid_npm_details?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:36:in `latest_version_from_registry'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker.rb:294:in `latest_released_version'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker.rb:319:in `latest_version_details'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker.rb:39:in `latest_version'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.213.0/lib/dependabot/update_checkers/base.rb:231:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.213.0/lib/dependabot/update_checkers/base.rb:189:in `version_up_to_date?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.213.0/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-npm_and_yarn-0.213.0/lib/dependabot/npm_and_yarn/update_checker.rb:27:in `up_to_date?'
	from ./update-script.rb:332:in `block in <main>'
	from ./update-script.rb:310:in `each'
	from ./update-script.rb:310:in `<main>'
GitHub access token has been provided.
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
Pull Requests shall be linked to milestone (work item) 3499
Fetching npm_and_yarn dependency files for (our registry)
Targeting 'develop' branch under '/' directory
Parsing dependencies information
Checking if @babel/runtime 7.20.1 needs updating
No update needed for @babel/runtime 7.20.1
Checking if @research/react-app-cards 1.0.0 needs updating
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Run Dependabot - dtes

**OUR Pipeline is as defined below. NOTE: This was working last week and no changes were made**
schedules:
  - cron: "0 4 * * SAT"
    displayName: 'Weekly Run'
    always: true
    branches:
      include:
        - 'main'
trigger: none
pool:
  vmImage: 'ubuntu-latest'
variables:
    DEPENDABOT_EXTRA_CREDENTIALS: '[{"type":"npm_registry","token":"$(DEPENDABOT_PAT)","registry":"$(NPM_REG)"}]' # put the credentials for private registries and feeds
stages:
  - stage: Dtes
    jobs:
    - job: DependabotDtes
      steps:
      - task: Cache@2
        inputs:
          key: docker | "$(IMAGETOCACHE)"
          path: $(Pipeline.Workspace)/docker
          cacheHitVar: DOCKER_CACHE_HIT
        displayName: Cache Docker images
      - script: |
          docker load -i $(Pipeline.Workspace)/docker/cache.tar
        displayName: Restore Docker image
        condition: and(not(canceled()), eq(variables.DOCKER_CACHE_HIT, 'true'))
      - script: |
          mkdir -p $(Pipeline.Workspace)/docker
          docker pull -q $(IMAGETOCACHE)
          docker save -o $(Pipeline.Workspace)/docker/cache.tar $(IMAGETOCACHE)
        displayName: Save Docker image
        condition: and(not(canceled()), or(failed(), ne(variables.DOCKER_CACHE_HIT, 'true')))
      - task: dependabot@1
        displayName: 'Run Dependabot - dtes'
        inputs:
          useConfigFile: true
          setAutoComplete: false
          azureDevOpsAccessToken: $(DEPENDABOT_PAT)
          gitHubAccessToken: $(GITHUB_TOKEN)

**Varibales:**
IMAGETOCACHE = tingle/dependabot-azure-devops:latest
NPM_REG = our npm registry

Please let me know any suggestions, thank you.

**Comment by MO2k4** [comment]
I’ve got the same issue :-/

**Comment by mburumaxwell** [comment]
What's the value of NPM_REG?

**Comment by ChrisDoddGit** [comment]
NPM_REG is the research:registry in npmrc

https://pkgs.dev.azure.com/OUR_ORGANIZATION/_packaging/Research/npm/registry/

Thanks!

**Comment by ChrisDoddGit** [comment]
NOTE: When specifying a different dependabot tag, (0:7) the originally defined pipeline runs fine

**Comment by ChrisDoddGit** [comment]
The updated dependabot image (0:10) has resolved the issue. Can close this issue.

Thank you for your help
