### ISSUE TITLE
entrypoint error when running in azure devops

### ISSUE THREAD

**Issue by dgcaron** [tinglesoftware/dependabot-azure-devops#380]
the docker image (tingle/dependabot-azure-devops:latest) started producing the following error in azure devops starting last thursday:

docker: Error response from daemon: failed to create shim: OCI runtime create failed: runc create failed: unable to start container process: exec: "./entrypoint.sh": permission denied: unknown..

it looks like this is introduced in version 0.9.3.

**Comment by MiKuehn** [comment]
./entrypoint.sh doesn't have execute permission.

I fixed this in my docker image with:

`RUN chmod +x entrypoint.sh`

**Comment by mburumaxwell** [comment]
Fixed in #384

**Comment by dgcaron** [comment]
i can confirm this working now, thanks!
