### ISSUE TITLE
Custom labels specified not used

### ISSUE THREAD

**Issue by mmoreno79** [tinglesoftware/dependabot-azure-devops#398]
Hello, we are making use of the custom labels feature released in 0.9.0 so that we can differentiate between PR's that should be automatically merged and those that should be reviewed. In our case, minor and patch bumps would be automatically merged, while major bumps aren't. The label we are trying to use is simply "automerge".

The reason why we currently can't use the autocomplete and auto approve is because our branch policy requires two reviewers. There are steps after dependabot in the pipeline that will find all PR's with this label and complete them by bypassing policies using the devops rest api.

Here is the script we're using in the pipeline:

```
      docker run --rm -t \
        -e GITHUB_ACCESS_TOKEN=$(dependabot-gh-pat) \
        -e AZURE_HOSTNAME=dev.azure.com \
        -e AZURE_ACCESS_TOKEN=$(dependabot-pat) \
        -e AZURE_ORGANIZATION={redacted} \
        -e AZURE_PROJECT=${{ parameters.project }} \
        -e AZURE_REPOSITORY=${{ parameters.repository }} \
        -e DEPENDABOT_DIRECTORY=${{ parameters.directory }} \
        -e DEPENDABOT_MILESTONE=${{ parameters.parent_wi }} \
        -e DEPENDABOT_PACKAGE_MANAGER=${{ parameters.pkg_mgr }} \
        -e DEPENDABOT_VERSIONING_STRATEGY=auto \
        -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=${{ parameters.pr_limit }} \
        -e DEPENDABOT_IGNORE_CONDITIONS='${{ parameters.ignore_cond }}' \
        -e DEPENDABOT_EXTRA_CREDENTIALS={redacted} \
        -e DEPENDABOT_LABELS='["automerge", "dependencies"]' \
        -e AZURE_SET_AUTO_COMPLETE=${{ lower(parameters.autocomplete) }} \
        tingle/dependabot-azure-devops:0.10
```

I see the following note in the github dependabot docs stating that the labels must already exist, so I ensured the label was added to other PRs first:

> You can use labels to override the default labels and specify alternative labels for all pull requests raised for a package manager. You can't create new labels in the dependabot.yml file, so the alternative labels must already exist in the repository.

After the pipeline completes, we see the dependencies label but not the automerge label. What am I missing?

**Comment by mmoreno79** [comment]
@mburumaxwell Dang. Thanks for the reply. Given what I could describe in my original description, does that sound like a reasonable approach to autocompleting minor/patch bumps only? Would you recommend any other way?

**Comment by mmoreno79** [comment]
Also, it looks like the PR in dependabot-core is waiting for your review

**Comment by mburumaxwell** [comment]
> @mburumaxwell Dang. Thanks for the reply. Given what I could describe in my original description, does that sound like a reasonable approach to autocompleting minor/patch bumps only? Would you recommend any other way?

When you are already using the DevOps REST API and the docker image directly in place of the task extension then you are already a pro (not the Apple version). If you are able to bypass policy validation, then by all means you have succeeded at doing the necessary. I cannot see any other way to go around given the policies on Azure DevOps can only filter against paths. 

One alternative is to have a `develop` branch alongside the `main` only this time without the strenuous policies; direct dependabot to create PRs against the develop branch then occasionally merge the develop branch onto the main (fast forward). It creates an extra step.

While we are here, may I ask if there is a specific reason you use the docker image directly instead of the task?

**Comment by mburumaxwell** [comment]
Want to contribute a fix?

**Comment by mmoreno79** [comment]
Submitted https://github.com/tinglesoftware/dependabot-azure-devops/pull/403

**Comment by mburumaxwell** [comment]
Custom labels finally merged into upstream in https://github.com/dependabot/dependabot-core/pull/5767

**Comment by mburumaxwell** [comment]
@mmoreno79 there's still no new release for dependabot since 0.215.0 but the new bits are now available here. Could you test using the specific input `dockerImageTag: 0.14.2-ci.7`?
