### ISSUE TITLE
Build agent with full access still requires PAT

### ISSUE THREAD

**Issue by thviQit** [tinglesoftware/dependabot-azure-devops#40]
First of all, great initiative wrapping this for Azure DevOps. MS should have done this right after acquiring GitHub.

I am trying to get this up and running on a test repository using the yaml template provided in the Marketplace.
However, I discovered that our build agents kept getting this error:
_Message TF401398: The pull request cannot be activated because the source and/or the target branch no longer exists, or the requested refs are not branches_

First I thought I needed to do `refs/heads/master` for the branch name, but that didn't work.
Finally I added a new PAT for `azureDevOpsAccessToken` instead of defaulting to the build agent's, and then it worked.

The weird thing is that the build agent has a PAT with full access.

In the extension the token is acquired using `tl.getEndpointAuthorizationParameter("SystemVssConnection", "AccessToken", false);` if `azureDevOpsAccessToken` is empty.
Azure DevOps seems to recommend using `tl.getVariable('System.AccessToken');` which might solve it.

I am hoping you would investigate and check if you can reproduce this?

**Comment by mburumaxwell** [comment]
Hi, I couldn't agree more on official support. Sadly, there are more things that need to be added to Azure DevOps before this can work like the GitHub native version. For example, automatic creation of build pipelines by adding YAML files to the repository. Seems, we'll be on our own for a while.

I'd like to investigate your authentication issue further.

The earliest versions of the extensions used `tl.getVariable('System.AccessToken')` but it would occasionally return be null. The new way of getting access token is indeed using `tl.getEndpointAuthorizationParameter("System.VssConnection", "AccessToken", false);`. Read more [here ](https://github.com/microsoft/azure-pipelines-task-lib/issues/579).

Confirm that the `Pull Requests Threads (Read & Write)` permission is granted to the `Project Collection Build Service ({organization-name-here})` group. This is done in the repositories tab of the Azure DevOps project you are working on. The URL should be in the format `https://dev.azure.com/{organization}/{project}/_settings/repositories?_a=permissions`.  Search for the user named in the format `Project Collection Build Service ({organization})` then set `Allow` for the `Contribute to pull requests` permission.

Hope that helps.

**Comment by thviQit** [comment]
Thanks for the reply - and the help.

I figured it would be enough with a token, that gave full access, but you were right. We actually have 2 build service users, and one did not have `Allow` for `Contribute to pull requests`. Just ran a test, and now it works without the extra PAT.

Regarding automatic build pipelines, Azure DevOps did support 1. You could drop azure-pipelines.yml in the root of your repo, and Azure DevOps would pick it up. But according to [this issue here](https://developercommunity.visualstudio.com/content/problem/1129219/azure-pipelinesyml-not-creating-pipeline-automatic.html) it has been disabled.

Still it wasn't very flexible, as you can only have one trigger and you quickly have 2-3 types of builds for a repo + deployment ...

Anyway - thanks for the insight 🙂
