### ISSUE TITLE
Dependabot build fails when it scans the nuget package (the build works fine when it scans npm package)

### ISSUE THREAD

**Issue by EmilSahin88** [tinglesoftware/dependabot-azure-devops#421]
warning: parser/current is loading parser/ruby31, which recognizes3.1.3-compliant syntax, but you are running 3.1.2.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/usr/local/lib/ruby/3.1.0/pathname.rb:528:in `relative_path_from': different prefix: "/" and "src/Jar/Jar.Web" (ArgumentError)
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:29:in `block in fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:28:in `each'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/file_fetchers/base.rb:75:in `files'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:20:in `config_file'
	from ./update-script.rb:271:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
##[error]The process '/usr/bin/docker' failed with exit code 1

**Comment by mburumaxwell** [comment]
Possibly fixed in #423 ?

**Comment by EmilSahin88** [comment]
Thanks for the answer. 
But I am unfortunately still getting the error:

`Starting: Run Dependabot - nuget
==============================================================================
Task         : Dependabot
Description  : Automatically update dependencies and vulnerabilities in your code
Version      : 1.11.300
Author       : Tingle Software
Help         : For help please visit https://github.com/tinglesoftware/dependabot-azure-devops
==============================================================================
##[warning]
        Using explicit inputs instead of a configuration file is deprecated and will be removed in version 0.13.0.
        No new features will be added to the use of explicit inputs that can also be specified in the configuration file.

        Migrate to using a config file at .github/dependabot.yml.
        See https://github.com/tinglesoftware/dependabot-azure-devops/tree/main/extension#usage for more information.
        
/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=nuget -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e DEPENDABOT_REJECT_EXTERNAL_CODE=false -e DEPENDABOT_EXCLUDE_REQUIREMENTS_TO_UNLOCK= -e AZURE_PROTOCOL=https -e AZURE_HOSTNAME=dev.azure.com -e AZURE_ORGANIZATION=cowigroup -e AZURE_PROJECT=Jordforureningslovens%20Areal%20Register -e AZURE_REPOSITORY=JAR -e AZURE_ACCESS_TOKEN=*** -e AZURE_SET_AUTO_COMPLETE=false -e AZURE_AUTO_COMPLETE_IGNORE_CONFIG_IDS=[] -e AZURE_MERGE_STRATEGY=2 -e DEPENDABOT_DIRECTORY=src/Jar/Jar.Web -e DEPENDABOT_TARGET_BRANCH=development -e DEPENDABOT_VERSIONING_STRATEGY=auto -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 -e AZURE_AUTO_APPROVE_PR=false tingle/dependabot-azure-devops:0.11
warning: parser/current is loading parser/ruby31, which recognizes3.1.3-compliant syntax, but you are running 3.1.2.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/usr/local/lib/ruby/3.1.0/pathname.rb:528:in `relative_path_from': different prefix: "/" and "src/Jar/Jar.Web" (ArgumentError)
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:29:in `block in fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:28:in `each'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/file_fetchers/base.rb:75:in `files'
	from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.214.0/lib/dependabot/config/file_fetcher.rb:20:in `config_file'
	from ./update-script.rb:271:in `<main>'
Using hostname = 'dev.azure.com', protocol = 'https', port = '443'.
Using '[https://dev.azure.com:443/'](https://dev.azure.com/') as API endpoint
##[error]The process '/usr/bin/docker' failed with exit code 1
Finishing: Run Dependabot - nuget`

**Comment by mburumaxwell** [comment]
Share the pipeline and configuration file.

**Comment by EmilSahin88** [comment]
OMG - how can I be so blind??

Thank you @mburumaxwell, it worked :)

**Comment by EmilSahin88** [comment]
It works
