### ISSUE TITLE
PRs are not closed when the packages are updated manually

### ISSUE THREAD

**Issue by lara-ec** [tinglesoftware/dependabot-azure-devops#432]
Hi, first of all, thanks for your work :)

In certain cases, I have to do the package updates manually, e.g. with Angular or when multiple entity framework core packages require specific versions of other packages, and thus need to be updated all at once.

It would be great if dependabot could detect that and close the outdated PRs where the packages are already up to date. Instead I have to close all those PRs by hand.

**Comment by mburumaxwell** [comment]
@lara-ec at the moment, the easiest way to get around this is to rerun the pipeline to automatically solve merge conflicts. Maybe at the same time, PRs that are no longer required can be closed.
We may not have time to get this done at the moment as there are higher priorities for this repo's work. However, you can make contributions with the following pointers:
1. Active PRs are pulled https://github.com/tinglesoftware/dependabot-azure-devops/blob/0ed0549ae1fff3a0612fef00ac089308666e0bbf/script/update-script.rb#L450
2. Add logic for closing PR exists https://github.com/tinglesoftware/dependabot-azure-devops/blob/0ed0549ae1fff3a0612fef00ac089308666e0bbf/script/update-script.rb#L609-L610
3. Add logic for closing unwanted PRs after updates have been done at https://github.com/tinglesoftware/dependabot-azure-devops/blob/0ed0549ae1fff3a0612fef00ac089308666e0bbf/script/update-script.rb#L736 and this can be similar to the logic for finding existing PRs for a dependency https://github.com/tinglesoftware/dependabot-azure-devops/blob/0ed0549ae1fff3a0612fef00ac089308666e0bbf/script/update-script.rb#L585-L628 with a few caveats:
    - How to differentiate PRs that were not created by dependabot given labels can be altered. (Solution: use the creator User Id, in `azure_helpers.rb` when fetching)
    - Check the version declared in the PR title is not the one in the listed dependencies. For example, a PR with the title `Bump Microsoft.EntityFrameworkCore.Relational from 6.0.0 ` should be closed if the `Microsoft.EntityFrameworkCore.Relational` dependency has a version other than 6.0.0
