### ISSUE TITLE
Troubleshooting PR creation failure

### ISSUE THREAD

**Issue by tomkerkhove** [tinglesoftware/dependabot-azure-devops#437]
I'm currently trying to mitigate this issue:

```
Checking if dotnet/aspnet 6.0.11-alpine3.16 needs updating
Requirements to unlock own
Updating dotnet/aspnet from 6.0.11-alpine3.16 to 6.0.12-alpine3.16
Submitting dotnet/aspnet pull request for creation. Failed! PR already exists or an error has occurred.
```

However, the permissions look good based on the docs [here](https://marketplace.visualstudio.com/items?itemName=tingle-software.dependabot):

![image](https://user-images.githubusercontent.com/4345663/207817917-6f3dd06a-797b-4bc1-83f4-cfc187f04a9b.png)

Any further tips how to fix this? There are no open PRs.

**Comment by MO2k4** [comment]
I think its the wrong user, as this is not the user which executes the pipeline, could you go back to all repositories and there check security for a user like '<ProjectName> Build Service (<org>)' and change the security settings there?

**Comment by tomkerkhove** [comment]
I have changed that as well but no luck. Is there a way to get more details?

**Comment by tomkerkhove** [comment]
PAT also didn't work.

However, I'm seeing this:
```
warning: parser/current is loading parser/ruby31, which recognizes3.1.3-compliant syntax, but you are running 3.1.2.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
./update-script.rb:570:in `block in <main>': Pull Request creation failed with status 400. Message: Invalid argument value.\r (StandardError)
Parameter name: The identity dependabot is not recognized.
from ./update-script.rb:364:in `each'
from ./update-script.rb:364:in `<main>'
```
https://dev.azure.com/tomkerkhove/Dependabot/_build/results?buildId=9634&view=logs&j=011e1ec8-6569-5e69-4f06-baf193d1351e&t=45b7c07f-c76c-5a86-56bd-20f45fe1a607

**Comment by tomkerkhove** [comment]
That was it, it might be good to improve the logs there though.

**Comment by mburumaxwell** [comment]
With #438 you may have better visibility into the requests and responses for HTTP
