### ISSUE TITLE
Support of assignees and reviewers

### ISSUE THREAD

**Issue by Pascal997** [tinglesoftware/dependabot-azure-devops#45]
Hello,

Can we specify `assignees` and / or `reviewers` at the PR creation?

The original project seems to support it using the `dependabot.yml` file.

Thanks

**Comment by mburumaxwell** [comment]
@Pascal997 ,

Support for `dependabot.yml` file located at `.azuredevops/dependabot.yml` is now [available](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.2.2). Maybe you can get an initial PR submitted and we can iterate on the specifics?

**Comment by mburumaxwell** [comment]
@Pascal997,

Support for `assignees` and/or `reviewers` is not present in the upstream repository, see [link](https://github.com/dependabot/dependabot-core/blob/aeb24117348547966a2451adbeb40cac3de388c7/common/lib/dependabot/clients/azure.rb#L172-L179). 

You can however solve this case using branch policies in Azure DevOps that add approvers automatically to any new PR. I will proceed and close this issue as there is nothing more left.

**Comment by mburumaxwell** [comment]
Added in #428

**Comment by TobiasB91** [comment]
Is this still working?

**Comment by TobiasB91** [comment]
@mburumaxwell I see. I tried it and this works but in also makes all reviewers required to approve. In our workflow we approve PRs if one developer approves. Is there still an option to set optional reviewers to allow this?

**Comment by mburumaxwell** [comment]
I see what you mean about being required. `assignees` were required reviewers while `reviewers` were not.
https://github.com/mburumaxwell/dependabot-azure-devops/blob/b4edfb4fd93b965800d98cba89b02dc61a005119/extensions/azure/src/azure-devops/client.ts#L196-L199

With the [deprecation of `reviewers` in dependabot](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/), the recommendation is to use `CODEOWNERS` in GitHub to enforce rules. Technically, the equivalent of that is using branch policies in Azure DevOps.

Making the change in https://github.com/mburumaxwell/dependabot-azure-devops/pull/1761
