### ISSUE TITLE
Regex convertPlaceholder is broken

### ISSUE THREAD

**Issue by WhiteOlivierus** [tinglesoftware/dependabot-azure-devops#461]
I think there was a mistake.

https://github.com/tinglesoftware/dependabot-azure-devops/blob/75df48ab6b5999ad614107a447858f225a113f96/extension/task/utils/convertPlaceholder.ts#L4

This does not work:
https://regex101.com/r/bmIth9/1

This works:
https://regex101.com/r/q0hfGm/1

**Comment by WhiteOlivierus** [comment]
version: 2
registries:
  nuget-azure-devops:
    type: nuget-feed
    url: 
    password: PAT:${{PAT}}
updates:
- package-ecosystem: nuget
  directory: "/source"
  target-branch: "feature/dependabot"
  # target-branch: "acceptance"
  registries:
  - nuget-azure-devops
  open-pull-requests-limit: 1

**Comment by WhiteOlivierus** [comment]
You can close this item. Found the problem, was missing a permission

**Comment by mburumaxwell** [comment]
Thanks for getting back. Could you kindly contribute the unit tests?

**Comment by WhiteOlivierus** [comment]
Yes I could. I will make a pr monday for you
