### ISSUE TITLE
Run updates in the same repository at different times

### ISSUE THREAD

**Issue by michalwawa** [tinglesoftware/dependabot-azure-devops#466]
Hi

I have a question. Is extension site updated with new changes (https://marketplace.visualstudio.com/items?itemName=tingle-software.dependabot) ? Task parameters list seems to be old on extension site and it is different comparing to https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/extension/README.md. For example in github readme there is no directory task parameter. Is it deprecated now ?

**Comment by michalwawa** [comment]
My question is because we have multiple projects in the repo and I assume when we have one global configuration files and many pipelines for dependabot each of them will trigger pull request on all declared directories in config file ? For example in config files we have 2 declared nuget packages for directory A and for directory B and we have azure pipelines for specific directory: PipelineA and PipelineB with own schedule etc. So if config file has 2 cfgs for nuget each pipeline will trigger checking for these 2 projects in different path ? Before forcing to use global cfg file we were able to prepare pipeline per directory, is there any option to make it with new approach with .github/dependabot.yml ?

**Comment by mburumaxwell** [comment]
Hi @michalwawa the differences are due to the latest changes. As from Verizon 0.14 a configuration file is required. The directory, packageEcosystem and similar variables are not placed in the .github/dependabot.yml file

Unfortunately, using a single configuration file for multiple repositories will not work. Each repository needs its own configuration file.

However, you can run a single pipeline with work on multiple repositories using multiple tasks while changing the targetRepository input for each repository.

**Comment by michalwawa** [comment]
> Hi @michalwawa the differences are due to the latest changes. As from Verizon 0.14 a configuration file is required. The directory, packageEcosystem and similar variables are not placed in the .github/dependabot.yml file
> 
> Unfortunately, using a single configuration file for multiple repositories will not work. Each repository needs its own configuration file.
> 
> However, you can run a single pipeline with work on multiple repositories using multiple tasks while changing the targetRepository input for each repository.

Hello, maybe i did not write this clear. We have not many repository but one repository with many projects/solutions are structure looks like for example:

Repository
-> project A (solution A) -> applications
-> project B (solution B) -> applications
... etc.

Most of our projects are in .Net so in one repo we have many solutions and in them many applications. All of them are based on Nuget packages. Is there any option to define pipelines per solutions while we will have one global configuration in .github/dependabot

Currently we were defining in pipeline in dependabot@ task parametrs like: directory, packet manager etc so we were able to make pipeline per solution

**Comment by mburumaxwell** [comment]
The only alternative here is to work with the schedule in the configuration. Unfortunately, that cannot be picked up by the pipeline.
I will get back to you when we are ready for external usage on the managed version in a few of weeks.

**Comment by mburumaxwell** [comment]
@michalwawa could this be solved using #478 ?

**Comment by michalwawa** [comment]
> @michalwawa could this be solved using #478 ?

If I understand correctly, when someone declare in pipeline targetUpdateId, pipeline will only trigger these chosen updates? But I think in PR is mistake, because in example pipline there is targetUpdateIds:0,3 but should it be 0,2 ?

**Comment by mburumaxwell** [comment]
> > @michalwawa could this be solved using #478 ?
> 
> 
> 
> If I understand correctly, when someone declare in pipeline targetUpdateId, pipeline will only trigger these chosen updates? But I think in PR is mistake, because in example pipline there is targetUpdateIds:0,3 but should it be 0,2 ?

Your understanding is correct. Yes, it should be `0;2`
Would it be a solution for you?

**Comment by michalwawa** [comment]
> > > @michalwawa could this be solved using #478 ?
> > 
> > 
> > If I understand correctly, when someone declare in pipeline targetUpdateId, pipeline will only trigger these chosen updates? But I think in PR is mistake, because in example pipline there is targetUpdateIds:0,3 but should it be 0,2 ?
> 
> Your understanding is correct. Yes, it should be `0;2` Would it be a solution for you?

Yes, this will be fantastic solution. Right now I found workaround. I Just send additional variabales in extraEnvVariables and override values in configuration file  but this is not perfect way to handle this. Your proposition is perfect.

**Comment by michalwawa** [comment]
@mburumaxwell can I use it already or I need to wait when extension will be updated ?

**Comment by mburumaxwell** [comment]
@michalwawa Yes you can do so. Released in [0.14.1](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.14.1)
