### ISSUE TITLE
Dependabot version 0.14.0.404 not updating nuget packages

### ISSUE THREAD

**Issue by michalwawa** [tinglesoftware/dependabot-azure-devops#475]
Hello

After changing our dependabot installation to use global configuration, dependabot stops to updating nuget packages. Current version of extension is: 0.14.0.404

Azure peopline is working ok, when we run it, it finish with success status but in logs we can see:

Checking if Grpc.Tools 2.50.0 needs updating
Requirements to unlock update_not_possible
Requirements update strategy 

Pull requests are not creating.

**Comment by michalwawa** [comment]
Ok, that was my mistake, I just needed to add another nuget repo. Case closed

**Comment by mburumaxwell** [comment]
Okay

**Comment by cancan101** [comment]
What was the issue here? I am seeing "Requirements to unlock update_not_possible" messages with composer.
