### ISSUE TITLE
Dependabot 0.14 crashes on azure_helpers.rb:35:in `branch_delete': undefined method 

### ISSUE THREAD

**Issue by air2** [tinglesoftware/dependabot-azure-devops#477]
When using 0.14 it crashes on me with the following log

https://pastebin.com/g283zEEs

It is too big to paste here.

**Comment by mburumaxwell** [comment]
I will look into this and revert.
The last change to that particular method was in #440

Meanwhile, I'd appreciate any other context you can provide

**Comment by mburumaxwell** [comment]
@air2 Is this still happening?

**Comment by air2** [comment]
I am not sure, because I use the latest version now, So it is not happening in the latest version
