### ISSUE TITLE
include packs from optionalDependencies in scan

### ISSUE THREAD

**Issue by BeataKr** [tinglesoftware/dependabot-azure-devops#494]
Is there any parameter in which we can extend scanned packs by `optionalDependencies`?

**Comment by mburumaxwell** [comment]
What do you meant by scanned packs and optionalDependencies?

**Comment by BeataKr** [comment]
Scanned packs -> found by Dependabot dependenies from parsed files.
[optionalDependencies ](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#optionaldependencies) - as I can see Dependabot takes `dependencies` and `devDependencies` ignoring `optionalDependencies` and any potential [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides).

**Comment by mburumaxwell** [comment]
This is something that would need to be supported in the main repository https://github.com/dependabot/dependabot-core as it relates to the parsing of dependencies listed in `package.json`. Could you create an issue there instead?

**Comment by BeataKr** [comment]
Yes, raised under https://github.com/dependabot/dependabot-core/issues/6566

**Comment by mburumaxwell** [comment]
Closing in favour of https://github.com/dependabot/dependabot-core/issues/6566
