### ISSUE TITLE
Configuration file not found

### ISSUE THREAD

**Issue by mikaeldiener** [tinglesoftware/dependabot-azure-devops#495]
I get the following error message eventhough I have a configuration file at /.github/

My pipeline-file that inits the dependabot task is located in /.pipelines/ from root.

If Im doing something wrong, could someone please provide a repository with a working sample.

##[error]Configuration file not found at possible locations: /.github/dependabot.yaml, /.github/dependabot.yml

**Comment by mburumaxwell** [comment]
The only difference I see is the nesting of the pipeline definition file under the `.pipelines` folder. I have tried to reproduce this and it seems to work just fine.

Repository: https://dev.azure.com/tingle/dependabot/_git/repro-495
Pipeline run: https://dev.azure.com/tingle/dependabot/_build/results?buildId=55128

Did I miss anything?

**Comment by mikaeldiener** [comment]
Thank you! I´ve realized that I needed to move the .github-dir one step further up the directory path. I hadn´t put it directly under the root path.

I´ve copied your config file, which works for a while (longer than my previous problem), it downloads the tingle-image and tries to locate a configuration file (again?) but now it says:

```
Configuration file was not found, a default config will be used. 😔
Fetching nuget dependency files ...
```

And returns with an error: `##[error]The process '/usr/bin/docker' failed with exit code 1.`

**Comment by mikaeldiener** [comment]
Never mind, I found out that I had to manually specify a target branch during testing. Thanks a lot for the help!
