### ISSUE TITLE
##[error]Configuration file not found at possible locations: /.github/dependabot.yaml, /.github/dependabot.yml

### ISSUE THREAD

**Issue by EmilSahin88** [tinglesoftware/dependabot-azure-devops#511]
Hi guys

I am experiecing following when I use Dependabot on Azure Devops:

- ##[error]Configuration file not found at possible locations: /.github/dependabot.yaml, /.github/dependabot.yml

Can you please help?

**Comment by mburumaxwell** [comment]
@EmilSahin88 you need to add a configuration file at either of the two paths. The contents of which are described [here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)

**Comment by EmilSahin88** [comment]
Thank you Maxwell - I can see that I had a misspelling in the
dependabot.yml file.
I did wrote depandabot.yml instead of dependabot.yml

Den man. 13. feb. 2023 kl. 19.40 skrev Maxwell Weru <
***@***.***>:
