### ISSUE TITLE
"bundle": cannot run executable found relative to current directory

### ISSUE THREAD

**Issue by whiskeysierra** [tinglesoftware/dependabot-azure-devops#519]
We're running in Azure DevOps Pipelines and since the weekend we're seeing this:

```
Digest: sha256:6b25824a73b30594742ce66e987893f775583ae20bf24e43858d3dda7c893001
Status: Downloaded newer image for tingle/dependabot-azure-devops@sha256:6b25824a73b30594742ce66e987893f775583ae20bf24e43858d3dda7c893001
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bundle": cannot run executable found relative to current directory: unknown.
```

We haven't updated the version in the recent weeks, so I'm somewhat confused why it started to break.
Have you seen this before?

**Comment by hollowdrutt** [comment]
I had the same issue, I was still on version 0.9. I updated to 0.14.1 and that error disappeared but I got the error `TF401027: You need the Git 'GenericContribute' permission to perform this action.`
I added `Contribute` permission to the build service and then it worked.

**Comment by mburumaxwell** [comment]
Could either of you provide a public repro of this?

**Comment by hollowdrutt** [comment]
@mburumaxwell https://github.com/hollowdrutt/dependabot-azure-devops-error-repro
```
2023-02-24T09:46:56.4990380Z 6b7bfb231103: Pull complete
2023-02-24T09:46:56.5038420Z Digest: sha256:6b25824a73b30594742ce66e987893f775583ae20bf24e43858d3dda7c893001
2023-02-24T09:46:56.5052786Z Status: Downloaded newer image for tingle/dependabot-azure-devops:0.9.0
2023-02-24T09:46:56.9051863Z docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bundle": cannot run executable found relative to current directory: unknown.
2023-02-24T09:46:56.9150569Z ##[error]The process '/usr/bin/docker' failed with exit code 125
2023-02-24T09:46:56.9186443Z ##[section]Finishing: dependabot
```
I tried with different versions in another pipeline, 0.10.0 did not produce the error.

**Comment by mburumaxwell** [comment]
Is there a particular reason you're using version 0.9.0? Can you updated to the latest (0.15.0).

The 0.9.0 image hasn't been updated since almost 6 months ago. See https://hub.docker.com/layers/tingle/dependabot-azure-devops/0.9.0/images/sha256-6b25824a73b30594742ce66e987893f775583ae20bf24e43858d3dda7c893001
However, the extension has been updated and using different major/minor version between docker image and the extension may bring issues and isn't supported. If you have to use the older version then you have to fix the task version too. I haven't tried this for very old version but it should be something like `- task: dependabot@1.9.0` in your case

**Comment by hollowdrutt** [comment]
I have already updated to 0.14.1 which solved that error for me.

**Comment by whiskeysierra** [comment]
I've been running 1.12.1, iirc and had the same issue.

**Comment by whiskeysierra** [comment]
Or 0.12.1.

**Comment by mburumaxwell** [comment]
Is there a reason to use the particular version and not the latest? Have you tried not specifying the version and letting the extension select it?

**Comment by mburumaxwell** [comment]
With the docker container you can use the `latest` tag or just the major version or the major na d minor combined. Either of the following should get you a more recent version:
- `ghcr.io/tinglesoftware/dependabot-updater:latest`
- `ghcr.io/tinglesoftware/dependabot-updater:0`
- `ghcr.io/tinglesoftware/dependabot-updater:0.15`

Still I'd like to know the reason(s) behind not using the latest version.

**Comment by whiskeysierra** [comment]
The reason for us is that we can't/won't/shouldn't give a third party tool
direct access to our source code without reviewing the tool first.

Not to mention breaking changes in the recent versions.

**Comment by mburumaxwell** [comment]
@whiskeysierra The code base is open, what makes you feel that you're giving 3rd party access? I don't understand the difference in giving access here between versions.

Breaking changes are inevitable, the code has to evolve to support more scenarios. If your don't like that, you could fork an earlier version and you wouldn't have to give anyone access. On that I can't help you.

**Comment by whiskeysierra** [comment]
> The code base is open, what makes you feel that you're giving 3rd party access? I don't understand the difference in giving access here between versions.

Projects being taken over by malicious actors isn't unheard of.
Could be just a contributor sneaking in a backdoor, or someone taking over the dockerhub repository.
By just using `latest`, I'm prone to all of those attacks.

> Breaking changes are inevitable, the code has to evolve to support more scenarios.

Absolutely, I understand. It's just another reason why I'm not comfortable with `latest`, because if a breaking change comes, it will break all of our pipelines.
An old version may not have the latest features, but it should run indefinitely (or so I thought, until I opened this issue).

**Comment by mburumaxwell** [comment]
I understand your reasoning. Unfortunately, I cannot help you with this, too many restrictions and hoops to jump. I will close the issue. If anything changes, you can reopen.
