### ISSUE TITLE
How to add ADO-Groups to be Assignee / Reviewer

### ISSUE THREAD

**Issue by drvup** [tinglesoftware/dependabot-azure-devops#543]
Dear all,

thanks for the great project and the contribution. Since some days we're using your ADO integration and I am on the journey to get it rolled out to our complete ADO landscape for all applications. 

I am wondering if it's possible to add groups instead users to the yaml file as assignee or reviewer. I tried this with the name of the group and also with the domain-ID (I guess, it's the correct uuid). No luck there. So before diving more into it, can you let me know if this is supported already?

Thanks in advance,
BR, Cedric

**Comment by mburumaxwell** [comment]
Have you tried using the group identifier in place of a username?

**Comment by drvup** [comment]
Hi @mburumaxwell - thanks for the reply last week. Sry for the delay, I was on sick leave.
I find a way to provide the uuid of the group by using `extraEnvironmentVariables` approach:

`
- task: dependabot@1
  inputs:
    extraEnvironmentVariables: DEPENDABOT_ASSIGNEES=["11c05ac8-9c71-41a4-b483-12345678"]
`

Regards,
Cedric

**Comment by mburumaxwell** [comment]
You can also provide the same values in the configuration file.

```yml
version: 2
updates:
- package-ecosystem: "nuget"
  directory: "/"
  assignees:
  - "11c05ac8-9c71-41a4-b483-12345678"
```
