### ISSUE TITLE
Unauthorized (401) for private NPM feeds in Azure Devops Service

### ISSUE THREAD

**Issue by Sandy1438** [tinglesoftware/dependabot-azure-devops#545]
Hi All,

Can anyone please help me to to fix unauthorize errors for private npm registry?
I have tried implementing with all the possibilities that others had faced and resolved it but no much luck for me.

dependabot.yml
------------------
version: 2
registries:
  npm-ado:
    type: npm-registry
    url: https://pkgs.dev.azure.com/DVP/SYSTEMS/_packaging/Gdp/npm/registry/
    token: "PAT:${{DEPENDABOT_TOKEN}}"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    
azure-pipeline.yaml
---------------------
stages:
  - stage: CheckDependencies
    displayName: 'Check Dependencies'
    jobs:
      - job: Dependabot
        displayName: 'Run Dependabot'
        pool:
          vmImage: "ubuntu-latest"
        variables:
          - group: gdp-variables
        steps:
          - task: dependabot@1
            displayName: 'Run Dependabot'
            inputs:
              targetBranch: 'master'
              azureDevOpsAccessToken: $(DEPENDABOT_TOKEN)
              extraEnvironmentVariables: 'EXCON_DEBUG=1'

Log Snippet:
--------------
excon.response
  :body              => "{\"$id\":\"1\",\"innerException\":null,\"message\":\"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.\",\"typeName\":\"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server\",\"typeKey\":\"UnauthorizedRequestException\",\"errorCode\":0,\"eventId\":3000}"
  :cookies           => [
  ]
  :headers           => {
    "Access-Control-Expose-Headers" => "Request-Context"
    "Cache-Control"                 => "no-cache"
    "Content-Length"                => "343"
    "Content-Type"                  => "application/json; charset=utf-8"
    "Date"                          => "Thu, 02 Mar 2023 11:40:30 GMT"
    "Expires"                       => "-1"
    "P3P"                           => "CP=\"CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT\""
    "Pragma"                        => "no-cache"
    "Strict-Transport-Security"     => "max-age=31536000; includeSubDomains"
    "WWW-Authenticate"              => "Bearer authorization_uri=https://login.windows.net/f25493ae-1c98-41d7-8a33-0be75f5fe603, Basic realm=\"https://pkgsprodsu3weu.app.pkgs.visualstudio.com/\", TFS-Federated"
    "X-Cache"                       => "CONFIG_NOCACHE"
    "X-Content-Type-Options"        => "nosniff"
    "X-FRAME-OPTIONS"               => "SAMEORIGIN"
    "X-MSEdge-Ref"                  => "Ref A: E646D5B7D0C1406CBA134A2503C19155 Ref B: DB3EDGE3212 Ref C: 2023-03-02T11:40:31Z"
    "X-TFS-FedAuthIssuer"           => "https://www.visualstudio.com/"
    "X-TFS-FedAuthRealm"            => "https://pkgsprodsu3weu.app.pkgs.visualstudio.com/"
    "X-TFS-FedAuthRedirect"         => "https://spsprodweu4.vssps.visualstudio.com/_signin?realm=volvogroup-dvp.pkgs.visualstudio.com&reply_to=https%3A%2F%2Fvolvogroup-dvp.pkgs.visualstudio.com%2FDSBS-SYSTEMS%2F_packaging%2FGdsp%2Fnpm%2Fregistry%2F%40backend%2Fcommon-utils&redirect=1&hid=30da452d-ca8e-443a-b954-9cb4ea249165&context=eyJodCI6MiwiaGlkIjoiODJhYTU0NzgtYmJlZS00YTNiLTliYzMtMzQ3N2RlYTM2MWUwIiwicXMiOnt9LCJyciI6IiIsInZoIjoiIiwiY3YiOiIiLCJjcyI6IiJ90#ctx=eyJTaWduSW5Db29raWVEb21haW5zIjpbImh0dHBzOi8vbG9naW4ud2luZG93cy5uZXQiXX01"
    "X-VSS-AuthorizationEndpoint"   => "https://vssps.dev.azure.com/VolvoGroup-DVP/"
    "X-VSS-E2EID"                   => "a265a98a-8948-49f1-8073-e48bc3ec3443"
    "X-VSS-ResourceTenant"          => "f25493ae-1c98-41d7-8a33-0be75f5fe603"
    "X-VSS-S2STargetService"        => "00000030-0000-8888-8000-000000000000/visualstudio.com"
    "X-VSS-SenderDeploymentId"      => "1a640fd9-ac39-bf02-92ac-d7705ca2547a"
  }
  :host              => ".pkgs.visualstudio.com"
  :local_port        => 57848
  :method            => :get
  :omit_default_port => true
  :path              => "/SYSTEMS/_packaging/Gdsp/npm/registry/@backend%2Fcommon-utils"
  :port              => 443
  :query             => nil
  :reason_phrase     => "Unauthorized"
  :scheme            => "https"
  :status            => 401
  :status_line       => "HTTP/1.1 401 Unauthorized\r\n"
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:313:in `check_npm_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): volvogroup-dvp.pkgs.visualstudio.com/DSBS-SYSTEMS/_packaging/Gdsp/npm/registry (Dependabot::PrivateSourceAuthenticationFailure)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:271:in `npm_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:108:in `valid_npm_details?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:36:in `latest_version_from_registry'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb:297:in `latest_released_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb:305:in `latest_version_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb:39:in `latest_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/update_checkers/base.rb:234:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/update_checkers/base.rb:192:in `version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/common/lib/dependabot/update_checkers/base.rb:33:in `up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-f8c48ef2f569/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb:27:in `up_to_date?'
	from bin/update-script.rb:570:in `block in <main>'
	from bin/update-script.rb:533:in `each'
	from bin/update-script.rb:533:in `<main>'
##[debug]Exit code 1 received from tool '/usr/bin/docker'

**Comment by mburumaxwell** [comment]
Hi @Sandy1438 sorry it took me a while to get here. Seems like a permissions issue.

Ensure

1. The PAT has `Packaging Read` permission.
2. The user owning the PAT has been granted permissions to access the feed. An easy way for this is to give `Contributor` permission the `[{project_name}]\Contributors` group under the `Feed Settings -> Permissions` page. The page has the url format: `https://dev.azure.com/{organization}/{project}/_packaging?_a=settings&feed={feed-name}&view=permissions`.

Before using the PAT with dependabot, you can test by making a HTTP request to the same URL in Postman using Basic credentials with an empty username and the PAT as the password.

**Comment by Sandy1438** [comment]
Thanks, I was able to resolve.
