### ISSUE TITLE
Option for single/consolidated PR for update instead of multiple PR

### ISSUE THREAD

**Issue by Sandy1438** [tinglesoftware/dependabot-azure-devops#554]
Hi All,

Curious to know if there is any options to tell dependabot to consolidate all all pull request to a single consolidated PR.

BR,
Sandeep.

**Comment by mburumaxwell** [comment]
Hi Sandeep,

If there is such functionality, it would need to come from the main tool at https://github.com/dependabot/dependabot-core
As far as I know, such an option does not exist even on the GitHub-hosted version of dependabot.

Maybe you could ask the question in at that repo?
