### ISSUE TITLE
Keep getting "Dependabot::RepoNotFound" and "Dependabot::Clients::Azure::NotFound"

### ISSUE THREAD

**Issue by verycrispy** [tinglesoftware/dependabot-azure-devops#56]
I've installed the extension in our Azure DevOps environment and created a PAT with full access. No matter what I fill in for the parameters "directory" and "targetBranch", I keep on getting "Dependabot::RepoNotFound" and "Dependabot::Clients::Azure::NotFound" errors.
Below you see the log. In the log I've replaced the real names with the placeholders [Organisation name], [project name] and [repo name].
The default branch is 'develop'. I've tried providing a specific branch, providing 'develop' omitting the parameter.
With the setting for nuget, I've tried providing a folder where a nuget.config is provided, but also in the root, there is a nuget.config.
I've tried with npm, pointing to a folder where a package.json is located.
But all the time it results in the same error.

I see the URL '[OrganisationName].visualstudio.com' is used while nowadays you see 'https://dev.azure.com/[OrganisationName]'. Could that be related? I don't see a way of changing that, so I can't try that out.
I guess spaces in project names can be used?

Your help is really appriciated!

`/vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:444:in `rescue in default_branch_for_repo': Dependabot::RepoNotFound (Dependabot::RepoNotFound)
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:440:in `default_branch_for_repo'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.133.5/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.133.5/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.133.5/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:155:in `<main>'
/vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/clients/azure.rb:207:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/clients/azure.rb:57:in `fetch_default_branch'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:442:in `default_branch_for_repo'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.133.5/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.133.5/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /vendor/ruby/2.6.0/gems/dependabot-nuget-0.133.5/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:155:in `<main>'
Using '[OrganisationName].visualstudio.com' as hostname
Fetching nuget dependency files for [OrganisationName]/[Project name]/_git/[Repo name]
Targeting 'default' branch under '/' directory
Using 'auto' versioning strategy
##[debug]Exit code 1 received from tool '/usr/bin/docker'
##[debug]STDIO streams have closed for tool '/usr/bin/docker'
##[debug]task result: Failed
##[error]The process '/usr/bin/docker' failed with exit code 1
`

**Comment by thviQit** [comment]
Hi @verycrispy 

I've had a similar issue. It could be an idea to check the Repository Permissions for the user running the build.

In your Azure Devops settings --> Repositories
![image](https://user-images.githubusercontent.com/34093316/109322994-4169bf00-7853-11eb-81f5-129246d55c29.png)

Go to Permissions
![image](https://user-images.githubusercontent.com/34093316/109323044-50e90800-7853-11eb-8c30-0d390bf7071d.png)

Find the user used for running the build agent builds - usually something like `Project Collection Build Service ({Your Org})`
![image](https://user-images.githubusercontent.com/34093316/109323160-72e28a80-7853-11eb-93ec-bb9375bf1164.png)

Check that both `Contribute to pull requests` and `Create branch` is set to allow
![image](https://user-images.githubusercontent.com/34093316/109323586-eab0b500-7853-11eb-864f-f500c7efc1ed.png)

Hope it helps 🙂

**Comment by verycrispy** [comment]
Hi @thviQit,

Thank you for your message!
Unfortunately that doesn't seem to change anything. I already used a PAT with full access, but now with or without that token, te results are the same.

Thanks again,
Chris

**Comment by mburumaxwell** [comment]
Hi @verycrispy 

Is your organisation using the new URL (https://dev.azure.com/{organisation})?

**Comment by verycrispy** [comment]
@mburumaxwell 
We used both URL's to access DevOps, but the toggle on the organization settings was not set to use the new URL.
![image](https://user-images.githubusercontent.com/18570226/111288319-582a5700-8644-11eb-9b0a-4c19c2b3e740.png)
Now I've set the toggle to use the new URL and now the Dependabot extension does work!
So maybe this can be fixed in the code? Or maybe it can be put in the documentation somewhere? I think there will be others that didn't change the toggle that will run into issues. 
I hope this solution helps.

**Comment by MikeAtETI** [comment]
that would certainly be a useful fix, as my understand (and I may be wrong) is turning that on would break the existing *.visualstudio.com refs you may have in cloned git repositories

**Comment by michael-letcher** [comment]
I'm having the same issue

adding `AZURE_HOSTNAME` didn't solve it for me either.


```
/vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:74:in `rescue in commit': Dependabot::BranchNotFound (Dependabot::BranchNotFound)
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:67:in `commit'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:369:in `_fetch_file_content'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:139:in `fetch_file_from_host'
	from /vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.133.5/lib/dependabot/npm_and_yarn/file_fetcher.rb:51:in `package_json'
	from /vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.133.5/lib/dependabot/npm_and_yarn/file_fetcher.rb:36:in `fetch_files'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:155:in `<main>'
/vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/clients/azure.rb:207:in `get': Dependabot::Clients::Azure::NotFound (Dependabot::Clients::Azure::NotFound)
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/clients/azure.rb:46:in `fetch_commit'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:72:in `commit'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:369:in `_fetch_file_content'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:139:in `fetch_file_from_host'
	from /vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.133.5/lib/dependabot/npm_and_yarn/file_fetcher.rb:51:in `package_json'
	from /vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.133.5/lib/dependabot/npm_and_yarn/file_fetcher.rb:36:in `fetch_files'
	from /vendor/ruby/2.6.0/gems/dependabot-common-0.133.5/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./update-script.rb:155:in `<main>'
Using 'RETACTED.visualstudio.com' as hostname
Fetching npm_and_yarn dependency files for RETACTED/RETACTED/_git/zinc-core
Targeting 'master' branch under '/' directory
Using 'bump_versions' versioning strategy
##[error]The process '/usr/bin/docker' failed with exit code 1

```

**Comment by MikeAtETI** [comment]
if its a simple as setting a variable in the pipeline somewhere to tell it what the dev.azure.com/<organisation> should be then that would be a great workaround @mburumaxwell

**Comment by passionateprogrammersguild** [comment]
Try running this locally with docker.  The first step is to generate a PAT (Personal Access Token) within azure devops, and then run the command below filling in your details.  I found the documentation at https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/src/script/README.md to be really useful.

docker run --rm -t \
           -e AZURE_ACCESS_TOKEN={PAT} \
           -e AZURE_ORGANIZATION={YOUR_ORGANIZATION} \
           -e AZURE_PROJECT={PROJECT_NAME} \
           -e AZURE_REPOSITORY={YOUR_REPO_NAME} \
           -e DEPENDABOT_PACKAGE_MANAGER=npm_and_yarn \
           -e DEPENDABOT_DIRECTORY={PATH_TO_PACKAGE.JSON} \
           -e DEPENDABOT_TARGET_BRANCH=develop \
           -e DEPENDABOT_VERSIONING_STRATEGY=auto \
           -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 \
           tingle/dependabot-azure-devops:0.2.0

**Comment by mburumaxwell** [comment]
@MikeAtETI , @michael-letcher the only way dependabot will work with Azure DevOps repositories is by using the new organization URL. Toggling this on does not affect the old URLs, I can still access ours via the old hostname. Some of our old repositories still use the old URL format for private feeds.

**Comment by mburumaxwell** [comment]
See also https://github.com/tinglesoftware/dependabot-azure-devops/issues/27#issuecomment-768054722
