### ISSUE TITLE
Allow us to specify a location for the dependabot.yml file.

### ISSUE THREAD

**Issue by DaleMckeown** [tinglesoftware/dependabot-azure-devops#574]
Hi,

The addition of support for the dependabot.yml file is really great - https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file.

Could an option be added to the Azure extension task to allow us to specify a path for the dependabot config file? Often project structures are complexed, and being forced to add the file at `.github/dependabot.yml` can add additional noise to a project repository.

Being able to supply a path to the config file will allow us to tidy up our repository settings into a single `Automation` folder, keeping our projects neat and tidy.

**Comment by InvertedLlama** [comment]
I was just looking for this feature, I'm not a big fan of having a .github directory when we use Azure Devops for our repos and pipelines. Would be better if we could place it in /pipelines along with our pipeline related files.

**Comment by TPMartin** [comment]
> I was just looking for this feature, I'm not a big fan of having a .github directory when we use Azure Devops for our repos and pipelines. Would be better if we could place it in /pipelines along with our pipeline related files.

The extension supports having the dependabot.yml inside a .azuredevops folder in your repo, if it is the .github naming that you dont want to use.
