### ISSUE TITLE
Add release notes as comments

### ISSUE THREAD

**Issue by hbendev** [tinglesoftware/dependabot-azure-devops#579]
Would be nice if the extension allowed to save release notes of the dependencies as PR comments. I see 2 advantages of the switch:
1. Work items wouldn't automatically be mentioned by the merge commit. If the release note contains Azure's `#1234` [ticket linking syntax](https://learn.microsoft.com/en-us/azure/devops/repos/git/resolution-mentions?view=azure-devops), the accidentally mentioned ticket number could conflict with other automations, like [Work Item Updater](https://marketplace.visualstudio.com/items?itemName=BlueBasher.bluebasher-workitemupdater) or the built-in [auto-close feature](https://learn.microsoft.com/en-us/azure/devops/boards/work-items/auto-complete-work-items-pull-requests?view=azure-devops).
2. When updating by multiple versions, it could allow seperate validation of the changes comment-by-comment. Commit description could still be explicitly edited.

My pain point is 1. and I'm open to other suggestions and to help with the implementation.

**Comment by hbendev** [comment]
Okay. I was not aware of how dependabot works itself, nor how this project integrates it. I don't think what I desire is a small change, and it seems the discussion should start in dependabot-core instead.

The only other thing I can think of is reusing the commit's description instead, as this seems possible after taking a look at [the source](https://github.com/dependabot/dependabot-core/blob/a72d5988ceb89ba5e7b79613cd9c4c94e52efdd1/common/lib/dependabot/pull_request_creator.rb#L168), but I don't think this is a feature many would use.

**Comment by mburumaxwell** [comment]
@hbendev If I understand you correctly, you would like for the PR description that describe the changes to exist in the final commit? If this is the case, I recently discovered that when auto complete is enabled and the merge strategy is `squash`, the final commit is very empty. To fix this, we should pass the merge commit message when enabling auto complete. As of now, you can work around this by removing disabling auto complete so that when you complete the PR (you can still squash), the UI will automatically populate the commit message from the PR description into the commit message unless you override that.

As regards release notes, I do recall there being a lack of docs on how this should be done by library maintainers. See https://github.com/dependabot/dependabot-core/issues/6225

From January this year, you will now get release notes, changelog and a list commits for packages published in Azure DevOps. See:
- https://github.com/dependabot/dependabot-core/pull/6321
- https://github.com/dependabot/dependabot-core/pull/6343
- https://github.com/dependabot/dependabot-core/pull/6351

Let me know if answers it

**Comment by hbendev** [comment]
@mburumaxwell What I ultimately want to achieve is that none of the commits created by dependabot contain a reference to an actual work item in my own Azure DevOps project. Changelogs imported could cause automatically resolution of unwanted tickets.

This is because the description of the PR created contains the raw (but truncated) changelog of the dependency.
<details><summary>Example:</summary>
<p>
<img src="https://user-images.githubusercontent.com/22564005/227945701-a014885d-e70f-4eee-8e0b-5f6ed9b19abd.png"/>
</p>
</details> 

On the other hand, the commit's description only contains references.
<details><summary>Example:</summary>
<p>
<img src="https://user-images.githubusercontent.com/22564005/227944729-7a748170-0a23-4ab4-bf5e-9bfb59fb642a.png"/>
</p>
</details>

I know I can edit the PR's description manually, or use some other merge method to avoid mentioning tickets, but I'd like it to be configurable in some way or other.

My initial suggestion was to move release notes to comments of the PR one-by-one (one comment for each version), but I'm open to other ideas.

**Comment by hbendev** [comment]
@mburumaxwell What I ultimately want to achieve is that none of the commits created by dependabot contain a reference to an actual work item in my own Azure DevOps project. Changelogs imported could cause automatically resolution of unwanted tickets.

This is because the description of the PR created contains the raw (but truncated) changelog of the dependency.
<details><summary>Example:</summary>
<p>
<img src="https://user-images.githubusercontent.com/22564005/227945701-a014885d-e70f-4eee-8e0b-5f6ed9b19abd.png"/>
</p>
</details> 

On the other hand, the commit's description only contains references.
<details><summary>Example:</summary>
<p>
<img src="https://user-images.githubusercontent.com/22564005/227944729-7a748170-0a23-4ab4-bf5e-9bfb59fb642a.png"/>
</p>
</details>

I know I can edit the PR's description manually, or use some other merge method to avoid mentioning tickets, but I'd like it to be configurable in some way or other.

My initial suggestion was to move release notes to comments of the PR one-by-one (one comment for each version), but I'm open to other ideas.

**Comment by mburumaxwell** [comment]
From what I know, the automatic resolution of issues in Azure DevOps is controlled by `transitionWorkItems` in the auto-complete settings of the PR as described in [the docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.teamfoundation.sourcecontrol.webapi.gitpullrequestcompletionoptions.transitionworkitems?view=azure-devops-dotnet).

When the updater sets auto-complete, `transitionWorkItems` is set to false; see line 61 of the code below:
https://github.com/tinglesoftware/dependabot-azure-devops/blob/63870c5921df639cc3d01d1b9e39d8c5c6370836/updater/bin/azure_helpers.rb#L51-L63

However, if you do not have auto-complete enabled in the updater (via the extension or server), you would end up setting it up or completing manually. This is where you are likely enabling `transitionWorkItems` by checking the box described as `Complete associated work items after merging` or it happens automatically by some policy. You can confirm this in the PRs where that happens by checking the http response body when the PR is retrieved (should be available in the Network tab of the developer options in Chrome)

**Comment by hbendev** [comment]
Thanks for your time and the details, however, I have a custom automation set up that modifies tasks in a custom pipeline, and I'm not using the built-in functionality to close them automatically. This process picks up the tasks linked to the pipeline itself: 
![image](https://user-images.githubusercontent.com/22564005/231897751-c5c6f1fe-47cb-422e-899a-a92493163ac0.png)

---
The work items can get linked multiple ways AFAIK, but what I want to avoid when using debendabot is to have no extra work item referenced accidentally. If the release notes contain a link to an issue/pr on github (for example: 
> [7d39c2c](https://github.com/AzureAD/microsoft-authentication-library-for-js/commit/7d39c2c90527a41115556ff05cfb6b84e30fac0a)  Token cache optimization ([#5806](https://redirect.redirect.github.com/AzureAD/microsoft-authentication-library-for-js/issues/5806))

then, the issue #5806 from my own project might be mentioned in the merge commit, if I forget to change the PR's description.

Sorry for not being clear enough.
