### ISSUE TITLE
Extension: `extraEnvironmentVariables` parameter does not work as expected

### ISSUE THREAD

**Issue by NenoLoje** [tinglesoftware/dependabot-azure-devops#584]
#### Works great:

`extraEnvironmentVariables: 'EXCON_DEBUG=1'`

#### Does not work (= does not do anything):

* `extraEnvironmentVariables: 'EXCON_DEBUG=1;GIT_AUTHOR_EMAIL=dependabot@example.org;GIT_AUTHOR_NAME=dependabot'`
  (`EXCON_DEBUG=1` works, but the `GIT_AUTHOR_NAME` does not)

* `extraEnvironmentVariables: 'GIT_AUTHOR_NAME=dependabot;'`
  (does not change the git author name)

**Comment by mburumaxwell** [comment]
Could you confirm the input name?
Seems like you're using `excludeRequirementsToUnlock` instead of `extraEnvironmentVariables`

**Comment by NenoLoje** [comment]
@mburumaxwell Sorry for the confusion! I fixed the auto-correct typo and now the `EXCON_DEBUG=1` does get recognized, but the `GIT_AUTHOR_NAME` has not effect (not sure about GIT_AUTHOR_EMAIL as I'm not sure if it's displayed on Azure Repos web anywhere)

**Comment by mburumaxwell** [comment]
@NenoLoje you should use `DEPENDABOT_AUTHOR_EMAIL` and `DEPENDABOT_AUTHOR_NAME` as indicated in the [docs](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/updater.md#environment-variables).

The variables you are using were renamed in version 0.12.0, see [release notes](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.12.0)

**Comment by NenoLoje** [comment]
> @NenoLoje you should use `DEPENDABOT_AUTHOR_EMAIL` and `DEPENDABOT_AUTHOR_NAME` as indicated in the [docs](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/updater.md#environment-variables).
> 
> The variables you are using were renamed in version 0.12.0, see [release notes](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/0.12.0)

I can confirm it works as expected using these variable names. Thanks!
