### ISSUE TITLE
Avoid rate limits to Github

### ISSUE THREAD

**Issue by pheeblyboos** [tinglesoftware/dependabot-azure-devops#602]
Hi all,

I have been experimenting in setting up ADO dependabot in a test subscription.
It seems to be running fine and creating PRs, however after some time it starts throwing this error:
`2023-04-24T13:31:45.0919161Z E, [2023-04-24T13:31:45.091128 #1] ERROR -- : Error while generating commit message: GET https://api.github.com/repos/dotnet/aspnetcore/contents/docs?ref=v7.0.5: 403 - API rate limit exceeded for <IP REDACTED>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting`

It seems related to fetching the metadata from Github. I can imagine when Dependabot ADO runs on an agent it does a lot of calls to Github to fetch and check these dependencies.

A solution on my side was to follow the advice in the error message and add a Github service connection to the pipeline configuration. This however is not documented anywhere in your documentation and took me quite some time to troubleshoot. If this is not done, it results in getting empty PR fields. Is it possible to include this in the documentation so it's clear that this can happen when not having a Github account linked?

Keep up the great work :)

**Comment by mburumaxwell** [comment]
@pheeblyboos thanks for the feedback.
We accept contributions even for documentation.
