### ISSUE TITLE
PNPM support?

### ISSUE THREAD

**Issue by AndrewCraswell** [tinglesoftware/dependabot-azure-devops#684]
Dependabot has released an update to support `pnpm` package manager, and the associated [feature request](https://github.com/dependabot/dependabot-core/issues/1736) was closed as completed. The docs have also been updated to show the new package manager [support matrix](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem).

I've been trying to verify the changes in our Azure Devops repo, where we use pnpm `v8.6.5` and Dependabot via this extension. I'm seeing the package.json file is having the proper version bump, but the `pnpm-lock.yaml` (using version `6.0`) is not being updated. This lead me to wonder if maybe the Dependabot Azure Devops extension is not yet using the latest version of Dependabot?

If it is, do you have any ideas about increasing logging to see why the lockfile is not being updated and included in the PRs that are opened?

**Comment by mburumaxwell** [comment]
@AndrewCraswell it is easier for me to work on this if you can provide a repro. I have zero experience with pnpm

**Comment by hbendev** [comment]
In my case, even though I use the most recent version (`pnpm -v` outputs  `8.6.7`) and the lockfile contains `lockfileVersion: '6.0'`, the job fails with:

```shell
Parsing dependencies information
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-8b4e7c7c59ff/npm_and_yarn/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:23:in `rescue in block in parsed': /pnpm-lock.yaml not parseable (Dependabot::DependencyFileNotParseable)
```

The project is a workspace with a single lockfile.

**Comment by AndrewCraswell** [comment]
> @AndrewCraswell it is easier for me to work on this if you can provide a repro. I have zero experience with pnpm

My apologies, I can try to put together a repro but it would need to be over a weekend. Assembling a minimal reproduction would be a good first step, and I need to do this anyways to provide an example for how to implement Dependabot in our org.

**Comment by mburumaxwell** [comment]
> > @AndrewCraswell it is easier for me to work on this if you can provide a repro. I have zero experience with pnpm
> 
> 
> 
> My apologies, I can try to put together a repro but it would need to be over a weekend. Assembling a minimal reproduction would be a good first step, and I need to do this anyways to provide an example for how to implement Dependabot in our org.

Yes, this is the way. 🙂

**Comment by hbendev** [comment]
Hi @mburumaxwell! Here's a very minimal example: [https://dev.azure.com/hajnalbendeguz/pnpm-dependabot](https://dev.azure.com/hajnalbendeguz/pnpm-dependabot). Unfortunately, it haven't received access to use hosted pipeline agents just yet, so the pipeline can't start, but a request doesn't take more than a few days as I read.

**Comment by AndrewCraswell** [comment]
Okay, I've put together a minimal reproduction and dropped the same repo in Github and in DevOps so we can verify it works in Github.

[Github Repo](https://github.com/AndrewCraswell/ado-dependabot)

[DevOps Repo](https://acraswell.visualstudio.com/_git/ADO%20Dependabot)
[DevOps Pipeline](https://acraswell.visualstudio.com/ADO%20Dependabot/_build?definitionId=1)

Interestingly, in the Azure DevOps repro the pipeline has started failing with parse errors. Two weeks back the pipeline would succeed but the PRs that would open would only include changes to the `package.json` file, and not lockfile changes. Now the pipeline [is just failing](https://acraswell.visualstudio.com/ADO%20Dependabot/_build/results?buildId=3&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5).

<img width="1328" alt="image" src="https://github.com/tinglesoftware/dependabot-azure-devops/assets/1908292/2ba44319-4db5-4970-9fc4-f8cd90234d46">

**Comment by AndrewCraswell** [comment]
I was able to look at our private repo build history and see what the output was when it was successfully creating the PRs (albeit without the changes to lockfile). Interestingly it seems that the lockfile was not being detected. Only the `package.json` is being found:

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/1908292/08b6a960-8e33-4635-b09e-0cef2902e0e7)

This contrasts with the minimal reproduction that I put together today, where the lockfile is found but then the parse error is encountered.

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/1908292/121365ca-7c06-4b1c-a106-5e19135c9d5f)

**Comment by mburumaxwell** [comment]
HI @AndrewCraswell
Thanks for offering the repro. I see the issue is parsing the lock file.
This happens in dependabot-core.
The only known way to troubleshoot this is by debugging the Ruby code. You can do this using either this repo or the dependabot-core one.

I should get to this in the course of the week if you will not have managed to get a solution.

**Comment by AndrewCraswell** [comment]
This unfortunately is outside of my comfort zone to provide a PR in Ruby. But in case it helps, I've put up a small bounty on the work item.
https://app.bountysource.com/issues/123710224-pnpm-support

**Comment by mburumaxwell** [comment]
Just an update, I have managed to repro the issue. Hopefully, it does not take too long to resolve.

**Comment by mburumaxwell** [comment]
@AndrewCraswell 

In the latest version, this has been addressed.
The release is major and I hope it does not affect your other setups (if any).
Release notes: [1.20.0](https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.20.0)
Validation build: https://dev.azure.com/tingle/dependabot/_build/results?buildId=63019&view=results

**Comment by AndrewCraswell** [comment]
Just verified it's working! I think it's safe to close the issue :)

**Comment by hbendev** [comment]
Thanks a lot! It does appear to be working, but sadly I bumped into errors which didn't happen while I was still using npm.

1. Azure DevOps has a 4000 character limit on the description, and I think it's now not, or incorrectly truncated. See example pipeline here: https://dev.azure.com/hajnalbendeguz/pnpm-dependabot/_build/results?buildId=22&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1f93c1a3-255b-505a-53c9-c382114aabf5&l=296

2. The pipeline is breaking on workspace dependencies, but it has to be tweaked in dependabot core I think.
```bash
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.224.0/lib/dependabot/npm_and_yarn/requirement.rb:26:in `parse': Illformed requirement ["workspace:*"] (Gem::Requirement::BadRequirementError)`
```

```package.json
{
  "dependencies": {
    "@private/package": "workspace:*",
  }
}
```

This latter error even happens when package updates are explicitly ignored by `dependency-name` rules in `dependabot.yml`.

**Comment by mburumaxwell** [comment]
@AndrewCraswell great! I will proceed

@hbendev , 
1. Let' use #723 to track the 4k limit issue. I know there was a major change in dependabot-core recently, see https://github.com/dependabot/dependabot-core/pull/7487
2. Indeed, this looks like an issue to track in dependabot-core. Given a repro and a separate issue, I can confirm and maybe fix it over there.

**Comment by mburumaxwell** [comment]
@AndrewCraswell I recently realized bountysource has issues, starting to look like a Ponzi scheme. No responses from their support and it appears that's been going on for a while.

https://github.com/bountysource/core/issues/1539

I recommend that you seek a refund, via PayPal.

GH sponsors is the better alternative.

**Comment by AndrewCraswell** [comment]
Ahh that's too bad. It used to be great Pre-covid. Sounds like things have gone downhill. I will look into GH Sponsors, unless you would prefer something more direct. Feel free to shoot me an email ajcraswell@gmail.com

**Comment by mburumaxwell** [comment]
@hbendev Your second issue where you get the error message `Illformed requirement ["workspace:*"]` indeed occurs. when you have a workspace referencing another in a monorepo. I think https://github.com/dependabot/dependabot-core/issues/7501 tracks that and related issues. If not, you could open a new issue and tag me along.

@AndrewCraswell , GH sponsors is okay and I believe more transparent.
