### ISSUE TITLE
Running plugin on Azure DevOps on prem SSL certificate problem

### ISSUE THREAD

**Issue by Glopter** [tinglesoftware/dependabot-azure-devops#735]
Hi Team!

Thank you for providing your Azure DevOps plugin. I'm trying set it up on an Azure DevOps on prem instance and get the following error:

```
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/excon-0.99.0/lib/excon/ssl_socket.rb:150:in `connect_nonblock': SSL_connect returned=1 errno=0 peeraddr=10.2.244.161:443 state=error: certificate verify failed (unable to get local issuer certificate) (OpenSSL::SSL::SSLError) Unable to verify certificate. This may be an issue with the remote host or with Excon. Excon has certificates bundled, but these can be customized: (Excon::Error::Certificate)

            `Excon.defaults[:ssl_ca_path] = path_to_certs`
            `ENV['SSL_CERT_DIR'] = path_to_certs`
            `Excon.defaults[:ssl_ca_file] = path_to_file`
            `ENV['SSL_CERT_FILE'] = path_to_file`
            `Excon.defaults[:ssl_verify_callback] = callback`
                (see OpenSSL::SSL::SSLContext#verify_callback)
```

Is there a way to provide a user defined SSL certificate or a custom Docker image using this plugin?

**Comment by mburumaxwell** [comment]
You can indeed create custom images but run them outside the extension. You will need to create an image for each of the ecosystems that you use and will also carry the burden of maintaining them. This is why you might find it easier to solve the SSL/TLS problem on your OnPrem installation instead (local DNS stuff may be involved) than to create your own docker images.

**Comment by Glopter** [comment]
Thanks for your answer. The solution to the SSL/TLS problem on prem is out of my reach. So I'll go with the Docker images.

**Comment by mburumaxwell** [comment]
All the best!
