### ISSUE TITLE
Azure DevOps Dependabot Extension - Support for Automatic PR Updates on Target Branch Changes

### ISSUE THREAD

**Issue by PaulMoney** [tinglesoftware/dependabot-azure-devops#784]
Hello,

I'm wondering if the Azure DevOps Dependabot extension supports automatic updates to Dependabot pull requests (PRs) when changes are made to the target branch, similar to how GitHub Dependabot functions. In GitHub, Dependabot automatically updates PRs when new code is merged into the target branch. This behavior ensures that the PRs stay up-to-date with the latest changes in the codebase. 

I'd like to understand whether the Azure DevOps Dependabot extension offers this feature.

Thanks in advance for any support.

**Comment by mburumaxwell** [comment]
Currently this only works if you rerun the task. Doing so will also attempt to resolve merge conflicts. Closing unwanted PRs will only work when there is a single entry in your `updates` node (see #451).

The [server component](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/server.md) is set to handle that among (other things) in the future.

**Comment by PaulMoney** [comment]
Thanks for the response. Perhaps the **server component** will be the best option to choose when working with Dependabot in Azure DevOps in the future.
