### ISSUE TITLE
Show as Task Failure when error occurs

### ISSUE THREAD

**Issue by acgritt** [tinglesoftware/dependabot-azure-devops#81]
I was able to get everything working using a PAT. It seems the default Build account didn't have permissions to create the PR. However, when that was the case I was seeing this in the logs:

![image](https://user-images.githubusercontent.com/10471937/114932241-e12bde00-9dfc-11eb-96c9-f130cc077c38.png)

At the same time, the task was also showing up as a Success:

![image](https://user-images.githubusercontent.com/10471937/114932323-f6a10800-9dfc-11eb-8582-1f865630a639.png)

It would be nicer if there is a failure to show it as the task failed so that it can be identified if/when a PAT has expired or something needs to be further investigated

**Comment by mburumaxwell** [comment]
Hi @acgritt kindly share the next line in the logs (should be line 152). It contains the message

**Comment by acgritt** [comment]
@mburumaxwell sorry about that here is the full stack:
![image](https://user-images.githubusercontent.com/10471937/115022713-622db880-9e83-11eb-8e7c-2f2301dadce6.png)

**Comment by mburumaxwell** [comment]
@acgritt 

I have looked for a way to tell that `pr_creator.create` failed via exception but there is none. The only alternative I can see is throwing our own type of exception to handle that. Ideally here:
https://github.com/tinglesoftware/dependabot-azure-devops/blob/70a3286c5564dbdd30e4856f1f14f4f405ff18d4/src/script/update-script.rb#L377-L382

I wonder though, how the logic for throwing exceptions just to catch them feels funny.

Related: #86

**Comment by acgritt** [comment]
@mburumaxwell I agree, it does leave a bad smell, but about the only other way I can think to handle it would be to have an "error" counter and increment that when it fails and then at the end check if it is 0 or not and return as failed.
