### ISSUE TITLE
Registries: 'registry1,registry2' have not been referenced by any update

### ISSUE THREAD

**Issue by bdovaz** [tinglesoftware/dependabot-azure-devops#813]
Since today the task crashes with this error without having touched anything.

The only thing that has changed is that the version of dependabot that uses this task has changed: 1.20.543 ->1.21.566.

How can I fix it?

Thanks!

**Comment by bdovaz** [comment]
Ok, it seems that at some point they have forced that the records have to be explicitly referenced in each `updates` element:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#registries

Do you know anything about this @mburumaxwell?

**Comment by mburumaxwell** [comment]
You can consult the release notes: https://github.com/tinglesoftware/dependabot-azure-devops/releases/tag/1.21.0

Each registry you configure must be referenced in at least one update. This matches the hosted version and, crucially, avoids sending unnecessary credentials to the updater.

This was introduced in #781

**Comment by mburumaxwell** [comment]
Support for `registries: '*'` was skipped because there are too many issues with accessing private registries created here. To help identify them, it is better to have the selection explicit. Maybe later, we can add wildcard support unless you have a case for why it should be immediate.
