### ISSUE TITLE
Provide a way to override repository

### ISSUE THREAD

**Issue by acgritt** [tinglesoftware/dependabot-azure-devops#82]
It would be nice if there were a way to re-use the task in a pipeline so that using one pipeline you could support multiple repositories. As we have several micro-service projects, each in their own repository, it would be more efficient to have it scan each of the repositories as a single run rather than a separate build for each of the individual repositories. If there were a way to provide a repository name as part of the settings and if it isn't there to default to the current repository that would be great.

**Comment by mburumaxwell** [comment]
@acgritt are you using a config file (`.azuredevops/dependabot.yml`)?

**Comment by acgritt** [comment]
I am not. I am just using the standard build yaml and the Hosted tool. I did not see a way within the config file to specify multiple repositories to scan for updates, only a way to setup private package registries. 

To be clear, I was specifically looking at this logic though within the task itself:
![image](https://user-images.githubusercontent.com/10471937/115023791-dddc3500-9e84-11eb-952e-05b352d87da2.png)

As then if we have a structure such as:
- Organization
  - Project A Common Repo
  - Project A Service 1 Repo
  - Project A Service 2 Repo
  - Project A Service 3 Repo
  - Project B Service 1 Repo

Rather than having a separate pipeline for each one that handles the builds and then another that handles the dependabot for that repo, it would be nice have just the one dependabot pipeline for Project A and one for Project B that could run nightly and the one for Project A would scan Common, Service 1, Service 2 and Service 3 repositories. I was thinking that an optional parameter that if specified would be the Repository used and if not, it would use the existing variable as the code does right now.

If there is a way to do what I am suggesting with the use of the config file right now, I would love to know about it, otherwise if you want I could create a PR with the change I am suggesting.

**Comment by mburumaxwell** [comment]
@acgritt ,
There is no way to do that in one single pipeline using the `dependabot` task. You can only accomplish it using multiple docker tasks. You are right about the code section supporting override for the repository name. A PR with the change is definately welcome.
