### ISSUE TITLE
Problem when run docker image ghcr.io/tinglesoftware/dependabot-updater-nuget:1.22.0

### ISSUE THREAD

**Issue by Icakis** [tinglesoftware/dependabot-azure-devops#851]
**Describe the bug**
Hello,
We are currently using the old version tingle/dependabot-azure-devops:0.14.1, pulling the docker image and everything is working as expected.
Now I want to update to latest version which includes the group update feature. 
I'm trying with the way it's described [here](https://github.com/tinglesoftware/dependabot-azure-devops/blob/main/docs/updater.md)

##[debug]script=docker run --rm -t \
  -e DEPENDABOT_PACKAGE_MANAGER=nuget \
  -e DEPENDABOT_DIRECTORY=/ \
  -e DEPENDABOT_TARGET_BRANCH=main \
  -e DEPENDABOT_VERSIONING_STRATEGY=auto \
  -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 \
  -e DEPENDABOT_EXTRA_CREDENTIALS='***' \
  -e DEPENDABOT_ALLOW_CONDITIONS \
  -e AZURE_HOSTNAME=dev.azure.com \
  -e AZURE_ACCESS_TOKEN='***' \
  -e AZURE_ORGANIZATION=***\
  -e AZURE_PROJECT=***\
  -e AZURE_REPOSITORY=***\
  ghcr.io/tinglesoftware/dependabot-updater-nuget:1.22.0

Digest: sha256:76b7d39080a82d94b6b88cc99ef2e2e93eea9e080213202fda880c69cde1a2e3
Status: Downloaded newer image for ghcr.io/tinglesoftware/dependabot-updater-nuget:1.22.0
usage: run [update_script|fetch_files|update_files]
##[debug]Exit code 1 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
##[error]Bash exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]Bash exited with code '1'.
##[debug]task result: Failed
##[debug]Processed: ##vso[task.complete result=Failed;done=true;]

**Expected behavior**
Starts and not throwing exception:
 - Host:  Azure DevOps

**Comment by sonnyhcl** [comment]
I had run into sumilar issue, just append `update_script` as argument works for me

**Comment by Icakis** [comment]
> I had run into sumilar issue, just append `update_script` as argument works for me

Thank you!! It's working.
