### ISSUE TITLE
autoApproveUserToken PAT scopes?

### ISSUE THREAD

**Issue by bdovaz** [tinglesoftware/dependabot-azure-devops#853]
It is not documented, I imagine it will be **vso.code_write** as it says in this endpoint (I don't know if it is the one used or a very similar one): https://learn.microsoft.com/en-us/rest/api/azure/devops/git/pull-request-reviewers/create-pull-request-reviewer?tabs=HTTP#scopes

**Comment by mburumaxwell** [comment]
This is correct.

**Comment by bdovaz** [comment]
Can you document it or do I create a PR?

**Comment by mburumaxwell** [comment]
A PR is very much welcome 🤗
