### ISSUE TITLE
requirements.txt Not Found

### ISSUE THREAD

**Issue by saleh1shalabi** [tinglesoftware/dependabot-azure-devops#860]
**Describe the bug**
I repeatedly get the error requirements.txt Not Found in Azure Devops pipeline using dependabot extension.

I tried even move the requirements.txt file into a subfolder and specify the path but still didn't work. the issue seems to be hapning only with requirements.txt file and not other files as Pipfile or Pipfile.lock

**To Reproduce**
1. create new python project and add requirements.txt
2. do not add any pipenv files as Pipfile or Pipfile.lock
3. add .github folder in root path and inside add the dependabot.yml
4. create new pipeline for dependabot and run it
5. you should now get the same issue.
 

**Expected behavior**
It should find the requirements.txt file and try to find newer versions of the deps. 

**Screenshots**
![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/78418332/da5a40ab-9a56-4872-81d9-62978a5319bc)

**Extension (please complete the following information):**
 - Host: [Azure DevOps, Azure DevOps Server]

**Server (please complete the following information):**
 - Region [westeurope]

**Additional context**

```
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-python-0.232.0/lib/dependabot/python/file_fetcher.rb:118:in `check_required_files_present': /requirements.txt not found (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-python-0.232.0/lib/dependabot/python/file_fetcher.rb:82:in `fetch_files'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.232.0/lib/dependabot/file_fetchers/base.rb:76:in `files'
	from bin/update_script.rb:529:in `<main>'

```

**Comment by mburumaxwell** [comment]
Could you redo your issue using the bug report template?
https://github.com/tinglesoftware/dependabot-azure-devops/issues/new?template=bug_report.md

**Comment by saleh1shalabi** [comment]
it is now updated @mburumaxwell, seems okay?

**Comment by mburumaxwell** [comment]
Could you share the contents of your `dependabot.yml` file?
Better yet, how about a repro?

**Comment by saleh1shalabi** [comment]
My dependabot.yml file contains the following. Unfortunately I can't share my repo, how ever I do 100% know that requirements.txt is in the base dir of the project

```yaml

version: 2
registries:
  python-feed:
    type: python-index
    url: https://pkgs.dev.azure.com/<myorg>/_packaging/<myfeed>/pypi/simple
    token: ${{DEPENDABOT_PAT}}
updates:
  - package-ecosystem: "pip"
    registries:
      - python-feed
    directory: "/"
    schedule:
      interval: "weekly"
```
The error logs show the following

```cmd

/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-python-0.237.0/lib/dependabot/python/file_fetcher.rb:123:in `check_required_files_present': /requirements.txt not found (Dependabot::DependencyFileNotFound)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-python-0.237.0/lib/dependabot/python/file_fetcher.rb:86:in `fetch_files'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11141/lib/types/private/methods/call_validation.rb:256:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11141/lib/types/private/methods/call_validation.rb:256:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11141/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.237.0/lib/dependabot/file_fetchers/base.rb:108:in `files'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11141/lib/types/private/methods/call_validation.rb:256:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11141/lib/types/private/methods/call_validation.rb:256:in `validate_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11141/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
	from bin/update_script.rb:503:in `<main>'
```

**Comment by mburumaxwell** [comment]
@saleh1shalabi 
Sorry it has taken me a while to get back on this.

I tried to recreate something similar to yours and it seems to be working.
Checkout [this repo](https://dev.azure.com/tingle/dependabot/_git/repro-860?version=GBmain) and [the pipeline run](https://dev.azure.com/tingle/dependabot/_build/results?buildId=72491&view=results).

Could this have been a transient error in the upstream repository?
