### ISSUE TITLE
What's recommended way to consume docker image from GHCR

### ISSUE THREAD

**Issue by sonnyhcl** [tinglesoftware/dependabot-azure-devops#864]
**Describe the bug**
I have used a fixed docker image version as `1.22` in my script. while seems ghcr only keeps latest 20 tags, then 1.22 is not exist right now, only 1.22.1 exists now.
While it's hard to us to detect the tag change. Is there any recommended way to consume a stable docker image version?

**To Reproduce**
```
docker pulling image && docker pull --quiet ghcr.io/tinglesoftware/dependabot-updater-maven:1.22
Error response from daemon: manifest unknown
```

**Expected behavior**
User can pull a fixed docker image version successfully

**Screenshots**

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/10840522/75d1c946-a5e6-4ad4-afe7-4a78fda788ca)

**Extension (please complete the following information):**
No

**Server (please complete the following information):**
No

**Additional context**
No

**Comment by ryanbowden** [comment]
Also same issue, We have not Pind the version in the yml. So guess to many new tests ones been created and broke the listening.

**Comment by paul-kraftlauget** [comment]
Workaround:
``` 
steps:
  - task: dependabot@1
    inputs:
      dockerImageTag: 1.22.1-ci0024
 ```

**Comment by sonnyhcl** [comment]
> Workaround:
> 
> ```
> steps:
>   - task: dependabot@1
>     inputs:
>       dockerImageTag: latest
> ```

It would be easily broken if latest image tag has any regression.

**Comment by ryanbowden** [comment]
Seems the issue has been resolved. My pipelines have all ran without issue
