### ISSUE TITLE
Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-gradle:1.22' locally

### ISSUE THREAD

**Issue by jtorrestobena** [tinglesoftware/dependabot-azure-devops#870]
**Describe the bug**
When running pipeline we get following error. This started happening on Sunday 29 October.

/usr/bin/docker run --rm -i -e DEPENDABOT_PACKAGE_MANAGER=gradle -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=10 -e DEPENDABOT_DIRECTORY=/ -e DEPENDABOT_FAIL_ON_EXCEPTION=true -e AZURE_ORGANIZATION=** -e AZURE_PROJECT=****** -e AZURE_REPOSITORY=***** -e AZURE_ACCESS_TOKEN=*** -e AZURE_MERGE_STRATEGY=squash ghcr.io/tinglesoftware/dependabot-updater-gradle:1.22 update_script
Unable to find image 'ghcr.io/tinglesoftware/dependabot-updater-gradle:1.22' locally
docker: Error response from daemon: manifest unknown.
See 'docker run --help'.
##[error]The process '/usr/bin/docker' failed with exit code 125

**To Reproduce**
1. Run standard pipeline, without any special configuration other than what's described in the Azure plugin.

steps:
  - task: dependabot@1

**Expected behavior**
It works as before

**Screenshots**
None

**Extension (please complete the following information):**
 - Host: [e.g. Azure DevOps, Azure DevOps Server]
 - Version dependabot@1

**Additional context**

**Comment by martin-bmc** [comment]
Same for me

**Comment by paul-kraftlauget** [comment]
I'm also experiencing this exact problem. The pipeline worked on Oct 28 @ 2AM UTC. The pipeline failed on Oct 29 @ 2AM UTC.

**Comment by paul-kraftlauget** [comment]
Workaround:

```
steps:
  - task: dependabot@1
    inputs:
      dockerImageTag: 1.22.1-ci0024
  ```

**Comment by jtorrestobena** [comment]
> Workaround:
> 
> ```
> steps:
>   - task: dependabot@1
>     inputs:
>       dockerImageTag: latest
> ```

I can confirm that this workaround solved the issue for us.

**Comment by SchulteMarkus** [comment]
Problem vanished.
