### ISSUE TITLE
package-lock.json causing an error when updating packages

### ISSUE THREAD

**Issue by mFilali** [tinglesoftware/dependabot-azure-devops#896]
**Describe the bug**
When trying to update dependencies of a frontend project in Azure pipeline with dependabot, everything works fine when I delete the package-lock.json file, but got an error when the file exists in the repository.

The repository uses a private registry feed (proget).

**To Reproduce**
1. prepare frontend project with private registry feed
2. install npm packages then push package-lock.json to the repository
3. execute: 

docker run --rm -i -e GITHUB_ACCESS_TOKEN="$(GitHubPAT)" \
                          -e DEPENDABOT_OPEN_PULL_REQUESTS_LIMIT=$PRLimit \
                          -e AZURE_ACCESS_TOKEN="$(AzurePAT)" \
                          -e AZURE_ORGANIZATION="$(AZURE_ORGANIZATION)" \
                          -e AZURE_PROJECT="$project" \
                          -e AZURE_REPOSITORY="$repoName" \
                          -e DEPENDABOT_PACKAGE_MANAGER="$packageManager" \
                          -e DEPENDABOT_DIRECTORY="$directory" \
                          -e DEPENDABOT_TARGET_BRANCH="$branch" \
                          -e DEPENDABOT_EXTRA_CREDENTIALS=$credentials \
                          -e "$ignoreConditions" \
                          ghcr.io/tinglesoftware/dependabot-updater-nuget update_script

**Expected behavior**
PR created 

**Screenshots**

![image](https://github.com/tinglesoftware/dependabot-azure-devops/assets/47419110/25900bbe-eb96-4cd1-b908-de3312161d57)

**Extension (please complete the following information):**
 - Host: Azure DevOps
 - Version: 1.24.0

**Additional context**
I tried deleting the `package-lock.json` file and installing the packages (to create a new one) with different npm versions but still got the same problem.
If I remove the `package-lock.json` file, everything works fine and the PRs are created successfully.

Edit:
I switched to the public npm registry and still get the same error, for info, here is the package.json I use in one of the tests:

```json
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview --port 5050",
    "lint": "eslint . --ext .vue,.js,.jsx,.cjs,.mjs --fix --ignore-path .gitignore"
  },
  "dependencies": {
    "@fortawesome/fontawesome-free": "^6.0.0",
    "@microsoft/signalr": "^6.0.3",
    "axios": "^0.26.0",
    "bootstrap": "^5.1.3",
    "core-js": "^3.21.1",
    "pinia": "^2.0.14",
    "style-loader": "^3.3.1",
    "vue": "^3.2.31",
    "vue-router": "^4.0.12",
    "vue3-treeview": "^0.3.8"
  },
  "devDependencies": {
    "@babel/core": "^7.17.5",
    "@babel/eslint-parser": "^7.17.0",
    "@babel/preset-env": "^7.16.11",
    "@vitejs/plugin-vue": "^2.2.2",
    "eslint": "^8.9.0",
    "eslint-plugin-import": "^2.25.4",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^6.0.0",
    "eslint-plugin-standard": "^5.0.0",
    "eslint-plugin-vue": "^8.2.0",
    "sass": "^1.49.8",
    "sass-loader": "^12.6.0",
    "vite": "^2.8.4"
  }
}
```

I'm not the one who created the frontend apps nor am I an expert in frontend development, but the applications are working fine.

**Comment by mburumaxwell** [comment]
Could you offer a public repro such as https://dev.azure.com/tingle/dependabot/_git/repro-860?version=GBmain

It should include the dependabot.yml, azure-pipelines.yml, package-lock.json, all relevant package.json files, and any other files that may be necessary to reproduce the issue.

**Comment by mburumaxwell** [comment]
Can't repro.
Reopen when there is more information.
